/-
  16·3^k + 17 is not in B/B for every k ≥ 6 with k ≡ 0 (mod 2).
  Generated by guy-f31-bt/lean_gen/gen_lean.py; every step is re-checked by Lean (omega, decide).
-/
import BalancedTernary.TernCore

namespace Tern

set_option maxHeartbeats 4000000
set_option linter.unusedVariables false
set_option maxRecDepth 100000

/-- Carry set for k ≡ 0 (mod 2). -/
inductive F16_p17_2r0 (k : Nat) : Int → Prop
  | z : F16_p17_2r0 k 0
  | c1 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 4 * 3 ^ k + 4 - 4 * 3 ^ i) : F16_p17_2r0 k r
  | c2 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) (hr : r = 4 * 3 ^ k + 4 - 8 * 3 ^ i) : F16_p17_2r0 k r
  | c3 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) (hr : r = 4 * 3 ^ k + 4 - (-8) * 3 ^ i) : F16_p17_2r0 k r
  | c4 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) (h3 : i % 2 = 0) (hr : r = 4 * 3 ^ k + 4 - (-4) * 3 ^ i) : F16_p17_2r0 k r
  | c5 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 2 = 1) (hr : r = 4 * 3 ^ k + 4 - (-4) * 3 ^ i) : F16_p17_2r0 k r
  | c6 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (hr : r = 8 * 3 ^ k + 8 - 8 * 3 ^ i) : F16_p17_2r0 k r
  | c7 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 8 * 3 ^ k + 8 - 16 * 3 ^ i) : F16_p17_2r0 k r
  | c8 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 8 * 3 ^ k + 8 - 4 * 3 ^ i) : F16_p17_2r0 k r
  | s9 (r : Int) (hr : r = 8 * 3 ^ (k - 1) + 6) : F16_p17_2r0 k r
  | s10 (r : Int) (hr : r = 4 * 3 ^ k + 4) : F16_p17_2r0 k r
  | s11 (r : Int) (hr : r = 4 * 3 ^ k + 6) : F16_p17_2r0 k r
  | s12 (r : Int) (hr : r = 16 * 3 ^ (k - 1) + 6) : F16_p17_2r0 k r
  | s13 (r : Int) (hr : r = 20 * 3 ^ (k - 1) + 6) : F16_p17_2r0 k r
  | s14 (r : Int) (hr : r = 8 * 3 ^ k + 6) : F16_p17_2r0 k r
  | s15 (r : Int) (hr : r = 8 * 3 ^ k + 8) : F16_p17_2r0 k r
  | c16 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(4 * 3 ^ k + 4 - 4 * 3 ^ i)) : F16_p17_2r0 k r
  | c17 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) (hr : r = -(4 * 3 ^ k + 4 - 8 * 3 ^ i)) : F16_p17_2r0 k r
  | c18 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) (hr : r = -(4 * 3 ^ k + 4 - (-8) * 3 ^ i)) : F16_p17_2r0 k r
  | c19 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) (h3 : i % 2 = 0) (hr : r = -(4 * 3 ^ k + 4 - (-4) * 3 ^ i)) : F16_p17_2r0 k r
  | c20 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 2 = 1) (hr : r = -(4 * 3 ^ k + 4 - (-4) * 3 ^ i)) : F16_p17_2r0 k r
  | c21 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (hr : r = -(8 * 3 ^ k + 8 - 8 * 3 ^ i)) : F16_p17_2r0 k r
  | c22 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(8 * 3 ^ k + 8 - 16 * 3 ^ i)) : F16_p17_2r0 k r
  | c23 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(8 * 3 ^ k + 8 - 4 * 3 ^ i)) : F16_p17_2r0 k r
  | s24 (r : Int) (hr : r = -(8 * 3 ^ (k - 1) + 6)) : F16_p17_2r0 k r
  | s25 (r : Int) (hr : r = -(4 * 3 ^ k + 4)) : F16_p17_2r0 k r
  | s26 (r : Int) (hr : r = -(4 * 3 ^ k + 6)) : F16_p17_2r0 k r
  | s27 (r : Int) (hr : r = -(16 * 3 ^ (k - 1) + 6)) : F16_p17_2r0 k r
  | s28 (r : Int) (hr : r = -(20 * 3 ^ (k - 1) + 6)) : F16_p17_2r0 k r
  | s29 (r : Int) (hr : r = -(8 * 3 ^ k + 6)) : F16_p17_2r0 k r
  | s30 (r : Int) (hr : r = -(8 * 3 ^ k + 8)) : F16_p17_2r0 k r

theorem F16_p17_2r0.step_z {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = 0)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  subst hr
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.s12 r' (by omega))
  · exact (.s27 r' (by omega))
  · omega

theorem F16_p17_2r0.step_c1 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 4 * 3 ^ k + 4 - 4 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ i = 1 ∨ 2 ≤ i by omega) with rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.s13 r' (by omega))
    · exact (.s26 r' (by omega))
    · omega
  · have : (3 : Int) ^ 1 = 3 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c19 0 r' (by omega) (by omega) (by omega) (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases Nat.mod_two_eq_zero_or_one i with hip | hip
    · -- i % 2 = 0
      rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
      · omega
      · omega
      · omega
      · exact (.c20 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · -- i % 2 = 1
      rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
      · omega
      · omega
      · omega
      · exact (.c19 (i - 1) r' (by omega) (by omega) (by omega) (by omega))

theorem F16_p17_2r0.bd_c1 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 4 * 3 ^ k + 4 - 4 * 3 ^ i) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c1 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 4 * 3 ^ k + 4 - 4 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    exact h0.mod3 (by omega)
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + (-3)) 1 h0 (by omega) (.inl rfl) (by omega)
    exact h1.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + (-11)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + (-4)) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (4 * 3 ^ (k - 3) + (-1)) (-1) h2 (by omega) (.inr rfl) (by omega)
    have h4 := ZF.down (4 * 3 ^ (k - 4) + 0) (-1) h3 (by omega) (.inr rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + (-35)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + (-12)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + (-107)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + (-36)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (4 * 3 ^ (k - 1) + 1 - 4 * 3 ^ (i - 1)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + 0 - 4 * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F16_p17_2r0.step_c2 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) (hr : r = 4 * 3 ^ k + 4 - 8 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 2 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c3 (k - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c18 (i - 1) r' (by omega) (by omega) (by omega) (by omega))

theorem F16_p17_2r0.bd_c2 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = 4 * 3 ^ k + 4 - 8 * 3 ^ i) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c2 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = 4 * 3 ^ k + 4 - 8 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 2 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + (-1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + 0) (-1) h1 (by omega) (.inr rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + (-23)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + (-8)) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (4 * 3 ^ (k - 3) + (-3)) 1 h2 (by omega) (.inl rfl) (by omega)
    exact h3.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + (-215)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + (-72)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 2 9 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 2 9 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 2 9 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (4 * 3 ^ (k - 1) + 1 - 8 * 3 ^ (i - 1)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + 0 - 8 * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F16_p17_2r0.step_c3 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) (hr : r = 4 * 3 ^ k + 4 - (-8) * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 1 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c17 (i - 1) r' (by omega) (by omega) (by omega) (by omega))

theorem F16_p17_2r0.bd_c3 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = 4 * 3 ^ k + 4 - (-8) * 3 ^ i) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c3 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = 4 * 3 ^ k + 4 - (-8) * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 1 ∨ i = 3 ∨ 5 ≤ i by omega) with rfl | rfl | hi
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + 9) 1 h0 (by omega) (.inl rfl) (by omega)
    exact h1.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + 73) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + 24) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (4 * 3 ^ (k - 1) + 1 - (-8) * 3 ^ (i - 1)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + 0 - (-8) * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F16_p17_2r0.step_c4 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) (h3 : i % 2 = 0) (hr : r = 4 * 3 ^ k + 4 - (-4) * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c8 (k - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c16 (i - 1) r' (by omega) (by omega) (by omega))

theorem F16_p17_2r0.bd_c4 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = 4 * 3 ^ k + 4 - (-4) * 3 ^ i) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i k (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c4 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = 4 * 3 ^ k + 4 - (-4) * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i k (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 2 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + 3) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + 13) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + 4) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (4 * 3 ^ (k - 3) + 1) 1 h2 (by omega) (.inl rfl) (by omega)
    have h4 := ZF.down (4 * 3 ^ (k - 4) + 0) 1 h3 (by omega) (.inl rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + 109) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + 36) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 0 1 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 0 1 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 0 1 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (4 * 3 ^ (k - 1) + 1 - (-4) * 3 ^ (i - 1)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + 0 - (-4) * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F16_p17_2r0.step_c5 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 2 = 1) (hr : r = 4 * 3 ^ k + 4 - (-4) * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 1 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c16 (i - 1) r' (by omega) (by omega) (by omega))

theorem F16_p17_2r0.bd_c5 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = 4 * 3 ^ k + 4 - (-4) * 3 ^ i) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 3) (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c5 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = 4 * 3 ^ k + 4 - (-4) * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 3) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 1 ∨ i = 3 ∨ 5 ≤ i by omega) with rfl | rfl | hi
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + 5) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + 2) (-1) h1 (by omega) (.inr rfl) (by omega)
    have h3 := ZF.down (4 * 3 ^ (k - 3) + 1) (-1) h2 (by omega) (.inr rfl) (by omega)
    have h4 := ZF.down (4 * 3 ^ (k - 4) + 0) 1 h3 (by omega) (.inl rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + 37) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + 12) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 3 27 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 3 27 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 3 27 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (4 * 3 ^ (k - 1) + 1 - (-4) * 3 ^ (i - 1)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + 0 - (-4) * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F16_p17_2r0.step_c6 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (hr : r = 8 * 3 ^ k + 8 - 8 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.s14 r' (by omega))
    · exact (.s24 r' (by omega))
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c6 (i - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega

theorem F16_p17_2r0.bd_c6 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) {r : Int} (hr : r = 8 * 3 ^ k + 8 - 8 * 3 ^ i) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c6 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) {r : Int} (hr : r = 8 * 3 ^ k + 8 - 8 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ 4 ≤ i by omega) with rfl | rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    exact h0.mod3 (by omega)
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (8 * 3 ^ (k - 1) + (-5)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (8 * 3 ^ (k - 2) + (-2)) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (8 * 3 ^ (k - 3) + (-1)) 1 h2 (by omega) (.inl rfl) (by omega)
    have h4 := ZF.down (8 * 3 ^ (k - 4) + 0) (-1) h3 (by omega) (.inr rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (8 * 3 ^ (k - 1) + (-21)) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (8 * 3 ^ (k - 1) + (-69)) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := pow3_pos (i - 2)
    have := pow3_le_mul (i - 0) (k - 0) 2 9 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 2 9 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 3 27 (by decide) (by omega)
    have h1 := ZF.down (8 * 3 ^ (k - 1) + 3 - 8 * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)

theorem F16_p17_2r0.step_c7 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 8 * 3 ^ k + 8 - 16 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c22 (k - 1) r' (by omega) (by omega) (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c7 (i - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega

theorem F16_p17_2r0.bd_c7 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 8 * 3 ^ k + 8 - 16 * 3 ^ i) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c7 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 8 * 3 ^ k + 8 - 16 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ 4 ≤ i by omega) with rfl | rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    have h1 := ZF.down (8 * 3 ^ (k - 1) + (-3)) 1 h0 (by omega) (.inl rfl) (by omega)
    exact h1.mod3 (by omega)
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (8 * 3 ^ (k - 1) + (-13)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (8 * 3 ^ (k - 2) + (-4)) (-1) h1 (by omega) (.inr rfl) (by omega)
    have h3 := ZF.down (8 * 3 ^ (k - 3) + (-1)) (-1) h2 (by omega) (.inr rfl) (by omega)
    have h4 := ZF.down (8 * 3 ^ (k - 4) + 0) (-1) h3 (by omega) (.inr rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (8 * 3 ^ (k - 1) + (-45)) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (8 * 3 ^ (k - 1) + (-141)) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := pow3_pos (i - 2)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 3 27 (by decide) (by omega)
    have h1 := ZF.down (8 * 3 ^ (k - 1) + 3 - 16 * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)

theorem F16_p17_2r0.step_c8 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 8 * 3 ^ k + 8 - 4 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 1 ∨ 2 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 1 = 3 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c4 k r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c8 (i - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega

theorem F16_p17_2r0.bd_c8 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 8 * 3 ^ k + 8 - 4 * 3 ^ i) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c8 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 8 * 3 ^ k + 8 - 4 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 1 ∨ i = 2 ∨ i = 3 ∨ 4 ≤ i by omega) with rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (8 * 3 ^ (k - 1) + (-1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (8 * 3 ^ (k - 2) + 0) (-1) h1 (by omega) (.inr rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (8 * 3 ^ (k - 1) + (-9)) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (8 * 3 ^ (k - 1) + (-33)) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := pow3_pos (i - 2)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 3 27 (by decide) (by omega)
    have h1 := ZF.down (8 * 3 ^ (k - 1) + 3 - 4 * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)

theorem F16_p17_2r0.step_s9 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = 8 * 3 ^ (k - 1) + 6)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.c7 (k - 2) r' (by omega) (by omega) (by omega))
  · exact (.c19 (k - 2) r' (by omega) (by omega) (by omega) (by omega))
  · omega

theorem F16_p17_2r0.bd_s9 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 8 * 3 ^ (k - 1) + 6) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F16_p17_2r0.nz_s9 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 8 * 3 ^ (k - 1) + 6) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  intro h0
  subst hr
  exact h0.mod3 (by omega)

theorem F16_p17_2r0.step_s10 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = 4 * 3 ^ k + 4)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · omega
  · omega
  · exact (.s25 r' (by omega))

theorem F16_p17_2r0.bd_s10 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 4 * 3 ^ k + 4) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F16_p17_2r0.nz_s10 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 4 * 3 ^ k + 4) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  intro h0
  subst hr
  have h1 := ZF.down (4 * 3 ^ (k - 1) + 1) 1 h0 (by omega) (.inl rfl) (by omega)
  have h2 := ZF.down (4 * 3 ^ (k - 2) + 0) 1 h1 (by omega) (.inl rfl) (by omega)
  exact h2.mod3 (by omega)

theorem F16_p17_2r0.step_s11 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = 4 * 3 ^ k + 6)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.c8 (k - 1) r' (by omega) (by omega) (by omega))
  · exact (.s25 r' (by omega))
  · omega

theorem F16_p17_2r0.bd_s11 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 4 * 3 ^ k + 6) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F16_p17_2r0.nz_s11 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 4 * 3 ^ k + 6) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  intro h0
  subst hr
  exact h0.mod3 (by omega)

theorem F16_p17_2r0.step_s12 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = 16 * 3 ^ (k - 1) + 6)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.c6 (k - 2) r' (by omega) (by omega) (by omega))
  · exact (.c16 (k - 2) r' (by omega) (by omega) (by omega))
  · omega

theorem F16_p17_2r0.bd_s12 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 16 * 3 ^ (k - 1) + 6) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F16_p17_2r0.nz_s12 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 16 * 3 ^ (k - 1) + 6) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  intro h0
  subst hr
  exact h0.mod3 (by omega)

theorem F16_p17_2r0.step_s13 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = 20 * 3 ^ (k - 1) + 6)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.c8 (k - 2) r' (by omega) (by omega) (by omega))
  · exact (.c17 (k - 2) r' (by omega) (by omega) (by omega) (by omega))
  · omega

theorem F16_p17_2r0.bd_s13 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 20 * 3 ^ (k - 1) + 6) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F16_p17_2r0.nz_s13 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 20 * 3 ^ (k - 1) + 6) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  intro h0
  subst hr
  exact h0.mod3 (by omega)

theorem F16_p17_2r0.step_s14 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = 8 * 3 ^ k + 6)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.s15 r' (by omega))
  · exact (.c16 (k - 1) r' (by omega) (by omega) (by omega))
  · omega

theorem F16_p17_2r0.bd_s14 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 8 * 3 ^ k + 6) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F16_p17_2r0.nz_s14 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 8 * 3 ^ k + 6) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  intro h0
  subst hr
  exact h0.mod3 (by omega)

theorem F16_p17_2r0.step_s15 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = 8 * 3 ^ k + 8)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · exact (.s15 r' (by omega))
  · omega
  · omega
  · omega

theorem F16_p17_2r0.bd_s15 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 8 * 3 ^ k + 8) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F16_p17_2r0.nz_s15 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 8 * 3 ^ k + 8) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  intro h0
  subst hr
  have h1 := ZF.down (8 * 3 ^ (k - 1) + 3) (-1) h0 (by omega) (.inr rfl) (by omega)
  exact h1.mod3 (by omega)

theorem F16_p17_2r0.step_c16 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(4 * 3 ^ k + 4 - 4 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ i = 1 ∨ 2 ≤ i by omega) with rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.s11 r' (by omega))
    · exact (.s28 r' (by omega))
    · omega
  · have : (3 : Int) ^ 1 = 3 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c4 0 r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases Nat.mod_two_eq_zero_or_one i with hip | hip
    · -- i % 2 = 0
      rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
      · exact (.c5 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
      · omega
      · omega
      · omega
    · -- i % 2 = 1
      rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
      · exact (.c4 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
      · omega
      · omega
      · omega

theorem F16_p17_2r0.bd_c16 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(4 * 3 ^ k + 4 - 4 * 3 ^ i)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c16 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(4 * 3 ^ k + 4 - 4 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F16_p17_2r0.step_c17 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) (hr : r = -(4 * 3 ^ k + 4 - 8 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 2 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c18 (k - 1) r' (by omega) (by omega) (by omega) (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c3 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega

theorem F16_p17_2r0.bd_c17 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = -(4 * 3 ^ k + 4 - 8 * 3 ^ i)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c17 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = -(4 * 3 ^ k + 4 - 8 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega

theorem F16_p17_2r0.step_c18 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) (hr : r = -(4 * 3 ^ k + 4 - (-8) * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 1 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c2 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega

theorem F16_p17_2r0.bd_c18 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = -(4 * 3 ^ k + 4 - (-8) * 3 ^ i)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c18 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = -(4 * 3 ^ k + 4 - (-8) * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F16_p17_2r0.step_c19 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) (h3 : i % 2 = 0) (hr : r = -(4 * 3 ^ k + 4 - (-4) * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c23 (k - 1) r' (by omega) (by omega) (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c1 (i - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega

theorem F16_p17_2r0.bd_c19 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = -(4 * 3 ^ k + 4 - (-4) * 3 ^ i)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i k (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c19 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = -(4 * 3 ^ k + 4 - (-4) * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i k (by omega)
  have := pow3_pos i
  omega

theorem F16_p17_2r0.step_c20 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 2 = 1) (hr : r = -(4 * 3 ^ k + 4 - (-4) * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 1 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c1 (i - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega

theorem F16_p17_2r0.bd_c20 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = -(4 * 3 ^ k + 4 - (-4) * 3 ^ i)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 3) (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c20 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = -(4 * 3 ^ k + 4 - (-4) * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 3) (by omega)
  have := pow3_pos i
  omega

theorem F16_p17_2r0.step_c21 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (hr : r = -(8 * 3 ^ k + 8 - 8 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.s9 r' (by omega))
    · exact (.s29 r' (by omega))
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c21 (i - 1) r' (by omega) (by omega) (by omega))

theorem F16_p17_2r0.bd_c21 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) {r : Int} (hr : r = -(8 * 3 ^ k + 8 - 8 * 3 ^ i)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c21 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) {r : Int} (hr : r = -(8 * 3 ^ k + 8 - 8 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega

theorem F16_p17_2r0.step_c22 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(8 * 3 ^ k + 8 - 16 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c7 (k - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c22 (i - 1) r' (by omega) (by omega) (by omega))

theorem F16_p17_2r0.bd_c22 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(8 * 3 ^ k + 8 - 16 * 3 ^ i)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c22 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(8 * 3 ^ k + 8 - 16 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F16_p17_2r0.step_c23 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(8 * 3 ^ k + 8 - 4 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 1 ∨ 2 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 1 = 3 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c19 k r' (by omega) (by omega) (by omega) (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c23 (i - 1) r' (by omega) (by omega) (by omega))

theorem F16_p17_2r0.bd_c23 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(8 * 3 ^ k + 8 - 4 * 3 ^ i)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F16_p17_2r0.nz_c23 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(8 * 3 ^ k + 8 - 4 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F16_p17_2r0.step_s24 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = -(8 * 3 ^ (k - 1) + 6))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.c4 (k - 2) r' (by omega) (by omega) (by omega) (by omega))
  · exact (.c22 (k - 2) r' (by omega) (by omega) (by omega))
  · omega

theorem F16_p17_2r0.bd_s24 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(8 * 3 ^ (k - 1) + 6)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F16_p17_2r0.nz_s24 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(8 * 3 ^ (k - 1) + 6)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega

theorem F16_p17_2r0.step_s25 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = -(4 * 3 ^ k + 4))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · exact (.s10 r' (by omega))
  · omega
  · omega
  · omega

theorem F16_p17_2r0.bd_s25 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(4 * 3 ^ k + 4)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F16_p17_2r0.nz_s25 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(4 * 3 ^ k + 4)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega

theorem F16_p17_2r0.step_s26 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = -(4 * 3 ^ k + 6))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.s10 r' (by omega))
  · exact (.c23 (k - 1) r' (by omega) (by omega) (by omega))
  · omega

theorem F16_p17_2r0.bd_s26 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(4 * 3 ^ k + 6)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F16_p17_2r0.nz_s26 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(4 * 3 ^ k + 6)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega

theorem F16_p17_2r0.step_s27 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = -(16 * 3 ^ (k - 1) + 6))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.c1 (k - 2) r' (by omega) (by omega) (by omega))
  · exact (.c21 (k - 2) r' (by omega) (by omega) (by omega))
  · omega

theorem F16_p17_2r0.bd_s27 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(16 * 3 ^ (k - 1) + 6)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F16_p17_2r0.nz_s27 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(16 * 3 ^ (k - 1) + 6)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega

theorem F16_p17_2r0.step_s28 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = -(20 * 3 ^ (k - 1) + 6))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.c2 (k - 2) r' (by omega) (by omega) (by omega) (by omega))
  · exact (.c23 (k - 2) r' (by omega) (by omega) (by omega))
  · omega

theorem F16_p17_2r0.bd_s28 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(20 * 3 ^ (k - 1) + 6)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F16_p17_2r0.nz_s28 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(20 * 3 ^ (k - 1) + 6)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega

theorem F16_p17_2r0.step_s29 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = -(8 * 3 ^ k + 6))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.c1 (k - 1) r' (by omega) (by omega) (by omega))
  · exact (.s30 r' (by omega))
  · omega

theorem F16_p17_2r0.bd_s29 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(8 * 3 ^ k + 6)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F16_p17_2r0.nz_s29 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(8 * 3 ^ k + 6)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega

theorem F16_p17_2r0.step_s30 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = -(8 * 3 ^ k + 8))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · omega
  · omega
  · exact (.s30 r' (by omega))

theorem F16_p17_2r0.bd_s30 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(8 * 3 ^ k + 8)) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F16_p17_2r0.nz_s30 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(8 * 3 ^ k + 8)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega

theorem F16_p17_2r0.step {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : F16_p17_2r0 k r) (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (16 * 3 ^ k + 17) * d = 3 * r' + c) : F16_p17_2r0 k r' := by
  cases hr with
  | z => exact F16_p17_2r0.step_z hk hpar rfl hd hc hv
  | c1 i r h1 h2 hr => exact F16_p17_2r0.step_c1 hk hpar h1 h2 hr hd hc hv
  | c2 i r h1 h2 h3 hr => exact F16_p17_2r0.step_c2 hk hpar h1 h2 h3 hr hd hc hv
  | c3 i r h1 h2 h3 hr => exact F16_p17_2r0.step_c3 hk hpar h1 h2 h3 hr hd hc hv
  | c4 i r h1 h2 h3 hr => exact F16_p17_2r0.step_c4 hk hpar h1 h2 h3 hr hd hc hv
  | c5 i r h1 h2 h3 hr => exact F16_p17_2r0.step_c5 hk hpar h1 h2 h3 hr hd hc hv
  | c6 i r h1 h2 hr => exact F16_p17_2r0.step_c6 hk hpar h1 h2 hr hd hc hv
  | c7 i r h1 h2 hr => exact F16_p17_2r0.step_c7 hk hpar h1 h2 hr hd hc hv
  | c8 i r h1 h2 hr => exact F16_p17_2r0.step_c8 hk hpar h1 h2 hr hd hc hv
  | s9 r hr => exact F16_p17_2r0.step_s9 hk hpar hr hd hc hv
  | s10 r hr => exact F16_p17_2r0.step_s10 hk hpar hr hd hc hv
  | s11 r hr => exact F16_p17_2r0.step_s11 hk hpar hr hd hc hv
  | s12 r hr => exact F16_p17_2r0.step_s12 hk hpar hr hd hc hv
  | s13 r hr => exact F16_p17_2r0.step_s13 hk hpar hr hd hc hv
  | s14 r hr => exact F16_p17_2r0.step_s14 hk hpar hr hd hc hv
  | s15 r hr => exact F16_p17_2r0.step_s15 hk hpar hr hd hc hv
  | c16 i r h1 h2 hr => exact F16_p17_2r0.step_c16 hk hpar h1 h2 hr hd hc hv
  | c17 i r h1 h2 h3 hr => exact F16_p17_2r0.step_c17 hk hpar h1 h2 h3 hr hd hc hv
  | c18 i r h1 h2 h3 hr => exact F16_p17_2r0.step_c18 hk hpar h1 h2 h3 hr hd hc hv
  | c19 i r h1 h2 h3 hr => exact F16_p17_2r0.step_c19 hk hpar h1 h2 h3 hr hd hc hv
  | c20 i r h1 h2 h3 hr => exact F16_p17_2r0.step_c20 hk hpar h1 h2 h3 hr hd hc hv
  | c21 i r h1 h2 hr => exact F16_p17_2r0.step_c21 hk hpar h1 h2 hr hd hc hv
  | c22 i r h1 h2 hr => exact F16_p17_2r0.step_c22 hk hpar h1 h2 hr hd hc hv
  | c23 i r h1 h2 hr => exact F16_p17_2r0.step_c23 hk hpar h1 h2 hr hd hc hv
  | s24 r hr => exact F16_p17_2r0.step_s24 hk hpar hr hd hc hv
  | s25 r hr => exact F16_p17_2r0.step_s25 hk hpar hr hd hc hv
  | s26 r hr => exact F16_p17_2r0.step_s26 hk hpar hr hd hc hv
  | s27 r hr => exact F16_p17_2r0.step_s27 hk hpar hr hd hc hv
  | s28 r hr => exact F16_p17_2r0.step_s28 hk hpar hr hd hc hv
  | s29 r hr => exact F16_p17_2r0.step_s29 hk hpar hr hd hc hv
  | s30 r hr => exact F16_p17_2r0.step_s30 hk hpar hr hd hc hv

theorem F16_p17_2r0.bound {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : F16_p17_2r0 k r) : 2 - (16 * 3 ^ k + 17) ≤ r := by
  cases hr with
  | z => have := pow3_ge k 1 3 (by decide) (by omega); omega
  | c1 i r h1 h2 hr => exact F16_p17_2r0.bd_c1 hk h1 h2 hr
  | c2 i r h1 h2 h3 hr => exact F16_p17_2r0.bd_c2 hk h1 h2 h3 hr
  | c3 i r h1 h2 h3 hr => exact F16_p17_2r0.bd_c3 hk h1 h2 h3 hr
  | c4 i r h1 h2 h3 hr => exact F16_p17_2r0.bd_c4 hk h1 h2 h3 hr
  | c5 i r h1 h2 h3 hr => exact F16_p17_2r0.bd_c5 hk h1 h2 h3 hr
  | c6 i r h1 h2 hr => exact F16_p17_2r0.bd_c6 hk h1 h2 hr
  | c7 i r h1 h2 hr => exact F16_p17_2r0.bd_c7 hk h1 h2 hr
  | c8 i r h1 h2 hr => exact F16_p17_2r0.bd_c8 hk h1 h2 hr
  | s9 r hr => exact F16_p17_2r0.bd_s9 hk hr
  | s10 r hr => exact F16_p17_2r0.bd_s10 hk hr
  | s11 r hr => exact F16_p17_2r0.bd_s11 hk hr
  | s12 r hr => exact F16_p17_2r0.bd_s12 hk hr
  | s13 r hr => exact F16_p17_2r0.bd_s13 hk hr
  | s14 r hr => exact F16_p17_2r0.bd_s14 hk hr
  | s15 r hr => exact F16_p17_2r0.bd_s15 hk hr
  | c16 i r h1 h2 hr => exact F16_p17_2r0.bd_c16 hk h1 h2 hr
  | c17 i r h1 h2 h3 hr => exact F16_p17_2r0.bd_c17 hk h1 h2 h3 hr
  | c18 i r h1 h2 h3 hr => exact F16_p17_2r0.bd_c18 hk h1 h2 h3 hr
  | c19 i r h1 h2 h3 hr => exact F16_p17_2r0.bd_c19 hk h1 h2 h3 hr
  | c20 i r h1 h2 h3 hr => exact F16_p17_2r0.bd_c20 hk h1 h2 h3 hr
  | c21 i r h1 h2 hr => exact F16_p17_2r0.bd_c21 hk h1 h2 hr
  | c22 i r h1 h2 hr => exact F16_p17_2r0.bd_c22 hk h1 h2 hr
  | c23 i r h1 h2 hr => exact F16_p17_2r0.bd_c23 hk h1 h2 hr
  | s24 r hr => exact F16_p17_2r0.bd_s24 hk hr
  | s25 r hr => exact F16_p17_2r0.bd_s25 hk hr
  | s26 r hr => exact F16_p17_2r0.bd_s26 hk hr
  | s27 r hr => exact F16_p17_2r0.bd_s27 hk hr
  | s28 r hr => exact F16_p17_2r0.bd_s28 hk hr
  | s29 r hr => exact F16_p17_2r0.bd_s29 hk hr
  | s30 r hr => exact F16_p17_2r0.bd_s30 hk hr

theorem F16_p17_2r0.nz {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : F16_p17_2r0 k r) (hpos : 0 < r) : ¬ ZF r := by
  cases hr with
  | z => omega
  | c1 i r h1 h2 hr => exact F16_p17_2r0.nz_c1 hk h1 h2 hr hpos
  | c2 i r h1 h2 h3 hr => exact F16_p17_2r0.nz_c2 hk h1 h2 h3 hr hpos
  | c3 i r h1 h2 h3 hr => exact F16_p17_2r0.nz_c3 hk h1 h2 h3 hr hpos
  | c4 i r h1 h2 h3 hr => exact F16_p17_2r0.nz_c4 hk h1 h2 h3 hr hpos
  | c5 i r h1 h2 h3 hr => exact F16_p17_2r0.nz_c5 hk h1 h2 h3 hr hpos
  | c6 i r h1 h2 hr => exact F16_p17_2r0.nz_c6 hk h1 h2 hr hpos
  | c7 i r h1 h2 hr => exact F16_p17_2r0.nz_c7 hk h1 h2 hr hpos
  | c8 i r h1 h2 hr => exact F16_p17_2r0.nz_c8 hk h1 h2 hr hpos
  | s9 r hr => exact F16_p17_2r0.nz_s9 hk hr hpos
  | s10 r hr => exact F16_p17_2r0.nz_s10 hk hr hpos
  | s11 r hr => exact F16_p17_2r0.nz_s11 hk hr hpos
  | s12 r hr => exact F16_p17_2r0.nz_s12 hk hr hpos
  | s13 r hr => exact F16_p17_2r0.nz_s13 hk hr hpos
  | s14 r hr => exact F16_p17_2r0.nz_s14 hk hr hpos
  | s15 r hr => exact F16_p17_2r0.nz_s15 hk hr hpos
  | c16 i r h1 h2 hr => exact F16_p17_2r0.nz_c16 hk h1 h2 hr hpos
  | c17 i r h1 h2 h3 hr => exact F16_p17_2r0.nz_c17 hk h1 h2 h3 hr hpos
  | c18 i r h1 h2 h3 hr => exact F16_p17_2r0.nz_c18 hk h1 h2 h3 hr hpos
  | c19 i r h1 h2 h3 hr => exact F16_p17_2r0.nz_c19 hk h1 h2 h3 hr hpos
  | c20 i r h1 h2 h3 hr => exact F16_p17_2r0.nz_c20 hk h1 h2 h3 hr hpos
  | c21 i r h1 h2 hr => exact F16_p17_2r0.nz_c21 hk h1 h2 hr hpos
  | c22 i r h1 h2 hr => exact F16_p17_2r0.nz_c22 hk h1 h2 hr hpos
  | c23 i r h1 h2 hr => exact F16_p17_2r0.nz_c23 hk h1 h2 hr hpos
  | s24 r hr => exact F16_p17_2r0.nz_s24 hk hr hpos
  | s25 r hr => exact F16_p17_2r0.nz_s25 hk hr hpos
  | s26 r hr => exact F16_p17_2r0.nz_s26 hk hr hpos
  | s27 r hr => exact F16_p17_2r0.nz_s27 hk hr hpos
  | s28 r hr => exact F16_p17_2r0.nz_s28 hk hr hpos
  | s29 r hr => exact F16_p17_2r0.nz_s29 hk hr hpos
  | s30 r hr => exact F16_p17_2r0.nz_s30 hk hr hpos

theorem F16_p17_2r0.main (k : Nat) (hk : 14 ≤ k) (hpar : k % 2 = 0) :
    ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (16 * 3 ^ k + 17) * m :=
  not_BB_of_inv _ (F16_p17_2r0 k) .z
    (fun _ _ _ _ hr hd hc hv => F16_p17_2r0.step hk hpar hr hd hc hv)
    (fun _ hr => F16_p17_2r0.bound hk hr)
    (fun _ _ _ hr hc hv hpos => F16_p17_2r0.nz hk (F16_p17_2r0.step hk hpar hr (.inl rfl) hc (by omega)) hpos)

theorem not_BB_16_p17_2r0_k6 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (16 * 3 ^ 6 + 17) * m :=
  not_BB_of_cert _ [-5840, -5838, -5836, -5832, -5828, -5824, -5816, -5804, -5792, -5768, -5732, -5696, -5624, -5516, -5408, -5192, -4868, -4866, -4864, -4544, -3894, -3244, -3136, -3028, -2956, -2944, -2932, -2924, -2922, -2920, -2916, -2912, -2908, -2884, -2848, -2812, -2596, -2272, -1952, -1950, -1948, 0, 1948, 1950, 1952, 2272, 2596, 2812, 2848, 2884, 2908, 2912, 2916, 2920, 2922, 2924, 2932, 2944, 2956, 3028, 3136, 3244, 3894, 4544, 4864, 4866, 4868, 5192, 5408, 5516, 5624, 5696, 5732, 5768, 5792, 5804, 5816, 5824, 5828, 5832, 5836, 5838, 5840] (by decide)

theorem not_BB_16_p17_2r0_k8 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (16 * 3 ^ 8 + 17) * m :=
  not_BB_of_cert _ [-52496, -52494, -52492, -52488, -52484, -52480, -52472, -52460, -52448, -52424, -52388, -52352, -52280, -52172, -52064, -51848, -51524, -51200, -50552, -49580, -48608, -46664, -43748, -43746, -43744, -40832, -34998, -29164, -28192, -27220, -26572, -26464, -26356, -26284, -26272, -26260, -26252, -26250, -26248, -26244, -26240, -26236, -26212, -26176, -26140, -25924, -25600, -25276, -23332, -20416, -17504, -17502, -17500, 0, 17500, 17502, 17504, 20416, 23332, 25276, 25600, 25924, 26140, 26176, 26212, 26236, 26240, 26244, 26248, 26250, 26252, 26260, 26272, 26284, 26356, 26464, 26572, 27220, 28192, 29164, 34998, 40832, 43744, 43746, 43748, 46664, 48608, 49580, 50552, 51200, 51524, 51848, 52064, 52172, 52280, 52352, 52388, 52424, 52448, 52460, 52472, 52480, 52484, 52488, 52492, 52494, 52496] (by decide)

theorem not_BB_16_p17_2r0_k10 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (16 * 3 ^ 10 + 17) * m :=
  not_BB_of_cert _ [-472400, -472398, -472396, -472392, -472388, -472384, -472376, -472364, -472352, -472328, -472292, -472256, -472184, -472076, -471968, -471752, -471428, -471104, -470456, -469484, -468512, -466568, -463652, -460736, -454904, -446156, -437408, -419912, -393668, -393666, -393664, -367424, -314934, -262444, -253696, -244948, -239116, -238144, -237172, -236524, -236416, -236308, -236236, -236224, -236212, -236204, -236202, -236200, -236196, -236192, -236188, -236164, -236128, -236092, -235876, -235552, -235228, -233284, -230368, -227452, -209956, -183712, -157472, -157470, -157468, 0, 157468, 157470, 157472, 183712, 209956, 227452, 230368, 233284, 235228, 235552, 235876, 236092, 236128, 236164, 236188, 236192, 236196, 236200, 236202, 236204, 236212, 236224, 236236, 236308, 236416, 236524, 237172, 238144, 239116, 244948, 253696, 262444, 314934, 367424, 393664, 393666, 393668, 419912, 437408, 446156, 454904, 460736, 463652, 466568, 468512, 469484, 470456, 471104, 471428, 471752, 471968, 472076, 472184, 472256, 472292, 472328, 472352, 472364, 472376, 472384, 472388, 472392, 472396, 472398, 472400] (by decide)

theorem not_BB_16_p17_2r0_k12 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (16 * 3 ^ 12 + 17) * m :=
  not_BB_of_cert _ [-4251536, -4251534, -4251532, -4251528, -4251524, -4251520, -4251512, -4251500, -4251488, -4251464, -4251428, -4251392, -4251320, -4251212, -4251104, -4250888, -4250564, -4250240, -4249592, -4248620, -4247648, -4245704, -4242788, -4239872, -4234040, -4225292, -4216544, -4199048, -4172804, -4146560, -4094072, -4015340, -3936608, -3779144, -3542948, -3542946, -3542944, -3306752, -2834358, -2361964, -2283232, -2204500, -2152012, -2143264, -2134516, -2128684, -2127712, -2126740, -2126092, -2125984, -2125876, -2125804, -2125792, -2125780, -2125772, -2125770, -2125768, -2125764, -2125760, -2125756, -2125732, -2125696, -2125660, -2125444, -2125120, -2124796, -2122852, -2119936, -2117020, -2099524, -2073280, -2047036, -1889572, -1653376, -1417184, -1417182, -1417180, 0, 1417180, 1417182, 1417184, 1653376, 1889572, 2047036, 2073280, 2099524, 2117020, 2119936, 2122852, 2124796, 2125120, 2125444, 2125660, 2125696, 2125732, 2125756, 2125760, 2125764, 2125768, 2125770, 2125772, 2125780, 2125792, 2125804, 2125876, 2125984, 2126092, 2126740, 2127712, 2128684, 2134516, 2143264, 2152012, 2204500, 2283232, 2361964, 2834358, 3306752, 3542944, 3542946, 3542948, 3779144, 3936608, 4015340, 4094072, 4146560, 4172804, 4199048, 4216544, 4225292, 4234040, 4239872, 4242788, 4245704, 4247648, 4248620, 4249592, 4250240, 4250564, 4250888, 4251104, 4251212, 4251320, 4251392, 4251428, 4251464, 4251488, 4251500, 4251512, 4251520, 4251524, 4251528, 4251532, 4251534, 4251536] (by decide)

/-- **Theorem.** 16·3^k + 17 ∉ B/B for every k ≥ 6 with k ≡ 0 (mod 2). -/
theorem not_BB_16_p17_2r0 (k : Nat) (hk0 : 6 ≤ k) (hkr : k % 2 = 0) :
    ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (16 * 3 ^ k + 17) * m := by
  rcases (show k = 6 ∨ k = 8 ∨ k = 10 ∨ k = 12 ∨ 14 ≤ k by omega) with rfl | rfl | rfl | rfl | hk
  · exact not_BB_16_p17_2r0_k6
  · exact not_BB_16_p17_2r0_k8
  · exact not_BB_16_p17_2r0_k10
  · exact not_BB_16_p17_2r0_k12
  · exact F16_p17_2r0.main k hk hkr

end Tern
