/-
  5·3^k + 4 is not in B/B for every k ≥ 8 with k ≡ 0 (mod 4).
  Generated by guy-f31-bt/lean_gen/gen_lean.py; every step is re-checked by Lean (omega, decide).
-/
import BalancedTernary.TernCore

namespace Tern

set_option maxHeartbeats 4000000
set_option linter.unusedVariables false
set_option maxRecDepth 100000

/-- Carry set for k ≡ 0 (mod 4). -/
inductive F5_p4_4r0 (k : Nat) : Int → Prop
  | z : F5_p4_4r0 k 0
  | c1 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) (hr : r = 1 * 3 ^ k + 1 - 2 * 3 ^ i) : F5_p4_4r0 k r
  | c2 (i : Nat) (r : Int) (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) (hr : r = 1 * 3 ^ k + 1 - (-4) * 3 ^ i) : F5_p4_4r0 k r
  | c3 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) (hr : r = 1 * 3 ^ k + 1 - 4 * 3 ^ i) : F5_p4_4r0 k r
  | c4 (i : Nat) (r : Int) (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) (hr : r = 1 * 3 ^ k + 1 - (-2) * 3 ^ i) : F5_p4_4r0 k r
  | c5 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) : F5_p4_4r0 k r
  | c6 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) : F5_p4_4r0 k r
  | c7 (i : Nat) (r : Int) (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) (hr : r = 2 * 3 ^ k + 2 - (-4) * 3 ^ i) : F5_p4_4r0 k r
  | c8 (i : Nat) (r : Int) (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) (hr : r = 2 * 3 ^ k + 2 - (-2) * 3 ^ i) : F5_p4_4r0 k r
  | s9 (r : Int) (hr : r = 1 * 3 ^ k + 1) : F5_p4_4r0 k r
  | s10 (r : Int) (hr : r = 2 * 3 ^ k + 2) : F5_p4_4r0 k r
  | c11 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) (hr : r = -(1 * 3 ^ k + 1 - 2 * 3 ^ i)) : F5_p4_4r0 k r
  | c12 (i : Nat) (r : Int) (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) (hr : r = -(1 * 3 ^ k + 1 - (-4) * 3 ^ i)) : F5_p4_4r0 k r
  | c13 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) (hr : r = -(1 * 3 ^ k + 1 - 4 * 3 ^ i)) : F5_p4_4r0 k r
  | c14 (i : Nat) (r : Int) (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) (hr : r = -(1 * 3 ^ k + 1 - (-2) * 3 ^ i)) : F5_p4_4r0 k r
  | c15 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) : F5_p4_4r0 k r
  | c16 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) : F5_p4_4r0 k r
  | c17 (i : Nat) (r : Int) (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) (hr : r = -(2 * 3 ^ k + 2 - (-4) * 3 ^ i)) : F5_p4_4r0 k r
  | c18 (i : Nat) (r : Int) (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) (hr : r = -(2 * 3 ^ k + 2 - (-2) * 3 ^ i)) : F5_p4_4r0 k r
  | s19 (r : Int) (hr : r = -(1 * 3 ^ k + 1)) : F5_p4_4r0 k r
  | s20 (r : Int) (hr : r = -(2 * 3 ^ k + 2)) : F5_p4_4r0 k r

theorem F5_p4_4r0.step_z {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    (hr : r = 0)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  subst hr
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · exact (.c4 (k - 1) r' (by omega) (by omega) (by omega) (by omega))
  · omega
  · omega
  · exact (.c14 (k - 1) r' (by omega) (by omega) (by omega) (by omega))

theorem F5_p4_4r0.step_c1 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) (hr : r = 1 * 3 ^ k + 1 - 2 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 1 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c5 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F5_p4_4r0.bd_c1 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) {r : Int} (hr : r = 1 * 3 ^ k + 1 - 2 * 3 ^ i) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 3) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c1 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) {r : Int} (hr : r = 1 * 3 ^ k + 1 - 2 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 3) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 1 ∨ 4 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (1 * 3 ^ (k - 1) + (-2)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (1 * 3 ^ (k - 2) + (-1)) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (1 * 3 ^ (k - 3) + 0) (-1) h2 (by omega) (.inr rfl) (by omega)
    exact h3.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := pow3_pos (i - 2)
    have := pow3_le_mul (i - 0) (k - 0) 3 27 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 3 27 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 3 27 (by decide) (by omega)
    have h1 := ZF.down (1 * 3 ^ (k - 1) + 0 - 2 * 3 ^ (i - 1)) 1 h0 (by omega) (.inl rfl) (by omega)
    exact h1.mod3 (by omega)

theorem F5_p4_4r0.step_c2 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) (hr : r = 1 * 3 ^ k + 1 - (-4) * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 3 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c7 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F5_p4_4r0.bd_c2 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) {r : Int} (hr : r = 1 * 3 ^ k + 1 - (-4) * 3 ^ i) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c2 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) {r : Int} (hr : r = 1 * 3 ^ k + 1 - (-4) * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 3 ∨ 4 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (1 * 3 ^ (k - 1) + 36) 1 h0 (by omega) (.inl rfl) (by omega)
    exact h1.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := pow3_pos (i - 2)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 3 27 (by decide) (by omega)
    have h1 := ZF.down (1 * 3 ^ (k - 1) + 0 - (-4) * 3 ^ (i - 1)) 1 h0 (by omega) (.inl rfl) (by omega)
    exact h1.mod3 (by omega)

theorem F5_p4_4r0.step_c3 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) (hr : r = 1 * 3 ^ k + 1 - 4 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 1 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c6 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F5_p4_4r0.bd_c3 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) {r : Int} (hr : r = 1 * 3 ^ k + 1 - 4 * 3 ^ i) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 3) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c3 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) {r : Int} (hr : r = 1 * 3 ^ k + 1 - 4 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 3) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 1 ∨ 4 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (1 * 3 ^ (k - 1) + (-4)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (1 * 3 ^ (k - 2) + (-1)) (-1) h1 (by omega) (.inr rfl) (by omega)
    have h3 := ZF.down (1 * 3 ^ (k - 3) + 0) (-1) h2 (by omega) (.inr rfl) (by omega)
    exact h3.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := pow3_pos (i - 2)
    have := pow3_le_mul (i - 0) (k - 0) 3 27 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 3 27 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 3 27 (by decide) (by omega)
    have h1 := ZF.down (1 * 3 ^ (k - 1) + 0 - 4 * 3 ^ (i - 1)) 1 h0 (by omega) (.inl rfl) (by omega)
    exact h1.mod3 (by omega)

theorem F5_p4_4r0.step_c4 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) (hr : r = 1 * 3 ^ k + 1 - (-2) * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 3 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c8 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F5_p4_4r0.bd_c4 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) {r : Int} (hr : r = 1 * 3 ^ k + 1 - (-2) * 3 ^ i) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c4 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) {r : Int} (hr : r = 1 * 3 ^ k + 1 - (-2) * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 3 ∨ 4 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (1 * 3 ^ (k - 1) + 18) 1 h0 (by omega) (.inl rfl) (by omega)
    exact h1.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := pow3_pos (i - 2)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 3 27 (by decide) (by omega)
    have h1 := ZF.down (1 * 3 ^ (k - 1) + 0 - (-2) * 3 ^ (i - 1)) 1 h0 (by omega) (.inl rfl) (by omega)
    exact h1.mod3 (by omega)

theorem F5_p4_4r0.step_c5 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 4 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c2 (k - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega
    · exact (.s19 r' (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c14 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega

theorem F5_p4_4r0.bd_c5 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 4) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c5 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 4) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    exact h0.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-53)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-18)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 4 81 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - 2 * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - 2 * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F5_p4_4r0.step_c6 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 4 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c2 (k - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c12 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega

theorem F5_p4_4r0.bd_c6 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 4) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c6 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 4) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-1)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0) (-1) h1 (by omega) (.inr rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-107)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-36)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 4 81 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - 4 * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - 4 * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F5_p4_4r0.step_c7 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) (hr : r = 2 * 3 ^ k + 2 - (-4) * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 2 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c13 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega

theorem F5_p4_4r0.bd_c7 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) {r : Int} (hr : r = 2 * 3 ^ k + 2 - (-4) * 3 ^ i) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c7 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) {r : Int} (hr : r = 2 * 3 ^ k + 2 - (-4) * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 2 ∨ 5 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 13) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 4) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (2 * 3 ^ (k - 3) + 1) 1 h2 (by omega) (.inl rfl) (by omega)
    have h4 := ZF.down (2 * 3 ^ (k - 4) + 0) 1 h3 (by omega) (.inl rfl) (by omega)
    exact h4.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 2 9 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 2 9 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 2 9 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - (-4) * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - (-4) * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F5_p4_4r0.step_c8 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) (hr : r = 2 * 3 ^ k + 2 - (-2) * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 2 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c11 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega

theorem F5_p4_4r0.bd_c8 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) {r : Int} (hr : r = 2 * 3 ^ k + 2 - (-2) * 3 ^ i) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c8 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) {r : Int} (hr : r = 2 * 3 ^ k + 2 - (-2) * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 2 ∨ 5 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 7) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 2) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (2 * 3 ^ (k - 3) + 1) (-1) h2 (by omega) (.inr rfl) (by omega)
    have h4 := ZF.down (2 * 3 ^ (k - 4) + 0) 1 h3 (by omega) (.inl rfl) (by omega)
    exact h4.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 2 9 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 2 9 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 2 9 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - (-2) * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - (-2) * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F5_p4_4r0.step_s9 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    (hr : r = 1 * 3 ^ k + 1)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.s10 r' (by omega))
  · omega
  · omega

theorem F5_p4_4r0.bd_s9 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 1 * 3 ^ k + 1) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F5_p4_4r0.nz_s9 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 1 * 3 ^ k + 1) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  intro h0
  subst hr
  have h1 := ZF.down (1 * 3 ^ (k - 1) + 0) 1 h0 (by omega) (.inl rfl) (by omega)
  exact h1.mod3 (by omega)

theorem F5_p4_4r0.step_s10 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    (hr : r = 2 * 3 ^ k + 2)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · omega
  · exact (.s19 r' (by omega))
  · omega

theorem F5_p4_4r0.bd_s10 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F5_p4_4r0.nz_s10 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  intro h0
  subst hr
  have h1 := ZF.down (2 * 3 ^ (k - 1) + 1) (-1) h0 (by omega) (.inr rfl) (by omega)
  have h2 := ZF.down (2 * 3 ^ (k - 2) + 0) 1 h1 (by omega) (.inl rfl) (by omega)
  exact h2.mod3 (by omega)

theorem F5_p4_4r0.step_c11 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) (hr : r = -(1 * 3 ^ k + 1 - 2 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 1 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c15 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega

theorem F5_p4_4r0.bd_c11 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) {r : Int} (hr : r = -(1 * 3 ^ k + 1 - 2 * 3 ^ i)) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 3) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c11 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) {r : Int} (hr : r = -(1 * 3 ^ k + 1 - 2 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 3) (by omega)
  have := pow3_pos i
  omega

theorem F5_p4_4r0.step_c12 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) (hr : r = -(1 * 3 ^ k + 1 - (-4) * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 3 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c17 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega

theorem F5_p4_4r0.bd_c12 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) {r : Int} (hr : r = -(1 * 3 ^ k + 1 - (-4) * 3 ^ i)) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c12 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) {r : Int} (hr : r = -(1 * 3 ^ k + 1 - (-4) * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F5_p4_4r0.step_c13 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) (hr : r = -(1 * 3 ^ k + 1 - 4 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 1 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c16 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega

theorem F5_p4_4r0.bd_c13 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) {r : Int} (hr : r = -(1 * 3 ^ k + 1 - 4 * 3 ^ i)) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 3) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c13 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 3 ≤ k) (h3 : i % 4 = 1) {r : Int} (hr : r = -(1 * 3 ^ k + 1 - 4 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 3) (by omega)
  have := pow3_pos i
  omega

theorem F5_p4_4r0.step_c14 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) (hr : r = -(1 * 3 ^ k + 1 - (-2) * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 3 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c18 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega

theorem F5_p4_4r0.bd_c14 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) {r : Int} (hr : r = -(1 * 3 ^ k + 1 - (-2) * 3 ^ i)) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c14 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 3 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 4 = 3) {r : Int} (hr : r = -(1 * 3 ^ k + 1 - (-2) * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F5_p4_4r0.step_c15 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 4 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.s9 r' (by omega))
    · omega
    · omega
    · exact (.c12 (k - 1) r' (by omega) (by omega) (by omega) (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c4 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F5_p4_4r0.bd_c15 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 4) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c15 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 4) (by omega)
  have := pow3_pos i
  omega

theorem F5_p4_4r0.step_c16 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 4 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c12 (k - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c2 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F5_p4_4r0.bd_c16 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 4) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c16 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 4 ≤ k) (h3 : i % 4 = 0) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 4) (by omega)
  have := pow3_pos i
  omega

theorem F5_p4_4r0.step_c17 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) (hr : r = -(2 * 3 ^ k + 2 - (-4) * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 2 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c3 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F5_p4_4r0.bd_c17 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - (-4) * 3 ^ i)) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c17 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - (-4) * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega

theorem F5_p4_4r0.step_c18 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) (hr : r = -(2 * 3 ^ k + 2 - (-2) * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 2 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c1 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F5_p4_4r0.bd_c18 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - (-2) * 3 ^ i)) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega
theorem F5_p4_4r0.nz_c18 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 2 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 4 = 2) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - (-2) * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega

theorem F5_p4_4r0.step_s19 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    (hr : r = -(1 * 3 ^ k + 1))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · omega
  · exact (.s20 r' (by omega))
  · omega

theorem F5_p4_4r0.bd_s19 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(1 * 3 ^ k + 1)) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F5_p4_4r0.nz_s19 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(1 * 3 ^ k + 1)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega

theorem F5_p4_4r0.step_s20 {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    (hr : r = -(2 * 3 ^ k + 2))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.s9 r' (by omega))
  · omega
  · omega

theorem F5_p4_4r0.bd_s20 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2)) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F5_p4_4r0.nz_s20 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega

theorem F5_p4_4r0.step {k : Nat} (hk : 14 ≤ k) (hpar : k % 4 = 0) {r r' d c : Int}
    (hr : F5_p4_4r0 k r) (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (5 * 3 ^ k + 4) * d = 3 * r' + c) : F5_p4_4r0 k r' := by
  cases hr with
  | z => exact F5_p4_4r0.step_z hk hpar rfl hd hc hv
  | c1 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c1 hk hpar h1 h2 h3 hr hd hc hv
  | c2 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c2 hk hpar h1 h2 h3 hr hd hc hv
  | c3 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c3 hk hpar h1 h2 h3 hr hd hc hv
  | c4 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c4 hk hpar h1 h2 h3 hr hd hc hv
  | c5 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c5 hk hpar h1 h2 h3 hr hd hc hv
  | c6 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c6 hk hpar h1 h2 h3 hr hd hc hv
  | c7 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c7 hk hpar h1 h2 h3 hr hd hc hv
  | c8 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c8 hk hpar h1 h2 h3 hr hd hc hv
  | s9 r hr => exact F5_p4_4r0.step_s9 hk hpar hr hd hc hv
  | s10 r hr => exact F5_p4_4r0.step_s10 hk hpar hr hd hc hv
  | c11 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c11 hk hpar h1 h2 h3 hr hd hc hv
  | c12 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c12 hk hpar h1 h2 h3 hr hd hc hv
  | c13 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c13 hk hpar h1 h2 h3 hr hd hc hv
  | c14 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c14 hk hpar h1 h2 h3 hr hd hc hv
  | c15 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c15 hk hpar h1 h2 h3 hr hd hc hv
  | c16 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c16 hk hpar h1 h2 h3 hr hd hc hv
  | c17 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c17 hk hpar h1 h2 h3 hr hd hc hv
  | c18 i r h1 h2 h3 hr => exact F5_p4_4r0.step_c18 hk hpar h1 h2 h3 hr hd hc hv
  | s19 r hr => exact F5_p4_4r0.step_s19 hk hpar hr hd hc hv
  | s20 r hr => exact F5_p4_4r0.step_s20 hk hpar hr hd hc hv

theorem F5_p4_4r0.bound {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : F5_p4_4r0 k r) : 2 - (5 * 3 ^ k + 4) ≤ r := by
  cases hr with
  | z => have := pow3_ge k 1 3 (by decide) (by omega); omega
  | c1 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c1 hk h1 h2 h3 hr
  | c2 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c2 hk h1 h2 h3 hr
  | c3 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c3 hk h1 h2 h3 hr
  | c4 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c4 hk h1 h2 h3 hr
  | c5 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c5 hk h1 h2 h3 hr
  | c6 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c6 hk h1 h2 h3 hr
  | c7 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c7 hk h1 h2 h3 hr
  | c8 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c8 hk h1 h2 h3 hr
  | s9 r hr => exact F5_p4_4r0.bd_s9 hk hr
  | s10 r hr => exact F5_p4_4r0.bd_s10 hk hr
  | c11 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c11 hk h1 h2 h3 hr
  | c12 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c12 hk h1 h2 h3 hr
  | c13 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c13 hk h1 h2 h3 hr
  | c14 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c14 hk h1 h2 h3 hr
  | c15 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c15 hk h1 h2 h3 hr
  | c16 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c16 hk h1 h2 h3 hr
  | c17 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c17 hk h1 h2 h3 hr
  | c18 i r h1 h2 h3 hr => exact F5_p4_4r0.bd_c18 hk h1 h2 h3 hr
  | s19 r hr => exact F5_p4_4r0.bd_s19 hk hr
  | s20 r hr => exact F5_p4_4r0.bd_s20 hk hr

theorem F5_p4_4r0.nz {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : F5_p4_4r0 k r) (hpos : 0 < r) : ¬ ZF r := by
  cases hr with
  | z => omega
  | c1 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c1 hk h1 h2 h3 hr hpos
  | c2 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c2 hk h1 h2 h3 hr hpos
  | c3 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c3 hk h1 h2 h3 hr hpos
  | c4 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c4 hk h1 h2 h3 hr hpos
  | c5 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c5 hk h1 h2 h3 hr hpos
  | c6 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c6 hk h1 h2 h3 hr hpos
  | c7 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c7 hk h1 h2 h3 hr hpos
  | c8 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c8 hk h1 h2 h3 hr hpos
  | s9 r hr => exact F5_p4_4r0.nz_s9 hk hr hpos
  | s10 r hr => exact F5_p4_4r0.nz_s10 hk hr hpos
  | c11 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c11 hk h1 h2 h3 hr hpos
  | c12 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c12 hk h1 h2 h3 hr hpos
  | c13 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c13 hk h1 h2 h3 hr hpos
  | c14 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c14 hk h1 h2 h3 hr hpos
  | c15 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c15 hk h1 h2 h3 hr hpos
  | c16 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c16 hk h1 h2 h3 hr hpos
  | c17 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c17 hk h1 h2 h3 hr hpos
  | c18 i r h1 h2 h3 hr => exact F5_p4_4r0.nz_c18 hk h1 h2 h3 hr hpos
  | s19 r hr => exact F5_p4_4r0.nz_s19 hk hr hpos
  | s20 r hr => exact F5_p4_4r0.nz_s20 hk hr hpos

theorem F5_p4_4r0.main (k : Nat) (hk : 14 ≤ k) (hpar : k % 4 = 0) :
    ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (5 * 3 ^ k + 4) * m :=
  not_BB_of_inv _ (F5_p4_4r0 k) .z
    (fun _ _ _ _ hr hd hc hv => F5_p4_4r0.step hk hpar hr hd hc hv)
    (fun _ hr => F5_p4_4r0.bound hk hr)
    (fun _ _ _ hr hc hv hpos => F5_p4_4r0.nz hk (F5_p4_4r0.step hk hpar hr (.inl rfl) hc (by omega)) hpos)

theorem not_BB_5_p4_4r0_k8 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (5 * 3 ^ 8 + 4) * m :=
  not_BB_of_cert _ [-16040, -15310, -14582, -13160, -13142, -13124, -13122, -13120, -12962, -12800, -10936, -6670, -6616, -6562, -6556, -6550, -6076, -5590, 0, 5590, 6076, 6550, 6556, 6562, 6616, 6670, 10936, 12800, 12962, 13120, 13122, 13124, 13142, 13160, 14582, 15310, 16040] (by decide)

theorem not_BB_5_p4_4r0_k12 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (5 * 3 ^ 12 + 4) * m :=
  not_BB_of_cert _ [-1299080, -1240030, -1180982, -1065800, -1064342, -1062920, -1062902, -1062884, -1062882, -1062880, -1062722, -1062560, -1049762, -1036640, -885736, -540190, -535816, -531550, -531496, -531442, -531436, -531430, -530956, -530470, -492076, -452710, 0, 452710, 492076, 530470, 530956, 531430, 531436, 531442, 531496, 531550, 535816, 540190, 885736, 1036640, 1049762, 1062560, 1062722, 1062880, 1062882, 1062884, 1062902, 1062920, 1064342, 1065800, 1180982, 1240030, 1299080] (by decide)

/-- **Theorem.** 5·3^k + 4 ∉ B/B for every k ≥ 8 with k ≡ 0 (mod 4). -/
theorem not_BB_5_p4_4r0 (k : Nat) (hk0 : 8 ≤ k) (hkr : k % 4 = 0) :
    ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (5 * 3 ^ k + 4) * m := by
  rcases (show k = 8 ∨ k = 12 ∨ 14 ≤ k by omega) with rfl | rfl | hk
  · exact not_BB_5_p4_4r0_k8
  · exact not_BB_5_p4_4r0_k12
  · exact F5_p4_4r0.main k hk hkr

end Tern
