/-
  8·3^k + 7 is not in B/B for every k ≥ 5.
  Generated by guy-f31-bt/lean_gen/gen_lean.py; every step is re-checked by Lean (omega, decide).
-/
import BalancedTernary.TernCore

namespace Tern

set_option maxHeartbeats 4000000
set_option linter.unusedVariables false

/-- Carry set for k ≡ 0 (mod 2). -/
inductive F8_p7_e (k : Nat) : Int → Prop
  | z : F8_p7_e k 0
  | c1 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) : F8_p7_e k r
  | c2 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) : F8_p7_e k r
  | c3 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) (hr : r = 2 * 3 ^ k + 2 - (-4) * 3 ^ i) : F8_p7_e k r
  | c4 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) (hr : r = 2 * 3 ^ k + 2 - (-2) * 3 ^ i) : F8_p7_e k r
  | s5 (r : Int) (hr : r = 2 * 3 ^ k + 2) : F8_p7_e k r
  | c6 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) : F8_p7_e k r
  | c7 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) : F8_p7_e k r
  | c8 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) (hr : r = -(2 * 3 ^ k + 2 - (-4) * 3 ^ i)) : F8_p7_e k r
  | c9 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) (hr : r = -(2 * 3 ^ k + 2 - (-2) * 3 ^ i)) : F8_p7_e k r
  | s10 (r : Int) (hr : r = -(2 * 3 ^ k + 2)) : F8_p7_e k r

theorem F8_p7_e.step_z {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = 0)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  subst hr
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · exact (.c4 (k - 1) r' (by omega) (by omega) (by omega) (by omega))
  · omega
  · omega
  · exact (.c9 (k - 1) r' (by omega) (by omega) (by omega) (by omega))

theorem F8_p7_e.step_c1 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 2 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c3 (k - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega
    · exact (.s10 r' (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c9 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega

theorem F8_p7_e.bd_c1 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_e.nz_c1 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 2 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    exact h0.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-5)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-2)) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (2 * 3 ^ (k - 3) + (-1)) 1 h2 (by omega) (.inl rfl) (by omega)
    have h4 := ZF.down (2 * 3 ^ (k - 4) + 0) (-1) h3 (by omega) (.inr rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-53)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-18)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 2 9 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 2 9 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 2 9 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - 2 * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - 2 * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F8_p7_e.step_c2 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 2 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c3 (k - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c8 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega

theorem F8_p7_e.bd_c2 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_e.nz_c2 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 2 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-1)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0) (-1) h1 (by omega) (.inr rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-11)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-4)) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (2 * 3 ^ (k - 3) + (-1)) (-1) h2 (by omega) (.inr rfl) (by omega)
    have h4 := ZF.down (2 * 3 ^ (k - 4) + 0) (-1) h3 (by omega) (.inr rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-107)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-36)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 2 9 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 2 9 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 2 9 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - 4 * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - 4 * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F8_p7_e.step_c3 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) (hr : r = 2 * 3 ^ k + 2 - (-4) * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 1 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c7 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega

theorem F8_p7_e.bd_c3 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = 2 * 3 ^ k + 2 - (-4) * 3 ^ i) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_e.nz_c3 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = 2 * 3 ^ k + 2 - (-4) * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 1 ∨ i = 3 ∨ 5 ≤ i by omega) with rfl | rfl | hi
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 5) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 2) (-1) h1 (by omega) (.inr rfl) (by omega)
    have h3 := ZF.down (2 * 3 ^ (k - 3) + 1) (-1) h2 (by omega) (.inr rfl) (by omega)
    have h4 := ZF.down (2 * 3 ^ (k - 4) + 0) 1 h3 (by omega) (.inl rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 37) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 12) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - (-4) * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - (-4) * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F8_p7_e.step_c4 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) (hr : r = 2 * 3 ^ k + 2 - (-2) * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 1 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c6 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega

theorem F8_p7_e.bd_c4 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = 2 * 3 ^ k + 2 - (-2) * 3 ^ i) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_e.nz_c4 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = 2 * 3 ^ k + 2 - (-2) * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 1 ∨ i = 3 ∨ 5 ≤ i by omega) with rfl | rfl | hi
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 3) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 19) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 6) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - (-2) * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - (-2) * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F8_p7_e.step_s5 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = 2 * 3 ^ k + 2)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · omega
  · exact (.s10 r' (by omega))
  · omega

theorem F8_p7_e.bd_s5 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F8_p7_e.nz_s5 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  intro h0
  subst hr
  have h1 := ZF.down (2 * 3 ^ (k - 1) + 1) (-1) h0 (by omega) (.inr rfl) (by omega)
  have h2 := ZF.down (2 * 3 ^ (k - 2) + 0) 1 h1 (by omega) (.inl rfl) (by omega)
  exact h2.mod3 (by omega)

theorem F8_p7_e.step_c6 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 2 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.s5 r' (by omega))
    · omega
    · omega
    · exact (.c8 (k - 1) r' (by omega) (by omega) (by omega) (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c4 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F8_p7_e.bd_c6 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_e.nz_c6 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega

theorem F8_p7_e.step_c7 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 2 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c8 (k - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c3 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F8_p7_e.bd_c7 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_e.nz_c7 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega

theorem F8_p7_e.step_c8 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) (hr : r = -(2 * 3 ^ k + 2 - (-4) * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 1 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c2 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F8_p7_e.bd_c8 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - (-4) * 3 ^ i)) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_e.nz_c8 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - (-4) * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F8_p7_e.step_c9 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) (hr : r = -(2 * 3 ^ k + 2 - (-2) * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 1 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c1 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F8_p7_e.bd_c9 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - (-2) * 3 ^ i)) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_e.nz_c9 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - (-2) * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F8_p7_e.step_s10 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = -(2 * 3 ^ k + 2))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.s5 r' (by omega))
  · omega
  · omega

theorem F8_p7_e.bd_s10 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2)) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F8_p7_e.nz_s10 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega

theorem F8_p7_e.step {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : F8_p7_e k r) (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_e k r' := by
  cases hr with
  | z => exact F8_p7_e.step_z hk hpar rfl hd hc hv
  | c1 i r h1 h2 h3 hr => exact F8_p7_e.step_c1 hk hpar h1 h2 h3 hr hd hc hv
  | c2 i r h1 h2 h3 hr => exact F8_p7_e.step_c2 hk hpar h1 h2 h3 hr hd hc hv
  | c3 i r h1 h2 h3 hr => exact F8_p7_e.step_c3 hk hpar h1 h2 h3 hr hd hc hv
  | c4 i r h1 h2 h3 hr => exact F8_p7_e.step_c4 hk hpar h1 h2 h3 hr hd hc hv
  | s5 r hr => exact F8_p7_e.step_s5 hk hpar hr hd hc hv
  | c6 i r h1 h2 h3 hr => exact F8_p7_e.step_c6 hk hpar h1 h2 h3 hr hd hc hv
  | c7 i r h1 h2 h3 hr => exact F8_p7_e.step_c7 hk hpar h1 h2 h3 hr hd hc hv
  | c8 i r h1 h2 h3 hr => exact F8_p7_e.step_c8 hk hpar h1 h2 h3 hr hd hc hv
  | c9 i r h1 h2 h3 hr => exact F8_p7_e.step_c9 hk hpar h1 h2 h3 hr hd hc hv
  | s10 r hr => exact F8_p7_e.step_s10 hk hpar hr hd hc hv

theorem F8_p7_e.bound {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : F8_p7_e k r) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  cases hr with
  | z => have := pow3_ge k 1 3 (by decide) (by omega); omega
  | c1 i r h1 h2 h3 hr => exact F8_p7_e.bd_c1 hk h1 h2 h3 hr
  | c2 i r h1 h2 h3 hr => exact F8_p7_e.bd_c2 hk h1 h2 h3 hr
  | c3 i r h1 h2 h3 hr => exact F8_p7_e.bd_c3 hk h1 h2 h3 hr
  | c4 i r h1 h2 h3 hr => exact F8_p7_e.bd_c4 hk h1 h2 h3 hr
  | s5 r hr => exact F8_p7_e.bd_s5 hk hr
  | c6 i r h1 h2 h3 hr => exact F8_p7_e.bd_c6 hk h1 h2 h3 hr
  | c7 i r h1 h2 h3 hr => exact F8_p7_e.bd_c7 hk h1 h2 h3 hr
  | c8 i r h1 h2 h3 hr => exact F8_p7_e.bd_c8 hk h1 h2 h3 hr
  | c9 i r h1 h2 h3 hr => exact F8_p7_e.bd_c9 hk h1 h2 h3 hr
  | s10 r hr => exact F8_p7_e.bd_s10 hk hr

theorem F8_p7_e.nz {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : F8_p7_e k r) (hpos : 0 < r) : ¬ ZF r := by
  cases hr with
  | z => omega
  | c1 i r h1 h2 h3 hr => exact F8_p7_e.nz_c1 hk h1 h2 h3 hr hpos
  | c2 i r h1 h2 h3 hr => exact F8_p7_e.nz_c2 hk h1 h2 h3 hr hpos
  | c3 i r h1 h2 h3 hr => exact F8_p7_e.nz_c3 hk h1 h2 h3 hr hpos
  | c4 i r h1 h2 h3 hr => exact F8_p7_e.nz_c4 hk h1 h2 h3 hr hpos
  | s5 r hr => exact F8_p7_e.nz_s5 hk hr hpos
  | c6 i r h1 h2 h3 hr => exact F8_p7_e.nz_c6 hk h1 h2 h3 hr hpos
  | c7 i r h1 h2 h3 hr => exact F8_p7_e.nz_c7 hk h1 h2 h3 hr hpos
  | c8 i r h1 h2 h3 hr => exact F8_p7_e.nz_c8 hk h1 h2 h3 hr hpos
  | c9 i r h1 h2 h3 hr => exact F8_p7_e.nz_c9 hk h1 h2 h3 hr hpos
  | s10 r hr => exact F8_p7_e.nz_s10 hk hr hpos

theorem F8_p7_e.main (k : Nat) (hk : 14 ≤ k) (hpar : k % 2 = 0) :
    ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (8 * 3 ^ k + 7) * m :=
  not_BB_of_inv _ (F8_p7_e k) .z
    (fun _ _ _ _ hr hd hc hv => F8_p7_e.step hk hpar hr hd hc hv)
    (fun _ hr => F8_p7_e.bound hk hr)
    (fun _ _ _ hr hc hv hpos => F8_p7_e.nz hk (F8_p7_e.step hk hpar hr (.inl rfl) hc (by omega)) hpos)

/-- Carry set for k ≡ 1 (mod 2). -/
inductive F8_p7_o (k : Nat) : Int → Prop
  | z : F8_p7_o k 0
  | c1 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) : F8_p7_o k r
  | c2 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 0) (hr : r = 2 * 3 ^ k + 2 - (-4) * 3 ^ i) : F8_p7_o k r
  | c3 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 1) (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) : F8_p7_o k r
  | c4 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) (hr : r = 2 * 3 ^ k + 2 - (-2) * 3 ^ i) : F8_p7_o k r
  | c5 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 4 * 3 ^ k + 4 - 2 * 3 ^ i) : F8_p7_o k r
  | s6 (r : Int) (hr : r = 2 * 3 ^ k + 2) : F8_p7_o k r
  | c7 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) : F8_p7_o k r
  | c8 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 0) (hr : r = -(2 * 3 ^ k + 2 - (-4) * 3 ^ i)) : F8_p7_o k r
  | c9 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 1) (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) : F8_p7_o k r
  | c10 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) (hr : r = -(2 * 3 ^ k + 2 - (-2) * 3 ^ i)) : F8_p7_o k r
  | c11 (i : Nat) (r : Int) (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(4 * 3 ^ k + 4 - 2 * 3 ^ i)) : F8_p7_o k r
  | s12 (r : Int) (hr : r = -(2 * 3 ^ k + 2)) : F8_p7_o k r

theorem F8_p7_o.step_z {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    (hr : r = 0)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  subst hr
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · exact (.c4 (k - 1) r' (by omega) (by omega) (by omega))
  · omega
  · omega
  · exact (.c10 (k - 1) r' (by omega) (by omega) (by omega))

theorem F8_p7_o.step_c1 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c2 (k - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega
    · exact (.s12 r' (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c10 (i - 1) r' (by omega) (by omega) (by omega))
    · omega

theorem F8_p7_o.bd_c1 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_o.nz_c1 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    exact h0.mod3 (by omega)
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0) (-1) h1 (by omega) (.inr rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-5)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-2)) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (2 * 3 ^ (k - 3) + (-1)) 1 h2 (by omega) (.inl rfl) (by omega)
    have h4 := ZF.down (2 * 3 ^ (k - 4) + 0) (-1) h3 (by omega) (.inr rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-17)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-6)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-53)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-18)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - 2 * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - 2 * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F8_p7_o.step_c2 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 0) (hr : r = 2 * 3 ^ k + 2 - (-4) * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 2 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c5 (k - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · exact (.c7 0 r' (by omega) (by omega) (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c9 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega

theorem F8_p7_o.bd_c2 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = 2 * 3 ^ k + 2 - (-4) * 3 ^ i) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_o.nz_c2 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = 2 * 3 ^ k + 2 - (-4) * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 2 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    exact h0.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 13) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 4) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (2 * 3 ^ (k - 3) + 1) 1 h2 (by omega) (.inl rfl) (by omega)
    have h4 := ZF.down (2 * 3 ^ (k - 4) + 0) 1 h3 (by omega) (.inl rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 109) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 36) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - (-4) * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - (-4) * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F8_p7_o.step_c3 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 1) (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 1 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c8 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega

theorem F8_p7_o.bd_c3 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_o.nz_c3 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 1 ∨ i = 3 ∨ 5 ≤ i by omega) with rfl | rfl | hi
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-3)) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-35)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-12)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 2 9 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 2 9 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 2 9 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - 4 * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - 4 * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F8_p7_o.step_c4 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) (hr : r = 2 * 3 ^ k + 2 - (-2) * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c5 (k - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c7 (i - 1) r' (by omega) (by omega) (by omega))
    · omega

theorem F8_p7_o.bd_c4 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2 - (-2) * 3 ^ i) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i k (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_o.nz_c4 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2 - (-2) * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i k (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 3) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 7) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 2) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (2 * 3 ^ (k - 3) + 1) (-1) h2 (by omega) (.inr rfl) (by omega)
    have h4 := ZF.down (2 * 3 ^ (k - 4) + 0) 1 h3 (by omega) (.inl rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 19) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 6) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 55) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 18) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 0 1 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 0 1 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 0 1 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - (-2) * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - (-2) * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F8_p7_o.step_c5 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 4 * 3 ^ k + 4 - 2 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 1 ∨ 2 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 1 = 3 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c4 k r' (by omega) (by omega) (by omega))
    · omega
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c5 (i - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F8_p7_o.bd_c5 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 4 * 3 ^ k + 4 - 2 * 3 ^ i) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_o.nz_c5 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 4 * 3 ^ k + 4 - 2 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + (-1)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + 0) (-1) h1 (by omega) (.inr rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + (-5)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + (-2)) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (4 * 3 ^ (k - 3) + (-1)) 1 h2 (by omega) (.inl rfl) (by omega)
    have h4 := ZF.down (4 * 3 ^ (k - 4) + 0) (-1) h3 (by omega) (.inr rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + (-17)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + (-6)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (4 * 3 ^ (k - 1) + (-53)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + (-18)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (4 * 3 ^ (k - 1) + 1 - 2 * 3 ^ (i - 1)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (4 * 3 ^ (k - 2) + 0 - 2 * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F8_p7_o.step_s6 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    (hr : r = 2 * 3 ^ k + 2)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · omega
  · exact (.s12 r' (by omega))
  · omega

theorem F8_p7_o.bd_s6 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F8_p7_o.nz_s6 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  intro h0
  subst hr
  have h1 := ZF.down (2 * 3 ^ (k - 1) + 1) (-1) h0 (by omega) (.inr rfl) (by omega)
  have h2 := ZF.down (2 * 3 ^ (k - 2) + 0) 1 h1 (by omega) (.inl rfl) (by omega)
  exact h2.mod3 (by omega)

theorem F8_p7_o.step_c7 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.s6 r' (by omega))
    · omega
    · omega
    · exact (.c8 (k - 1) r' (by omega) (by omega) (by omega) (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c4 (i - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F8_p7_o.bd_c7 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_o.nz_c7 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F8_p7_o.step_c8 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 0) (hr : r = -(2 * 3 ^ k + 2 - (-4) * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 2 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c1 0 r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · exact (.c11 (k - 1) r' (by omega) (by omega) (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c3 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F8_p7_o.bd_c8 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - (-4) * 3 ^ i)) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_o.nz_c8 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (h3 : i % 2 = 0) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - (-4) * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F8_p7_o.step_c9 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 1) (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show 1 ≤ i by omega) with hi
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c2 (i - 1) r' (by omega) (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F8_p7_o.bd_c9 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_o.nz_c9 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 2 ≤ k) (h3 : i % 2 = 1) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 2) (by omega)
  have := pow3_pos i
  omega

theorem F8_p7_o.step_c10 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) (hr : r = -(2 * 3 ^ k + 2 - (-2) * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c11 (k - 1) r' (by omega) (by omega) (by omega))
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c1 (i - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega

theorem F8_p7_o.bd_c10 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - (-2) * 3 ^ i)) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i k (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_o.nz_c10 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 0 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - (-2) * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i k (by omega)
  have := pow3_pos i
  omega

theorem F8_p7_o.step_c11 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(4 * 3 ^ k + 4 - 2 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 1 ∨ 2 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 1 = 3 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c10 k r' (by omega) (by omega) (by omega))
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · exact (.c11 (i - 1) r' (by omega) (by omega) (by omega))
    · omega

theorem F8_p7_o.bd_c11 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(4 * 3 ^ k + 4 - 2 * 3 ^ i)) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F8_p7_o.nz_c11 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 1 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(4 * 3 ^ k + 4 - 2 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F8_p7_o.step_s12 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    (hr : r = -(2 * 3 ^ k + 2))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.s6 r' (by omega))
  · omega
  · omega

theorem F8_p7_o.bd_s12 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2)) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F8_p7_o.nz_s12 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega

theorem F8_p7_o.step {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    (hr : F8_p7_o k r) (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (8 * 3 ^ k + 7) * d = 3 * r' + c) : F8_p7_o k r' := by
  cases hr with
  | z => exact F8_p7_o.step_z hk hpar rfl hd hc hv
  | c1 i r h1 h2 hr => exact F8_p7_o.step_c1 hk hpar h1 h2 hr hd hc hv
  | c2 i r h1 h2 h3 hr => exact F8_p7_o.step_c2 hk hpar h1 h2 h3 hr hd hc hv
  | c3 i r h1 h2 h3 hr => exact F8_p7_o.step_c3 hk hpar h1 h2 h3 hr hd hc hv
  | c4 i r h1 h2 hr => exact F8_p7_o.step_c4 hk hpar h1 h2 hr hd hc hv
  | c5 i r h1 h2 hr => exact F8_p7_o.step_c5 hk hpar h1 h2 hr hd hc hv
  | s6 r hr => exact F8_p7_o.step_s6 hk hpar hr hd hc hv
  | c7 i r h1 h2 hr => exact F8_p7_o.step_c7 hk hpar h1 h2 hr hd hc hv
  | c8 i r h1 h2 h3 hr => exact F8_p7_o.step_c8 hk hpar h1 h2 h3 hr hd hc hv
  | c9 i r h1 h2 h3 hr => exact F8_p7_o.step_c9 hk hpar h1 h2 h3 hr hd hc hv
  | c10 i r h1 h2 hr => exact F8_p7_o.step_c10 hk hpar h1 h2 hr hd hc hv
  | c11 i r h1 h2 hr => exact F8_p7_o.step_c11 hk hpar h1 h2 hr hd hc hv
  | s12 r hr => exact F8_p7_o.step_s12 hk hpar hr hd hc hv

theorem F8_p7_o.bound {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : F8_p7_o k r) : 2 - (8 * 3 ^ k + 7) ≤ r := by
  cases hr with
  | z => have := pow3_ge k 1 3 (by decide) (by omega); omega
  | c1 i r h1 h2 hr => exact F8_p7_o.bd_c1 hk h1 h2 hr
  | c2 i r h1 h2 h3 hr => exact F8_p7_o.bd_c2 hk h1 h2 h3 hr
  | c3 i r h1 h2 h3 hr => exact F8_p7_o.bd_c3 hk h1 h2 h3 hr
  | c4 i r h1 h2 hr => exact F8_p7_o.bd_c4 hk h1 h2 hr
  | c5 i r h1 h2 hr => exact F8_p7_o.bd_c5 hk h1 h2 hr
  | s6 r hr => exact F8_p7_o.bd_s6 hk hr
  | c7 i r h1 h2 hr => exact F8_p7_o.bd_c7 hk h1 h2 hr
  | c8 i r h1 h2 h3 hr => exact F8_p7_o.bd_c8 hk h1 h2 h3 hr
  | c9 i r h1 h2 h3 hr => exact F8_p7_o.bd_c9 hk h1 h2 h3 hr
  | c10 i r h1 h2 hr => exact F8_p7_o.bd_c10 hk h1 h2 hr
  | c11 i r h1 h2 hr => exact F8_p7_o.bd_c11 hk h1 h2 hr
  | s12 r hr => exact F8_p7_o.bd_s12 hk hr

theorem F8_p7_o.nz {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : F8_p7_o k r) (hpos : 0 < r) : ¬ ZF r := by
  cases hr with
  | z => omega
  | c1 i r h1 h2 hr => exact F8_p7_o.nz_c1 hk h1 h2 hr hpos
  | c2 i r h1 h2 h3 hr => exact F8_p7_o.nz_c2 hk h1 h2 h3 hr hpos
  | c3 i r h1 h2 h3 hr => exact F8_p7_o.nz_c3 hk h1 h2 h3 hr hpos
  | c4 i r h1 h2 hr => exact F8_p7_o.nz_c4 hk h1 h2 hr hpos
  | c5 i r h1 h2 hr => exact F8_p7_o.nz_c5 hk h1 h2 hr hpos
  | s6 r hr => exact F8_p7_o.nz_s6 hk hr hpos
  | c7 i r h1 h2 hr => exact F8_p7_o.nz_c7 hk h1 h2 hr hpos
  | c8 i r h1 h2 h3 hr => exact F8_p7_o.nz_c8 hk h1 h2 h3 hr hpos
  | c9 i r h1 h2 h3 hr => exact F8_p7_o.nz_c9 hk h1 h2 h3 hr hpos
  | c10 i r h1 h2 hr => exact F8_p7_o.nz_c10 hk h1 h2 hr hpos
  | c11 i r h1 h2 hr => exact F8_p7_o.nz_c11 hk h1 h2 hr hpos
  | s12 r hr => exact F8_p7_o.nz_s12 hk hr hpos

theorem F8_p7_o.main (k : Nat) (hk : 14 ≤ k) (hpar : k % 2 = 1) :
    ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (8 * 3 ^ k + 7) * m :=
  not_BB_of_inv _ (F8_p7_o k) .z
    (fun _ _ _ _ hr hd hc hv => F8_p7_o.step hk hpar hr hd hc hv)
    (fun _ hr => F8_p7_o.bound hk hr)
    (fun _ _ _ hr hc hv hpos => F8_p7_o.nz hk (F8_p7_o.step hk hpar hr (.inl rfl) hc (by omega)) hpos)

theorem not_BB_8_p7_k5 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (8 * 3 ^ 5 + 7) * m :=
  not_BB_of_cert _ [-974, -970, -958, -922, -814, -812, -650, -542, -524, -506, -494, -492, -490, -488, -486, -482, -476, -470, -434, -380, -326, 0, 326, 380, 434, 470, 476, 482, 486, 488, 490, 492, 494, 506, 524, 542, 650, 812, 814, 922, 958, 970, 974] (by decide)

theorem not_BB_8_p7_k6 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (8 * 3 ^ 6 + 7) * m :=
  not_BB_of_cert _ [-2432, -1946, -1568, -1514, -1472, -1466, -1460, -1458, -1456, -1442, -1424, -1298, -1136, 0, 1136, 1298, 1424, 1442, 1456, 1458, 1460, 1466, 1472, 1514, 1568, 1946, 2432] (by decide)

theorem not_BB_8_p7_k7 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (8 * 3 ^ 7 + 7) * m :=
  not_BB_of_cert _ [-8750, -8746, -8734, -8698, -8590, -8266, -7294, -7292, -5834, -4862, -4700, -4538, -4430, -4412, -4394, -4382, -4380, -4378, -4376, -4374, -4370, -4364, -4358, -4322, -4268, -4214, -3890, -3404, -2918, 0, 2918, 3404, 3890, 4214, 4268, 4322, 4358, 4364, 4370, 4374, 4376, 4378, 4380, 4382, 4394, 4412, 4430, 4538, 4700, 4862, 5834, 7292, 7294, 8266, 8590, 8698, 8734, 8746, 8750] (by decide)

theorem not_BB_8_p7_k8 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (8 * 3 ^ 8 + 7) * m :=
  not_BB_of_cert _ [-21872, -17498, -14096, -13610, -13232, -13178, -13136, -13130, -13124, -13122, -13120, -13106, -13088, -12962, -12800, -11666, -10208, 0, 10208, 11666, 12800, 12962, 13088, 13106, 13120, 13122, 13124, 13130, 13136, 13178, 13232, 13610, 14096, 17498, 21872] (by decide)

theorem not_BB_8_p7_k9 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (8 * 3 ^ 9 + 7) * m :=
  not_BB_of_cert _ [-78734, -78730, -78718, -78682, -78574, -78250, -77278, -74362, -65614, -65612, -52490, -43742, -42284, -40826, -39854, -39692, -39530, -39422, -39404, -39386, -39374, -39372, -39370, -39368, -39366, -39362, -39356, -39350, -39314, -39260, -39206, -38882, -38396, -37910, -34994, -30620, -26246, 0, 26246, 30620, 34994, 37910, 38396, 38882, 39206, 39260, 39314, 39350, 39356, 39362, 39366, 39368, 39370, 39372, 39374, 39386, 39404, 39422, 39530, 39692, 39854, 40826, 42284, 43742, 52490, 65612, 65614, 74362, 77278, 78250, 78574, 78682, 78718, 78730, 78734] (by decide)

theorem not_BB_8_p7_k10 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (8 * 3 ^ 10 + 7) * m :=
  not_BB_of_cert _ [-196832, -157466, -126848, -122474, -119072, -118586, -118208, -118154, -118112, -118106, -118100, -118098, -118096, -118082, -118064, -117938, -117776, -116642, -115184, -104978, -91856, 0, 91856, 104978, 115184, 116642, 117776, 117938, 118064, 118082, 118096, 118098, 118100, 118106, 118112, 118154, 118208, 118586, 119072, 122474, 126848, 157466, 196832] (by decide)

theorem not_BB_8_p7_k11 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (8 * 3 ^ 11 + 7) * m :=
  not_BB_of_cert _ [-708590, -708586, -708574, -708538, -708430, -708106, -707134, -704218, -695470, -669226, -590494, -590492, -472394, -393662, -380540, -367418, -358670, -357212, -355754, -354782, -354620, -354458, -354350, -354332, -354314, -354302, -354300, -354298, -354296, -354294, -354290, -354284, -354278, -354242, -354188, -354134, -353810, -353324, -352838, -349922, -345548, -341174, -314930, -275564, -236198, 0, 236198, 275564, 314930, 341174, 345548, 349922, 352838, 353324, 353810, 354134, 354188, 354242, 354278, 354284, 354290, 354294, 354296, 354298, 354300, 354302, 354314, 354332, 354350, 354458, 354620, 354782, 355754, 357212, 358670, 367418, 380540, 393662, 472394, 590492, 590494, 669226, 695470, 704218, 707134, 708106, 708430, 708538, 708574, 708586, 708590] (by decide)

theorem not_BB_8_p7_k12 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (8 * 3 ^ 12 + 7) * m :=
  not_BB_of_cert _ [-1771472, -1417178, -1141616, -1102250, -1071632, -1067258, -1063856, -1063370, -1062992, -1062938, -1062896, -1062890, -1062884, -1062882, -1062880, -1062866, -1062848, -1062722, -1062560, -1061426, -1059968, -1049762, -1036640, -944786, -826688, 0, 826688, 944786, 1036640, 1049762, 1059968, 1061426, 1062560, 1062722, 1062848, 1062866, 1062880, 1062882, 1062884, 1062890, 1062896, 1062938, 1062992, 1063370, 1063856, 1067258, 1071632, 1102250, 1141616, 1417178, 1771472] (by decide)

theorem not_BB_8_p7_k13 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (8 * 3 ^ 13 + 7) * m :=
  not_BB_of_cert _ [-6377294, -6377290, -6377278, -6377242, -6377134, -6376810, -6375838, -6372922, -6364174, -6337930, -6259198, -6023002, -5314414, -5314412, -4251530, -3542942, -3424844, -3306746, -3228014, -3214892, -3201770, -3193022, -3191564, -3190106, -3189134, -3188972, -3188810, -3188702, -3188684, -3188666, -3188654, -3188652, -3188650, -3188648, -3188646, -3188642, -3188636, -3188630, -3188594, -3188540, -3188486, -3188162, -3187676, -3187190, -3184274, -3179900, -3175526, -3149282, -3109916, -3070550, -2834354, -2480060, -2125766, 0, 2125766, 2480060, 2834354, 3070550, 3109916, 3149282, 3175526, 3179900, 3184274, 3187190, 3187676, 3188162, 3188486, 3188540, 3188594, 3188630, 3188636, 3188642, 3188646, 3188648, 3188650, 3188652, 3188654, 3188666, 3188684, 3188702, 3188810, 3188972, 3189134, 3190106, 3191564, 3193022, 3201770, 3214892, 3228014, 3306746, 3424844, 3542942, 4251530, 5314412, 5314414, 6023002, 6259198, 6337930, 6364174, 6372922, 6375838, 6376810, 6377134, 6377242, 6377278, 6377290, 6377294] (by decide)

/-- **Theorem.** 8·3^k + 7 ∉ B/B for every k ≥ 5. -/
theorem not_BB_8_p7 (k : Nat) (hk0 : 5 ≤ k) :
    ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (8 * 3 ^ k + 7) * m := by
  rcases (show k = 5 ∨ k = 6 ∨ k = 7 ∨ k = 8 ∨ k = 9 ∨ k = 10 ∨ k = 11 ∨ k = 12 ∨ k = 13 ∨ 14 ≤ k by omega) with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | hk
  · exact not_BB_8_p7_k5
  · exact not_BB_8_p7_k6
  · exact not_BB_8_p7_k7
  · exact not_BB_8_p7_k8
  · exact not_BB_8_p7_k9
  · exact not_BB_8_p7_k10
  · exact not_BB_8_p7_k11
  · exact not_BB_8_p7_k12
  · exact not_BB_8_p7_k13
  · rcases Nat.mod_two_eq_zero_or_one k with h | h
    · exact F8_p7_e.main k hk h
    · exact F8_p7_o.main k hk h

end Tern
