/-
  4·3^k + 5 is not in B/B for every k ≥ 5.
  Generated by guy-f31-bt/lean_gen/gen_lean.py; every step is re-checked by Lean (omega, decide).
-/
import BalancedTernary.TernCore

namespace Tern

set_option maxHeartbeats 4000000
set_option linter.unusedVariables false

/-- Carry set for k ≡ 0 (mod 2). -/
inductive F4_p5_e (k : Nat) : Int → Prop
  | z : F4_p5_e k 0
  | c1 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) : F4_p5_e k r
  | c2 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) : F4_p5_e k r
  | s3 (r : Int) (hr : r = 2 * 3 ^ k + 2) : F4_p5_e k r
  | c4 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) : F4_p5_e k r
  | c5 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) : F4_p5_e k r
  | s6 (r : Int) (hr : r = -(2 * 3 ^ k + 2)) : F4_p5_e k r

theorem F4_p5_e.step_z {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = 0)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  subst hr
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.c1 (k - 1) r' (by omega) (by omega) (by omega))
  · exact (.c4 (k - 1) r' (by omega) (by omega) (by omega))
  · omega

theorem F4_p5_e.step_c1 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.s3 r' (by omega))
    · exact (.c5 (k - 1) r' (by omega) (by omega) (by omega))
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c1 (i - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega

theorem F4_p5_e.bd_c1 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) : 2 - (4 * 3 ^ k + 5) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F4_p5_e.nz_c1 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    exact h0.mod3 (by omega)
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0) (-1) h1 (by omega) (.inr rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-5)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-2)) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (2 * 3 ^ (k - 3) + (-1)) 1 h2 (by omega) (.inl rfl) (by omega)
    have h4 := ZF.down (2 * 3 ^ (k - 4) + 0) (-1) h3 (by omega) (.inr rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-17)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-6)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-53)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-18)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - 2 * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - 2 * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F4_p5_e.step_c2 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c5 (k - 1) r' (by omega) (by omega) (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c2 (i - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega

theorem F4_p5_e.bd_c2 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) : 2 - (4 * 3 ^ k + 5) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F4_p5_e.nz_c2 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-1)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0) (-1) h1 (by omega) (.inr rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-3)) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-11)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-4)) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (2 * 3 ^ (k - 3) + (-1)) (-1) h2 (by omega) (.inr rfl) (by omega)
    have h4 := ZF.down (2 * 3 ^ (k - 4) + 0) (-1) h3 (by omega) (.inr rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-35)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-12)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-107)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-36)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - 4 * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - 4 * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F4_p5_e.step_s3 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = 2 * 3 ^ k + 2)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · exact (.s3 r' (by omega))
  · omega
  · omega
  · omega

theorem F4_p5_e.bd_s3 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2) : 2 - (4 * 3 ^ k + 5) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F4_p5_e.nz_s3 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  intro h0
  subst hr
  have h1 := ZF.down (2 * 3 ^ (k - 1) + 1) (-1) h0 (by omega) (.inr rfl) (by omega)
  have h2 := ZF.down (2 * 3 ^ (k - 2) + 0) 1 h1 (by omega) (.inl rfl) (by omega)
  exact h2.mod3 (by omega)

theorem F4_p5_e.step_c4 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c2 (k - 1) r' (by omega) (by omega) (by omega))
    · exact (.s6 r' (by omega))
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c4 (i - 1) r' (by omega) (by omega) (by omega))

theorem F4_p5_e.bd_c4 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) : 2 - (4 * 3 ^ k + 5) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F4_p5_e.nz_c4 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F4_p5_e.step_c5 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c2 (k - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c5 (i - 1) r' (by omega) (by omega) (by omega))

theorem F4_p5_e.bd_c5 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) : 2 - (4 * 3 ^ k + 5) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F4_p5_e.nz_c5 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F4_p5_e.step_s6 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : r = -(2 * 3 ^ k + 2))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_e k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · omega
  · omega
  · exact (.s6 r' (by omega))

theorem F4_p5_e.bd_s6 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2)) : 2 - (4 * 3 ^ k + 5) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F4_p5_e.nz_s6 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega

theorem F4_p5_e.step {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 0) {r r' d c : Int}
    (hr : F4_p5_e k r) (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_e k r' := by
  cases hr with
  | z => exact F4_p5_e.step_z hk hpar rfl hd hc hv
  | c1 i r h1 h2 hr => exact F4_p5_e.step_c1 hk hpar h1 h2 hr hd hc hv
  | c2 i r h1 h2 hr => exact F4_p5_e.step_c2 hk hpar h1 h2 hr hd hc hv
  | s3 r hr => exact F4_p5_e.step_s3 hk hpar hr hd hc hv
  | c4 i r h1 h2 hr => exact F4_p5_e.step_c4 hk hpar h1 h2 hr hd hc hv
  | c5 i r h1 h2 hr => exact F4_p5_e.step_c5 hk hpar h1 h2 hr hd hc hv
  | s6 r hr => exact F4_p5_e.step_s6 hk hpar hr hd hc hv

theorem F4_p5_e.bound {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : F4_p5_e k r) : 2 - (4 * 3 ^ k + 5) ≤ r := by
  cases hr with
  | z => have := pow3_ge k 1 3 (by decide) (by omega); omega
  | c1 i r h1 h2 hr => exact F4_p5_e.bd_c1 hk h1 h2 hr
  | c2 i r h1 h2 hr => exact F4_p5_e.bd_c2 hk h1 h2 hr
  | s3 r hr => exact F4_p5_e.bd_s3 hk hr
  | c4 i r h1 h2 hr => exact F4_p5_e.bd_c4 hk h1 h2 hr
  | c5 i r h1 h2 hr => exact F4_p5_e.bd_c5 hk h1 h2 hr
  | s6 r hr => exact F4_p5_e.bd_s6 hk hr

theorem F4_p5_e.nz {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : F4_p5_e k r) (hpos : 0 < r) : ¬ ZF r := by
  cases hr with
  | z => omega
  | c1 i r h1 h2 hr => exact F4_p5_e.nz_c1 hk h1 h2 hr hpos
  | c2 i r h1 h2 hr => exact F4_p5_e.nz_c2 hk h1 h2 hr hpos
  | s3 r hr => exact F4_p5_e.nz_s3 hk hr hpos
  | c4 i r h1 h2 hr => exact F4_p5_e.nz_c4 hk h1 h2 hr hpos
  | c5 i r h1 h2 hr => exact F4_p5_e.nz_c5 hk h1 h2 hr hpos
  | s6 r hr => exact F4_p5_e.nz_s6 hk hr hpos

theorem F4_p5_e.main (k : Nat) (hk : 14 ≤ k) (hpar : k % 2 = 0) :
    ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (4 * 3 ^ k + 5) * m :=
  not_BB_of_inv _ (F4_p5_e k) .z
    (fun _ _ _ _ hr hd hc hv => F4_p5_e.step hk hpar hr hd hc hv)
    (fun _ hr => F4_p5_e.bound hk hr)
    (fun _ _ _ hr hc hv hpos => F4_p5_e.nz hk (F4_p5_e.step hk hpar hr (.inl rfl) hc (by omega)) hpos)

/-- Carry set for k ≡ 1 (mod 2). -/
inductive F4_p5_o (k : Nat) : Int → Prop
  | z : F4_p5_o k 0
  | c1 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) : F4_p5_o k r
  | c2 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) : F4_p5_o k r
  | s3 (r : Int) (hr : r = 2 * 3 ^ k + 2) : F4_p5_o k r
  | c4 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) : F4_p5_o k r
  | c5 (i : Nat) (r : Int) (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) : F4_p5_o k r
  | s6 (r : Int) (hr : r = -(2 * 3 ^ k + 2)) : F4_p5_o k r

theorem F4_p5_o.step_z {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    (hr : r = 0)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  subst hr
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · exact (.c1 (k - 1) r' (by omega) (by omega) (by omega))
  · exact (.c4 (k - 1) r' (by omega) (by omega) (by omega))
  · omega

theorem F4_p5_o.step_c1 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.s3 r' (by omega))
    · exact (.c5 (k - 1) r' (by omega) (by omega) (by omega))
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c1 (i - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega

theorem F4_p5_o.bd_c1 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) : 2 - (4 * 3 ^ k + 5) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F4_p5_o.nz_c1 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 2 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    exact h0.mod3 (by omega)
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0) (-1) h1 (by omega) (.inr rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-5)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-2)) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (2 * 3 ^ (k - 3) + (-1)) 1 h2 (by omega) (.inl rfl) (by omega)
    have h4 := ZF.down (2 * 3 ^ (k - 4) + 0) (-1) h3 (by omega) (.inr rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-17)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-6)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-53)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-18)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - 2 * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - 2 * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F4_p5_o.step_c2 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c5 (k - 1) r' (by omega) (by omega) (by omega))
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c2 (i - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega

theorem F4_p5_o.bd_c2 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) : 2 - (4 * 3 ^ k + 5) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F4_p5_o.nz_c2 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2 - 4 * 3 ^ i) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  intro h0
  subst hr
  rcases (show i = 0 ∨ i = 1 ∨ i = 2 ∨ i = 3 ∨ i = 4 ∨ 5 ≤ i by omega) with rfl | rfl | rfl | rfl | rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-1)) 1 h0 (by omega) (.inl rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0) (-1) h1 (by omega) (.inr rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 1 = 3 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-3)) (-1) h0 (by omega) (.inr rfl) (by omega)
    exact h1.mod3 (by omega)
  · have : (3 : Int) ^ 2 = 9 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-11)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-4)) 1 h1 (by omega) (.inl rfl) (by omega)
    have h3 := ZF.down (2 * 3 ^ (k - 3) + (-1)) (-1) h2 (by omega) (.inr rfl) (by omega)
    have h4 := ZF.down (2 * 3 ^ (k - 4) + 0) (-1) h3 (by omega) (.inr rfl) (by omega)
    exact h4.mod3 (by omega)
  · have : (3 : Int) ^ 3 = 27 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-35)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-12)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · have : (3 : Int) ^ 4 = 81 := by decide
    have h1 := ZF.down (2 * 3 ^ (k - 1) + (-107)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + (-36)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)
  · skip
    have := p3 i (i - 1) (by omega)
    have := p3 (i - 1) (i - 2) (by omega)
    have := p3 (i - 2) (i - 3) (by omega)
    have := pow3_pos (i - 3)
    have := pow3_le_mul (i - 0) (k - 0) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 1) (k - 1) 1 3 (by decide) (by omega)
    have := pow3_le_mul (i - 2) (k - 2) 1 3 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 0) 5 243 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 1) 4 81 (by decide) (by omega)
    have := pow3_le_mul 0 (i - 2) 3 27 (by decide) (by omega)
    have h1 := ZF.down (2 * 3 ^ (k - 1) + 1 - 4 * 3 ^ (i - 1)) (-1) h0 (by omega) (.inr rfl) (by omega)
    have h2 := ZF.down (2 * 3 ^ (k - 2) + 0 - 4 * 3 ^ (i - 2)) 1 h1 (by omega) (.inl rfl) (by omega)
    exact h2.mod3 (by omega)

theorem F4_p5_o.step_s3 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    (hr : r = 2 * 3 ^ k + 2)
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · exact (.s3 r' (by omega))
  · omega
  · omega
  · omega

theorem F4_p5_o.bd_s3 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2) : 2 - (4 * 3 ^ k + 5) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F4_p5_o.nz_s3 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = 2 * 3 ^ k + 2) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  intro h0
  subst hr
  have h1 := ZF.down (2 * 3 ^ (k - 1) + 1) (-1) h0 (by omega) (.inr rfl) (by omega)
  have h2 := ZF.down (2 * 3 ^ (k - 2) + 0) 1 h1 (by omega) (.inl rfl) (by omega)
  exact h2.mod3 (by omega)

theorem F4_p5_o.step_c4 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · exact (.c2 (k - 1) r' (by omega) (by omega) (by omega))
    · exact (.s6 r' (by omega))
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c4 (i - 1) r' (by omega) (by omega) (by omega))

theorem F4_p5_o.bd_c4 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) : 2 - (4 * 3 ^ k + 5) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F4_p5_o.nz_c4 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 2 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F4_p5_o.step_c5 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases (show i = 0 ∨ 1 ≤ i by omega) with rfl | hi
  · have : (3 : Int) ^ 0 = 1 := by decide
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · exact (.c2 (k - 1) r' (by omega) (by omega) (by omega))
    · omega
    · omega
    · omega
  · have := p3 i (i - 1) (by omega)
    rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
    · omega
    · omega
    · omega
    · exact (.c5 (i - 1) r' (by omega) (by omega) (by omega))

theorem F4_p5_o.bd_c5 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) : 2 - (4 * 3 ^ k + 5) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega
theorem F4_p5_o.nz_c5 {k : Nat} (hk : 14 ≤ k) {i : Nat} (h1 : 0 ≤ i) (h2 : i + 1 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2 - 4 * 3 ^ i)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  have := pow3_mono i (k - 1) (by omega)
  have := pow3_pos i
  omega

theorem F4_p5_o.step_s6 {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    (hr : r = -(2 * 3 ^ k + 2))
    (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_o k r' := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  rcases hd with rfl | rfl <;> rcases hc with rfl | rfl
  · omega
  · omega
  · omega
  · exact (.s6 r' (by omega))

theorem F4_p5_o.bd_s6 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2)) : 2 - (4 * 3 ^ k + 5) ≤ r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega
theorem F4_p5_o.nz_s6 {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : r = -(2 * 3 ^ k + 2)) (hpos : 0 < r) : ¬ ZF r := by
  have := p3 k (k - 1) (by omega)
  have := p3 (k - 1) (k - 2) (by omega)
  have := p3 (k - 2) (k - 3) (by omega)
  have := p3 (k - 3) (k - 4) (by omega)
  have := p3 (k - 4) (k - 5) (by omega)
  have := p3 (k - 5) (k - 6) (by omega)
  have := p3 (k - 6) (k - 7) (by omega)
  have := p3 (k - 7) (k - 8) (by omega)
  have := p3 (k - 8) (k - 9) (by omega)
  have := p3 (k - 9) (k - 10) (by omega)
  have := pow3_pos (k - 10)
  omega

theorem F4_p5_o.step {k : Nat} (hk : 14 ≤ k) (hpar : k % 2 = 1) {r r' d c : Int}
    (hr : F4_p5_o k r) (hd : d = 1 ∨ d = -1) (hc : c = 1 ∨ c = -1)
    (hv : r + (4 * 3 ^ k + 5) * d = 3 * r' + c) : F4_p5_o k r' := by
  cases hr with
  | z => exact F4_p5_o.step_z hk hpar rfl hd hc hv
  | c1 i r h1 h2 hr => exact F4_p5_o.step_c1 hk hpar h1 h2 hr hd hc hv
  | c2 i r h1 h2 hr => exact F4_p5_o.step_c2 hk hpar h1 h2 hr hd hc hv
  | s3 r hr => exact F4_p5_o.step_s3 hk hpar hr hd hc hv
  | c4 i r h1 h2 hr => exact F4_p5_o.step_c4 hk hpar h1 h2 hr hd hc hv
  | c5 i r h1 h2 hr => exact F4_p5_o.step_c5 hk hpar h1 h2 hr hd hc hv
  | s6 r hr => exact F4_p5_o.step_s6 hk hpar hr hd hc hv

theorem F4_p5_o.bound {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : F4_p5_o k r) : 2 - (4 * 3 ^ k + 5) ≤ r := by
  cases hr with
  | z => have := pow3_ge k 1 3 (by decide) (by omega); omega
  | c1 i r h1 h2 hr => exact F4_p5_o.bd_c1 hk h1 h2 hr
  | c2 i r h1 h2 hr => exact F4_p5_o.bd_c2 hk h1 h2 hr
  | s3 r hr => exact F4_p5_o.bd_s3 hk hr
  | c4 i r h1 h2 hr => exact F4_p5_o.bd_c4 hk h1 h2 hr
  | c5 i r h1 h2 hr => exact F4_p5_o.bd_c5 hk h1 h2 hr
  | s6 r hr => exact F4_p5_o.bd_s6 hk hr

theorem F4_p5_o.nz {k : Nat} (hk : 14 ≤ k) {r : Int} (hr : F4_p5_o k r) (hpos : 0 < r) : ¬ ZF r := by
  cases hr with
  | z => omega
  | c1 i r h1 h2 hr => exact F4_p5_o.nz_c1 hk h1 h2 hr hpos
  | c2 i r h1 h2 hr => exact F4_p5_o.nz_c2 hk h1 h2 hr hpos
  | s3 r hr => exact F4_p5_o.nz_s3 hk hr hpos
  | c4 i r h1 h2 hr => exact F4_p5_o.nz_c4 hk h1 h2 hr hpos
  | c5 i r h1 h2 hr => exact F4_p5_o.nz_c5 hk h1 h2 hr hpos
  | s6 r hr => exact F4_p5_o.nz_s6 hk hr hpos

theorem F4_p5_o.main (k : Nat) (hk : 14 ≤ k) (hpar : k % 2 = 1) :
    ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (4 * 3 ^ k + 5) * m :=
  not_BB_of_inv _ (F4_p5_o k) .z
    (fun _ _ _ _ hr hd hc hv => F4_p5_o.step hk hpar hr hd hc hv)
    (fun _ hr => F4_p5_o.bound hk hr)
    (fun _ _ _ hr hc hv hpos => F4_p5_o.nz hk (F4_p5_o.step hk hpar hr (.inl rfl) hc (by omega)) hpos)

theorem not_BB_4_p5_k5 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (4 * 3 ^ 5 + 5) * m :=
  not_BB_of_cert _ [-488, -486, -484, -482, -476, -470, -452, -434, -380, -326, -164, 0, 164, 326, 380, 434, 452, 470, 476, 482, 484, 486, 488] (by decide)

theorem not_BB_4_p5_k6 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (4 * 3 ^ 6 + 5) * m :=
  not_BB_of_cert _ [-1460, -1458, -1456, -1454, -1448, -1442, -1424, -1406, -1352, -1298, -1136, -974, -488, 0, 488, 974, 1136, 1298, 1352, 1406, 1424, 1442, 1448, 1454, 1456, 1458, 1460] (by decide)

theorem not_BB_4_p5_k7 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (4 * 3 ^ 7 + 5) * m :=
  not_BB_of_cert _ [-4376, -4374, -4372, -4370, -4364, -4358, -4340, -4322, -4268, -4214, -4052, -3890, -3404, -2918, -1460, 0, 1460, 2918, 3404, 3890, 4052, 4214, 4268, 4322, 4340, 4358, 4364, 4370, 4372, 4374, 4376] (by decide)

theorem not_BB_4_p5_k8 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (4 * 3 ^ 8 + 5) * m :=
  not_BB_of_cert _ [-13124, -13122, -13120, -13118, -13112, -13106, -13088, -13070, -13016, -12962, -12800, -12638, -12152, -11666, -10208, -8750, -4376, 0, 4376, 8750, 10208, 11666, 12152, 12638, 12800, 12962, 13016, 13070, 13088, 13106, 13112, 13118, 13120, 13122, 13124] (by decide)

theorem not_BB_4_p5_k9 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (4 * 3 ^ 9 + 5) * m :=
  not_BB_of_cert _ [-39368, -39366, -39364, -39362, -39356, -39350, -39332, -39314, -39260, -39206, -39044, -38882, -38396, -37910, -36452, -34994, -30620, -26246, -13124, 0, 13124, 26246, 30620, 34994, 36452, 37910, 38396, 38882, 39044, 39206, 39260, 39314, 39332, 39350, 39356, 39362, 39364, 39366, 39368] (by decide)

theorem not_BB_4_p5_k10 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (4 * 3 ^ 10 + 5) * m :=
  not_BB_of_cert _ [-118100, -118098, -118096, -118094, -118088, -118082, -118064, -118046, -117992, -117938, -117776, -117614, -117128, -116642, -115184, -113726, -109352, -104978, -91856, -78734, -39368, 0, 39368, 78734, 91856, 104978, 109352, 113726, 115184, 116642, 117128, 117614, 117776, 117938, 117992, 118046, 118064, 118082, 118088, 118094, 118096, 118098, 118100] (by decide)

theorem not_BB_4_p5_k11 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (4 * 3 ^ 11 + 5) * m :=
  not_BB_of_cert _ [-354296, -354294, -354292, -354290, -354284, -354278, -354260, -354242, -354188, -354134, -353972, -353810, -353324, -352838, -351380, -349922, -345548, -341174, -328052, -314930, -275564, -236198, -118100, 0, 118100, 236198, 275564, 314930, 328052, 341174, 345548, 349922, 351380, 352838, 353324, 353810, 353972, 354134, 354188, 354242, 354260, 354278, 354284, 354290, 354292, 354294, 354296] (by decide)

theorem not_BB_4_p5_k12 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (4 * 3 ^ 12 + 5) * m :=
  not_BB_of_cert _ [-1062884, -1062882, -1062880, -1062878, -1062872, -1062866, -1062848, -1062830, -1062776, -1062722, -1062560, -1062398, -1061912, -1061426, -1059968, -1058510, -1054136, -1049762, -1036640, -1023518, -984152, -944786, -826688, -708590, -354296, 0, 354296, 708590, 826688, 944786, 984152, 1023518, 1036640, 1049762, 1054136, 1058510, 1059968, 1061426, 1061912, 1062398, 1062560, 1062722, 1062776, 1062830, 1062848, 1062866, 1062872, 1062878, 1062880, 1062882, 1062884] (by decide)

theorem not_BB_4_p5_k13 : ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (4 * 3 ^ 13 + 5) * m :=
  not_BB_of_cert _ [-3188648, -3188646, -3188644, -3188642, -3188636, -3188630, -3188612, -3188594, -3188540, -3188486, -3188324, -3188162, -3187676, -3187190, -3185732, -3184274, -3179900, -3175526, -3162404, -3149282, -3109916, -3070550, -2952452, -2834354, -2480060, -2125766, -1062884, 0, 1062884, 2125766, 2480060, 2834354, 2952452, 3070550, 3109916, 3149282, 3162404, 3175526, 3179900, 3184274, 3185732, 3187190, 3187676, 3188162, 3188324, 3188486, 3188540, 3188594, 3188612, 3188630, 3188636, 3188642, 3188644, 3188646, 3188648] (by decide)

/-- **Theorem.** 4·3^k + 5 ∉ B/B for every k ≥ 5. -/
theorem not_BB_4_p5 (k : Nat) (hk0 : 5 ≤ k) :
    ¬ ∃ m N : Int, 0 < m ∧ ZF m ∧ 0 < N ∧ ZF N ∧ N = (4 * 3 ^ k + 5) * m := by
  rcases (show k = 5 ∨ k = 6 ∨ k = 7 ∨ k = 8 ∨ k = 9 ∨ k = 10 ∨ k = 11 ∨ k = 12 ∨ k = 13 ∨ 14 ≤ k by omega) with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | hk
  · exact not_BB_4_p5_k5
  · exact not_BB_4_p5_k6
  · exact not_BB_4_p5_k7
  · exact not_BB_4_p5_k8
  · exact not_BB_4_p5_k9
  · exact not_BB_4_p5_k10
  · exact not_BB_4_p5_k11
  · exact not_BB_4_p5_k12
  · exact not_BB_4_p5_k13
  · rcases Nat.mod_two_eq_zero_or_one k with h | h
    · exact F4_p5_e.main k hk h
    · exact F4_p5_o.main k hk h

end Tern
