"""Independent check of the finite statements in the note "Labelling binary trees by powers of two".

Written from the definitions alone; shares no code with the C programs in this folder.
A tree is a vertex with at most two unordered children; a labelling onto a set S is a bijection with
root at min S and every child = parent + a power of two.

Checks (NMAX = 12 by default):
  1. tree counts 1, 1, 2, 3, 6, 11, 23, 46, 98, 207, 451, 983 (Wedderburn-Etherington, OEIS A001190 shifted);
  2. every tree with n <= NMAX vertices has a labelling by {0, ..., n-1} with root 0 (direct search);
  3. the root condition: the root's children can be given the labels 1 and 2 (1 for a single child), n <= NMAX;
  4. the primitive universal sets for n <= 9, generated by the tail rule and tested on every tree, are the
     intervals and the six sets listed in the note;
  5. the split (6, 4) at n = 11 has no labelling scheme that ignores the shapes of the branches, and every
     other split with n <= 11 has one;
then plants wrong statements and confirms each is rejected.
"""

from __future__ import annotations

import sys
from functools import cache
from itertools import combinations

POW2 = frozenset(2**k for k in range(64))


# ---------- trees: canonical tuples; () is a leaf, (c,) one child, (a, b) two children with a <= b ----------


@cache
def trees(n: int) -> tuple:
    if n == 1:
        return ((),)
    out = set()
    for c in trees(n - 1):
        out.add((c,))
    for a in range(1, n - 1):
        b = n - 1 - a
        if a > b:
            continue
        for x in trees(a):
            for y in trees(b):
                out.add(tuple(sorted((x, y))))
    return tuple(sorted(out))


def size(t: tuple) -> int:
    return 1 + sum(size(c) for c in t)


# ---------- labelling search ----------


def fits(t: tuple, S: frozenset[int], root: int) -> bool:
    """Is there a labelling of t by exactly S with the root labelled `root`?"""
    if root not in S or len(S) != size(t):
        return False
    rest = S - {root}
    if not t:
        return not rest
    cands = [root + p for p in POW2 if root + p in rest]
    if len(t) == 1:
        return any(fits(t[0], rest, c) for c in cands)
    a, b = t
    na = size(a)
    for ca in cands:
        for cb in cands:
            if ca == cb:
                continue
            # choose the labels of branch a: a subset of rest containing ca, all >= ca, of size na
            pool = sorted(x for x in rest if x >= ca and x != cb)
            if ca not in pool:
                continue
            others = [x for x in pool if x != ca]
            for comb in combinations(others, na - 1):
                A = frozenset(comb) | {ca}
                B = rest - A
                if cb in B and min(B) == cb and fits(a, A, ca) and fits(b, B, cb):
                    return True
    return False


def labelled(t: tuple) -> bool:
    return fits(t, frozenset(range(size(t))), 0)


def root_condition(t: tuple) -> bool:
    n = size(t)
    S = frozenset(range(n))
    if not t:
        return True
    if len(t) == 1:
        return fits(t[0], S - {0}, 1)
    a, b = t
    rest = S - {0}
    for x, y in ((a, b), (b, a)):
        nx = size(x)
        others = sorted(rest - {1, 2})
        for comb in combinations(others, nx - 1):
            X = frozenset(comb) | {1}
            Y = rest - X
            if 2 in Y and fits(x, X, 1) and fits(y, Y, 2):
                return True
    return False


# ---------- universal sets ----------


def universal(S: frozenset[int]) -> bool:
    return all(fits(t, S, 0) for t in trees(len(S)))


def primitive_universal(nmax: int) -> dict[int, set[frozenset[int]]]:
    """Generated by the tail rule: S = {0} u (p + T), T primitive universal of size n-1, p a power of two
    with p <= max T (or T = {0} for n = 2); then tested on every tree."""
    U: dict[int, set[frozenset[int]]] = {1: {frozenset({0})}, 2: {frozenset({0, 1})}}
    for n in range(3, nmax + 1):
        U[n] = set()
        for T in U[n - 1]:
            p = 1
            while p <= max(T):
                S = frozenset({0} | {p + x for x in T})
                if any(x % 2 for x in S) and universal(S):
                    U[n].add(S)
                p *= 2
    return U


def scaled_family(
    U: dict[int, set[frozenset[int]]], m: int, top: int
) -> list[frozenset[int]]:
    out = []
    for T in U[m]:
        j = 1
        while j * max(T, default=0) <= top:
            out.append(frozenset(j * x for x in T))
            j *= 2
            if max(T) == 0:
                break
    return out


def split_has_independent_scheme(a: int, b: int, U) -> bool:
    """[1, a + b] = (p + S1) u (q + S2), p != q powers of two, S1, S2 scaled universal of sizes a, b."""
    n = a + b + 1
    full = frozenset(range(1, n))
    for S1 in scaled_family(U, a, n):
        for p in (2**k for k in range(8)):
            A = frozenset(p + x for x in S1)
            if not A <= full:
                continue
            B = full - A
            q = min(B)
            if (
                q in POW2
                and q != p
                and frozenset(x - q for x in B) in set(scaled_family(U, b, n))
            ):
                return True
    return False


SPORADIC = {
    frozenset({0, 2, 3, 4}),
    frozenset({0, 1, 3, 4, 5}),
    frozenset({0, 2, 4, 5, 6}),
    frozenset({0, 1, 2, 4, 5, 6}),
    frozenset({0, 2, 3, 4, 5, 6, 7, 8}),
    frozenset({0, 2, 4, 5, 6, 7, 8, 9, 10}),
}
COUNTS = [1, 1, 2, 3, 6, 11, 23, 46, 98, 207, 451, 983, 2179]


def main() -> int:
    nmax = int(sys.argv[1]) if len(sys.argv) > 1 else 12
    ok = True

    def report(name: str, val: bool) -> None:
        nonlocal ok
        print(f"{'PASS' if val else 'FAIL'}  {name}", flush=True)
        ok &= val

    report("tree counts", [len(trees(n)) for n in range(1, nmax + 1)] == COUNTS[:nmax])
    report(
        f"every tree n <= {nmax} labelled",
        all(labelled(t) for n in range(1, nmax + 1) for t in trees(n)),
    )
    report(
        f"root condition n <= {nmax}",
        all(root_condition(t) for n in range(1, nmax + 1) for t in trees(n)),
    )
    U = primitive_universal(9)
    nonint = {S for n in U for S in U[n] if S != frozenset(range(n))}
    report(
        "primitive universal sets n <= 9: intervals and the six listed sets",
        nonint == SPORADIC and all(frozenset(range(n)) in U[n] for n in U),
    )
    U11 = primitive_universal(10)
    U11[11] = {frozenset(range(11))}
    bad = [
        (a, b)
        for n in range(3, 12)
        for a in range(1, n - 1)
        for b in [n - 1 - a]
        if a >= b and not split_has_independent_scheme(a, b, U11)
    ]
    report(
        "only the split (6, 4) at n <= 11 lacks a shape-independent scheme",
        bad == [(6, 4)],
    )

    # mutants: each wrong statement must be rejected
    mutants = [
        ("one of the six sporadic sets is not universal", any(not universal(S) for S in SPORADIC)),
        ("{0, 1, 2, 4} universal", universal(frozenset({0, 1, 2, 4}))),
        ("{0, 2, 3, 4, 5} universal", universal(frozenset({0, 2, 3, 4, 5}))),
        ("the cherry fits {0, 1, 3}", fits(((), ()), frozenset({0, 1, 3}), 0)),
        ("tree count at 11 is 452", len(trees(11)) == 452),
        ("a split other than (6, 4) lacks a scheme", bad != [(6, 4)]),
    ]
    for name, val in mutants:
        print(f"{'mutant SURVIVED' if val else 'mutant killed  '}  {name}")
        ok &= not val
    print("ALL PASS" if ok else "FAILURES")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
