import LeanProofs.BalancedMast.Lower

/-!
# The lower bound: the two-level induction (Lemma 5.3 and Theorem 1.1(3))

When `h₁ ≥ 2` and `h₂ ≥ 1`, expand `S` two levels and `T` one level. A *strategy* (`Strat`) is a
way of applying the recursion repeatedly from `(S, T)` and stopping at pairs of subtrees; it
bounds `mast(S, T)` below by the sum of `mast` over the stopped pairs (`Strat.val_le_root`). The
induction hypothesis at each stopped pair turns this into `t^a 2^(-c(h₁+h₂)) φ_s(y)`, where `y`
holds the eight overlap fractions (`Strat.val_eq_phi`). The inequality of Lemma 5.3,
`max_s φ_s ≥ 1` on the simplex over the 42 strategies (`CertTwo`), then closes the induction.

`strategies21` is generated by `balanced-mast/lean-aux/gen_strats.py` from the recursion, which
checks that its flattened forms are exactly the 42 strategies of the certifier, in its order.
-/

namespace BalancedMast

open Tree

section Helpers

variable {α : Type*} [DecidableEq α]

lemma mem_subtrees_trans {S U V : Tree α} (hU : U ∈ S.subtrees) (hV : V ∈ U.subtrees) :
    V ∈ S.subtrees := by
  induction S with
  | leaf x => simp [subtrees] at hU; subst hU; exact hV
  | node l r ihl ihr =>
    simp only [subtrees, List.mem_cons, List.mem_append] at hU ⊢
    rcases hU with rfl | hU | hU
    · simpa [subtrees] using hV
    · exact Or.inr (Or.inl (ihl hU))
    · exact Or.inr (Or.inr (ihr hU))

lemma sub_left {l r U : Tree α} (h : U ∈ l.subtrees) : U ∈ (node l r).subtrees := by
  simp [subtrees, h]

lemma sub_right {l r U : Tree α} (h : U ∈ r.subtrees) : U ∈ (node l r).subtrees := by
  simp [subtrees, h]

lemma sizeOf_le_of_mem_subtrees {S U : Tree α} (h : U ∈ S.subtrees) : sizeOf U ≤ sizeOf S := by
  induction S with
  | leaf x => simp [subtrees] at h; subst h; exact le_rfl
  | node l r ihl ihr =>
    simp only [subtrees, List.mem_cons, List.mem_append] at h
    rcases h with rfl | h | h
    · exact le_rfl
    · have := ihl h; simp; omega
    · have := ihr h; simp; omega

lemma ne_of_mem_left {l r U : Tree α} (h : U ∈ l.subtrees) : U ≠ node l r := by
  intro e; have := sizeOf_le_of_mem_subtrees h; rw [e] at this; simp at this <;> omega

lemma ne_of_mem_right {l r U : Tree α} (h : U ∈ r.subtrees) : U ≠ node l r := by
  intro e; have := sizeOf_le_of_mem_subtrees h; rw [e] at this; simp at this <;> omega

/-- The subtree at address `u` (bits read from the root; `false` is the left child). -/
def sub : Tree α → List Bool → Tree α
  | S, [] => S
  | node l _, false :: u => sub l u
  | node _ r, true :: u => sub r u
  | leaf x, _ :: _ => leaf x

/-- Height along the left spine (the height, for a balanced tree). -/
def ht : Tree α → ℕ
  | leaf _ => 0
  | node l _ => ht l + 1

lemma Bal.ht_eq {h : ℕ} {S : Tree α} (hS : Bal h S) : ht S = h := by
  induction hS with
  | leaf a => rfl
  | node _ _ ihl _ => simp [ht, ihl]

lemma Bal.bal_sub {h : ℕ} {S : Tree α} (hS : Bal h S) :
    ∀ u : List Bool, u.length ≤ h → Bal (h - u.length) (sub S u) := by
  induction hS with
  | leaf a => intro u hu; simp at hu; subst hu; simpa [sub] using Bal.leaf a
  | @node h l r hl hr ihl ihr =>
    intro u hu
    rcases u with _ | ⟨b, u⟩
    · simpa [sub] using Bal.node hl hr
    · cases b
      · simpa [sub] using ihl u (by simp at hu; omega)
      · simpa [sub] using ihr u (by simp at hu; omega)

lemma Bal.sub_node {h : ℕ} {S : Tree α} (hS : Bal h S) :
    ∀ u : List Bool, u.length < h →
      sub S u = Tree.node (sub S (u ++ [false])) (sub S (u ++ [true])) := by
  induction hS with
  | leaf a => intro u hu; simp at hu
  | @node h l r hl hr ihl ihr =>
    intro u hu
    rcases u with _ | ⟨b, u⟩
    · cases hl <;> cases hr <;> rfl
    · cases b
      · simpa [sub] using ihl u (by simp at hu; omega)
      · simpa [sub] using ihr u (by simp at hu; omega)

lemma sub_mem_subtrees (S : Tree α) : ∀ u : List Bool, sub S u ∈ S.subtrees := by
  induction S with
  | leaf x => intro u; rcases u with _ | ⟨b, u⟩ <;> simp [sub, subtrees]
  | node l r ihl ihr =>
    intro u
    rcases u with _ | ⟨b, u⟩
    · exact self_mem_subtrees _
    · cases b
      · exact sub_left (ihl u)
      · exact sub_right (ihr u)

lemma phylo_of_mem_subtrees {S U : Tree α} (hS : S.Phylo) (h : U ∈ S.subtrees) : U.Phylo := by
  induction S with
  | leaf x => simp [subtrees] at h; subst h; exact hS
  | node l r ihl ihr =>
    simp only [subtrees, List.mem_cons, List.mem_append] at h
    obtain ⟨pl, pr, _⟩ := phylo_node.1 hS
    rcases h with rfl | h | h
    · exact hS
    · exact ihl pl h
    · exact ihr pr h

/-- Subtrees of a balanced tree are balanced, and proper ones are lower. -/
lemma Bal.of_mem_subtrees {h : ℕ} {S U : Tree α} (hS : Bal h S) (hU : U ∈ S.subtrees) :
    Bal (ht U) U ∧ (U ≠ S → ht U < h) := by
  induction hS with
  | leaf a =>
    simp [subtrees] at hU; subst hU; exact ⟨Bal.leaf a, fun h => absurd rfl h⟩
  | @node h l r hl hr ihl ihr =>
    simp only [subtrees, List.mem_cons, List.mem_append] at hU
    rcases hU with rfl | hU | hU
    · exact ⟨(Bal.node hl hr).ht_eq ▸ Bal.node hl hr, fun h => absurd rfl h⟩
    · obtain ⟨b, hlt⟩ := ihl hU
      refine ⟨b, fun _ => ?_⟩
      by_cases e : U = l
      · rw [e, hl.ht_eq]; omega
      · have := hlt e; omega
    · obtain ⟨b, hlt⟩ := ihr hU
      refine ⟨b, fun _ => ?_⟩
      by_cases e : U = r
      · rw [e, hr.ht_eq]; omega
      · have := hlt e; omega

end Helpers

/-- A lookahead strategy at a pair of subtrees `(u, v)`. -/
inductive Strat
  | stop
  /-- `both false`: `(u0, v0)` and `(u1, v1)`; `both true`: `(u0, v1)` and `(u1, v0)`. -/
  | both (cross : Bool) (s₁ s₂ : Strat)
  /-- use only the half `b` of `T` -/
  | sideT (b : Bool) (s : Strat)
  /-- use only the half `b` of `S` -/
  | sideS (b : Bool) (s : Strat)
  deriving DecidableEq

namespace Strat

/-- The strategy stays within `dS` levels of `S` and `dT` levels of `T`. -/
def Fits : Strat → ℕ → ℕ → Bool
  | stop, _, _ => true
  | both _ s₁ s₂, dS, dT =>
    decide (1 ≤ dS ∧ 1 ≤ dT) && Fits s₁ (dS - 1) (dT - 1) && Fits s₂ (dS - 1) (dT - 1)
  | sideT _ s, dS, dT => decide (1 ≤ dT) && Fits s dS (dT - 1)
  | sideS _ s, dS, dT => decide (1 ≤ dS) && Fits s (dS - 1) dT

/-! ## Strategies bound `mast` -/

variable {α : Type*} [DecidableEq α]

/-- The value of a strategy on actual trees, with `g` evaluated at the stopped pairs. -/
noncomputable def val (g : Tree α → Tree α → ℝ) : Strat → Tree α → Tree α → ℝ
  | stop, S, T => g S T
  | both false s₁ s₂, node l r, node l' r' => val g s₁ l l' + val g s₂ r r'
  | both true s₁ s₂, node l r, node l' r' => val g s₁ l r' + val g s₂ r l'
  | sideT false s, S, node l' _ => val g s S l'
  | sideT true s, S, node _ r' => val g s S r'
  | sideS false s, node l _, T => val g s l T
  | sideS true s, node _ r, T => val g s r T
  | _, _, _ => 0

lemma val_le (g : Tree α → Tree α → ℝ) :
    ∀ (s : Strat) (S T : Tree α), S.Phylo → T.Phylo →
      (∀ U ∈ S.subtrees, ∀ V ∈ T.subtrees, g U V ≤ mast U V) → val g s S T ≤ mast S T := by
  intro s
  induction s with
  | stop => intro S T _ _ hg; exact hg S (self_mem_subtrees S) T (self_mem_subtrees T)
  | both cr s₁ s₂ ih₁ ih₂ =>
    intro S T pS pT hg
    cases S with
    | leaf x => cases cr <;> simp [val]
    | node l r =>
      cases T with
      | leaf x => cases cr <;> simp [val]
      | node l' r' =>
        obtain ⟨pl, pr, _⟩ := phylo_node.1 pS
        obtain ⟨pl', pr', _⟩ := phylo_node.1 pT
        cases cr
        · have := mast_node_node pS pT
          have h₁ := ih₁ l l' pl pl' fun U hU V hV => hg U (sub_left hU) V (sub_left hV)
          have h₂ := ih₂ r r' pr pr' fun U hU V hV => hg U (sub_right hU) V (sub_right hV)
          simp only [val]; exact (add_le_add h₁ h₂).trans (by exact_mod_cast this)
        · have := mast_node_cross pS pT
          have h₁ := ih₁ l r' pl pr' fun U hU V hV => hg U (sub_left hU) V (sub_right hV)
          have h₂ := ih₂ r l' pr pl' fun U hU V hV => hg U (sub_right hU) V (sub_left hV)
          simp only [val]; exact (add_le_add h₁ h₂).trans (by exact_mod_cast this)
  | sideT b s ih =>
    intro S T pS pT hg
    cases T with
    | leaf x => cases b <;> simp [val]
    | node l' r' =>
      obtain ⟨pl', pr', _⟩ := phylo_node.1 pT
      cases b
      · have : mast S l' ≤ mast S (node l' r') := by
          rw [mast_comm, mast_comm S]; exact mast_node_left pT
        have h := ih S l' pS pl' fun U hU V hV => hg U hU V (sub_left hV)
        simp only [val]; exact h.trans (by exact_mod_cast this)
      · have : mast S r' ≤ mast S (node l' r') := by
          rw [mast_comm, mast_comm S]; exact mast_node_right pT
        have h := ih S r' pS pr' fun U hU V hV => hg U hU V (sub_right hV)
        simp only [val]; exact h.trans (by exact_mod_cast this)
  | sideS b s ih =>
    intro S T pS pT hg
    cases S with
    | leaf x => cases b <;> simp [val]
    | node l r =>
      obtain ⟨pl, pr, _⟩ := phylo_node.1 pS
      cases b
      · have h := ih l T pl pT fun U hU V hV => hg U (sub_left hU) V hV
        simp only [val]; exact h.trans (by exact_mod_cast mast_node_left (T := T) pS)
      · have h := ih r T pr pT fun U hU V hV => hg U (sub_right hU) V hV
        simp only [val]; exact h.trans (by exact_mod_cast mast_node_right (T := T) pS)

/-- At the root, a strategy other than `stop` only evaluates `g` at pairs other than `(S, T)`. -/
lemma val_le_root (g : Tree α → Tree α → ℝ) (s : Strat) (hs : s ≠ stop) (S T : Tree α)
    (pS : S.Phylo) (pT : T.Phylo)
    (hg : ∀ U ∈ S.subtrees, ∀ V ∈ T.subtrees, (U ≠ S ∨ V ≠ T) → g U V ≤ mast U V) :
    val g s S T ≤ mast S T := by
  cases s with
  | stop => exact absurd rfl hs
  | both cr s₁ s₂ =>
    cases S with
    | leaf x => cases cr <;> simp [val]
    | node l r =>
      cases T with
      | leaf x => cases cr <;> simp [val]
      | node l' r' =>
        obtain ⟨pl, pr, _⟩ := phylo_node.1 pS
        obtain ⟨pl', pr', _⟩ := phylo_node.1 pT
        cases cr
        · have := mast_node_node pS pT
          have h₁ := val_le g s₁ l l' pl pl' fun U hU V hV =>
            hg U (sub_left hU) V (sub_left hV) (Or.inl (ne_of_mem_left hU))
          have h₂ := val_le g s₂ r r' pr pr' fun U hU V hV =>
            hg U (sub_right hU) V (sub_right hV) (Or.inl (ne_of_mem_right hU))
          simp only [val]; exact (add_le_add h₁ h₂).trans (by exact_mod_cast this)
        · have := mast_node_cross pS pT
          have h₁ := val_le g s₁ l r' pl pr' fun U hU V hV =>
            hg U (sub_left hU) V (sub_right hV) (Or.inl (ne_of_mem_left hU))
          have h₂ := val_le g s₂ r l' pr pl' fun U hU V hV =>
            hg U (sub_right hU) V (sub_left hV) (Or.inl (ne_of_mem_right hU))
          simp only [val]; exact (add_le_add h₁ h₂).trans (by exact_mod_cast this)
  | sideT b s =>
    cases T with
    | leaf x => cases b <;> simp [val]
    | node l' r' =>
      obtain ⟨pl', pr', _⟩ := phylo_node.1 pT
      cases b
      · have : mast S l' ≤ mast S (node l' r') := by
          rw [mast_comm, mast_comm S]; exact mast_node_left pT
        have h := val_le g s S l' pS pl' fun U hU V hV =>
          hg U hU V (sub_left hV) (Or.inr (ne_of_mem_left hV))
        simp only [val]; exact h.trans (by exact_mod_cast this)
      · have : mast S r' ≤ mast S (node l' r') := by
          rw [mast_comm, mast_comm S]; exact mast_node_right pT
        have h := val_le g s S r' pS pr' fun U hU V hV =>
          hg U hU V (sub_right hV) (Or.inr (ne_of_mem_right hV))
        simp only [val]; exact h.trans (by exact_mod_cast this)
  | sideS b s =>
    cases S with
    | leaf x => cases b <;> simp [val]
    | node l r =>
      obtain ⟨pl, pr, _⟩ := phylo_node.1 pS
      cases b
      · have h := val_le g s l T pl pT fun U hU V hV =>
          hg U (sub_left hU) V hV (Or.inl (ne_of_mem_left hU))
        simp only [val]; exact h.trans (by exact_mod_cast mast_node_left (T := T) pS)
      · have h := val_le g s r T pr pT fun U hU V hV =>
          hg U (sub_right hU) V hV (Or.inl (ne_of_mem_right hU))
        simp only [val]; exact h.trans (by exact_mod_cast mast_node_right (T := T) pS)

/-! ## The value `φ_s` on overlap counts -/

/-- `φ_s` at the pair of addresses `(u, v)`, for overlaps `L`: each stopped pair `(u', v')`
contributes `2^(c(|u'|+|v'|)) L(u', v')^a`. -/
noncomputable def phi (a c : ℝ) (L : List Bool → List Bool → ℝ) :
    Strat → List Bool → List Bool → ℝ
  | stop, u, v => (2 : ℝ) ^ (c * ((u.length : ℝ) + v.length)) * L u v ^ a
  | both false s₁ s₂, u, v =>
    phi a c L s₁ (u ++ [false]) (v ++ [false]) + phi a c L s₂ (u ++ [true]) (v ++ [true])
  | both true s₁ s₂, u, v =>
    phi a c L s₁ (u ++ [false]) (v ++ [true]) + phi a c L s₂ (u ++ [true]) (v ++ [false])
  | sideT b s, u, v => phi a c L s u (v ++ [b])
  | sideS b s, u, v => phi a c L s (u ++ [b]) v

lemma phi_nonneg (a c : ℝ) {L : List Bool → List Bool → ℝ} (hL : ∀ u v, 0 ≤ L u v) :
    ∀ s u v, 0 ≤ phi a c L s u v := by
  intro s
  induction s with
  | stop => intro u v; simp only [phi]; have := hL u v; positivity
  | both cr s₁ s₂ ih₁ ih₂ =>
    intro u v; cases cr <;> simp only [phi] <;> exact add_nonneg (ih₁ _ _) (ih₂ _ _)
  | sideT b s ih => intro u v; exact ih _ _
  | sideS b s ih => intro u v; exact ih _ _

lemma phi_smul (a c : ℝ) {L : List Bool → List Bool → ℝ} (hL : ∀ u v, 0 ≤ L u v) {t : ℝ}
    (ht : 0 ≤ t) : ∀ s u v, phi a c (fun u v => t * L u v) s u v = t ^ a * phi a c L s u v := by
  intro s
  induction s with
  | stop => intro u v; simp only [phi]; rw [Real.mul_rpow ht (hL u v)]; ring
  | both cr s₁ s₂ ih₁ ih₂ => intro u v; cases cr <;> simp only [phi, ih₁, ih₂] <;> ring
  | sideT b s ih => intro u v; exact ih _ _
  | sideS b s ih => intro u v; exact ih _ _

/-- `φ_s` reads `L` only at addresses within the expanded levels. -/
lemma phi_congr (a c : ℝ) {L L' : List Bool → List Bool → ℝ} :
    ∀ (s : Strat) (dS dT : ℕ) (u v : List Bool), s.Fits dS dT = true →
      (∀ u' v' : List Bool, u'.length ≤ u.length + dS → v'.length ≤ v.length + dT →
        L u' v' = L' u' v') → phi a c L s u v = phi a c L' s u v := by
  intro s
  induction s with
  | stop => intro dS dT u v _ h; simp only [phi]; rw [h u v (by omega) (by omega)]
  | both cr s₁ s₂ ih₁ ih₂ =>
    intro dS dT u v hf h
    simp only [Fits, Bool.and_eq_true, decide_eq_true_eq] at hf
    obtain ⟨⟨⟨h1, h2⟩, f₁⟩, f₂⟩ := hf
    cases cr <;> simp only [phi] <;>
      exact congrArg₂ (· + ·)
        (ih₁ _ _ _ _ f₁ fun u' v' hu hv => h u' v' (by simp at hu; omega) (by simp at hv; omega))
        (ih₂ _ _ _ _ f₂ fun u' v' hu hv => h u' v' (by simp at hu; omega) (by simp at hv; omega))
  | sideT b s ih =>
    intro dS dT u v hf h
    simp only [Fits, Bool.and_eq_true, decide_eq_true_eq] at hf
    exact ih _ _ _ _ hf.2 fun u' v' hu hv => h u' v' (by omega) (by simp at hv; omega)
  | sideS b s ih =>
    intro dS dT u v hf h
    simp only [Fits, Bool.and_eq_true, decide_eq_true_eq] at hf
    exact ih _ _ _ _ hf.2 fun u' v' hu hv => h u' v' (by simp at hu; omega) (by omega)

/-! ## `val = K φ` -/

/-- The ansatz `t^a 2^(-c(h₁+h₂))` at a pair of trees. -/
noncomputable def ans (a c : ℝ) (U V : Tree α) : ℝ :=
  tt U V ^ a * (2 : ℝ) ^ (-(c * ((ht U : ℝ) + ht V)))

lemma val_eq_phi (a c : ℝ) {h₁ h₂ : ℕ} {S T : Tree α} (hS : Bal h₁ S) (hT : Bal h₂ T) :
    ∀ (s : Strat) (dS dT : ℕ) (u v : List Bool), s.Fits dS dT = true →
      u.length + dS ≤ h₁ → v.length + dT ≤ h₂ →
      val (ans a c) s (sub S u) (sub T v) =
        (2 : ℝ) ^ (-(c * ((h₁ : ℝ) + h₂))) *
          phi a c (fun u v => tt (sub S u) (sub T v)) s u v := by
  intro s
  induction s with
  | stop =>
    intro dS dT u v _ hu hv
    simp only [val, phi, ans]
    rw [(hS.bal_sub u (by omega)).ht_eq, (hT.bal_sub v (by omega)).ht_eq,
      Nat.cast_sub (by omega), Nat.cast_sub (by omega)]
    rw [show -(c * ((h₁ : ℝ) - u.length + (h₂ - v.length))) =
      -(c * ((h₁ : ℝ) + h₂)) + c * ((u.length : ℝ) + v.length) by ring,
      Real.rpow_add (by norm_num)]
    ring
  | both cr s₁ s₂ ih₁ ih₂ =>
    intro dS dT u v hf hu hv
    simp only [Fits, Bool.and_eq_true, decide_eq_true_eq] at hf
    obtain ⟨⟨⟨h1, h2⟩, f₁⟩, f₂⟩ := hf
    rw [hS.sub_node u (by omega), hT.sub_node v (by omega)]
    cases cr
    · simp only [val, phi]
      rw [ih₁ (dS - 1) (dT - 1) (u ++ [false]) (v ++ [false]) f₁ (by simp; omega) (by simp; omega),
        ih₂ (dS - 1) (dT - 1) (u ++ [true]) (v ++ [true]) f₂ (by simp; omega) (by simp; omega)]
      ring
    · simp only [val, phi]
      rw [ih₁ (dS - 1) (dT - 1) (u ++ [false]) (v ++ [true]) f₁ (by simp; omega) (by simp; omega),
        ih₂ (dS - 1) (dT - 1) (u ++ [true]) (v ++ [false]) f₂ (by simp; omega) (by simp; omega)]
      ring
  | sideT b s ih =>
    intro dS dT u v hf hu hv
    simp only [Fits, Bool.and_eq_true, decide_eq_true_eq] at hf
    rw [hT.sub_node v (by omega)]
    cases b <;> simp only [val, phi] <;> exact ih _ _ _ _ hf.2 (by omega) (by simp; omega)
  | sideS b s ih =>
    intro dS dT u v hf hu hv
    simp only [Fits, Bool.and_eq_true, decide_eq_true_eq] at hf
    rw [hS.sub_node u (by omega)]
    cases b <;> simp only [val, phi] <;> exact ih _ _ _ _ hf.2 (by simp; omega) (by omega)

end Strat

/-! ## The inequality of Lemma 5.3 -/

open Strat

/-- The 42 strategies of the (2,1) lookahead, in the certifier's order. -/
def strategies21 : List Strat :=
  [(Strat.both false Strat.stop Strat.stop),
   (Strat.both false Strat.stop (Strat.sideS false Strat.stop)),
   (Strat.both false Strat.stop (Strat.sideS true Strat.stop)),
   (Strat.both false (Strat.sideS false Strat.stop) Strat.stop),
   (Strat.both false (Strat.sideS false Strat.stop) (Strat.sideS false Strat.stop)),
   (Strat.both false (Strat.sideS false Strat.stop) (Strat.sideS true Strat.stop)),
   (Strat.both false (Strat.sideS true Strat.stop) Strat.stop),
   (Strat.both false (Strat.sideS true Strat.stop) (Strat.sideS false Strat.stop)),
   (Strat.both false (Strat.sideS true Strat.stop) (Strat.sideS true Strat.stop)),
   (Strat.both true Strat.stop Strat.stop),
   (Strat.both true Strat.stop (Strat.sideS false Strat.stop)),
   (Strat.both true Strat.stop (Strat.sideS true Strat.stop)),
   (Strat.both true (Strat.sideS false Strat.stop) Strat.stop),
   (Strat.both true (Strat.sideS false Strat.stop) (Strat.sideS false Strat.stop)),
   (Strat.both true (Strat.sideS false Strat.stop) (Strat.sideS true Strat.stop)),
   (Strat.both true (Strat.sideS true Strat.stop) Strat.stop),
   (Strat.both true (Strat.sideS true Strat.stop) (Strat.sideS false Strat.stop)),
   (Strat.both true (Strat.sideS true Strat.stop) (Strat.sideS true Strat.stop)),
   (Strat.sideT false Strat.stop),
   (Strat.sideT false (Strat.sideS false Strat.stop)),
   (Strat.sideT false (Strat.sideS false (Strat.sideS false Strat.stop))),
   (Strat.sideT false (Strat.sideS false (Strat.sideS true Strat.stop))),
   (Strat.sideT false (Strat.sideS true Strat.stop)),
   (Strat.sideT false (Strat.sideS true (Strat.sideS false Strat.stop))),
   (Strat.sideT false (Strat.sideS true (Strat.sideS true Strat.stop))),
   (Strat.sideT true Strat.stop),
   (Strat.sideT true (Strat.sideS false Strat.stop)),
   (Strat.sideT true (Strat.sideS false (Strat.sideS false Strat.stop))),
   (Strat.sideT true (Strat.sideS false (Strat.sideS true Strat.stop))),
   (Strat.sideT true (Strat.sideS true Strat.stop)),
   (Strat.sideT true (Strat.sideS true (Strat.sideS false Strat.stop))),
   (Strat.sideT true (Strat.sideS true (Strat.sideS true Strat.stop))),
   (Strat.sideS false Strat.stop),
   (Strat.sideS false (Strat.both false Strat.stop Strat.stop)),
   (Strat.sideS false (Strat.both true Strat.stop Strat.stop)),
   (Strat.sideS false (Strat.sideS false Strat.stop)),
   (Strat.sideS false (Strat.sideS true Strat.stop)),
   (Strat.sideS true Strat.stop),
   (Strat.sideS true (Strat.both false Strat.stop Strat.stop)),
   (Strat.sideS true (Strat.both true Strat.stop Strat.stop)),
   (Strat.sideS true (Strat.sideS false Strat.stop)),
   (Strat.sideS true (Strat.sideS true Strat.stop))]

lemma strategies21_fit : ∀ s ∈ strategies21, s.Fits 2 1 = true ∧ s ≠ Strat.stop := by
  decide

/-- The leaf `p` of the two-level expansion of `S`, as an address. -/
def bitsS (p : Fin 4) : List Bool := [decide (2 ≤ p.val), decide (p.val % 2 = 1)]

/-- The leaf `q` of the one-level expansion of `T`, as an address. -/
def bitsT (q : Fin 2) : List Bool := [decide (q.val = 1)]

/-- `L_{uv}(y)`: the sum of `y_{pq}` over the leaves `p` below `u` and `q` below `v`. -/
noncomputable def Ly (y : Fin 4 → Fin 2 → ℝ) (u v : List Bool) : ℝ :=
  ∑ p : Fin 4, ∑ q : Fin 2, if u <+: bitsS p ∧ v <+: bitsT q then y p q else 0

/-- **The inequality of Lemma 5.3**: on the simplex `Δ₈`, some strategy has `φ_s ≥ 1`. -/
def CertTwo (a c : ℝ) : Prop :=
  ∀ y : Fin 4 → Fin 2 → ℝ, (∀ p q, 0 ≤ y p q) → ∑ p, ∑ q, y p q = 1 →
    ∃ s ∈ strategies21, 1 ≤ phi a c (Ly y) s [] []

lemma Ly_nonneg {y : Fin 4 → Fin 2 → ℝ} (hy : ∀ p q, 0 ≤ y p q) (u v : List Bool) :
    0 ≤ Ly y u v :=
  Finset.sum_nonneg fun p _ => Finset.sum_nonneg fun q _ => by split_ifs <;> simp [hy]

lemma Ly_smul (y : Fin 4 → Fin 2 → ℝ) (t : ℝ) (u v : List Bool) :
    Ly (fun p q => t * y p q) u v = t * Ly y u v := by
  simp only [Ly, Finset.mul_sum, mul_ite, mul_zero]

/-- Lemma 5.3, scaled to any nonnegative `y`. -/
lemma CertTwo.scaled {a c : ℝ} (ha : 0 < a) (h : CertTwo a c) {y : Fin 4 → Fin 2 → ℝ}
    (hy : ∀ p q, 0 ≤ y p q) :
    ∃ s ∈ strategies21, (∑ p, ∑ q, y p q) ^ a ≤ phi a c (Ly y) s [] [] := by
  set t := ∑ p, ∑ q, y p q
  have ht0 : 0 ≤ t := Finset.sum_nonneg fun p _ => Finset.sum_nonneg fun q _ => hy p q
  rcases ht0.eq_or_lt with ht | ht
  · refine ⟨_, List.mem_cons_self .., ?_⟩
    rw [← ht, Real.zero_rpow ha.ne']
    exact phi_nonneg a c (Ly_nonneg hy) _ _ _
  · obtain ⟨s, hs, h1⟩ := h (fun p q => y p q / t) (fun p q => div_nonneg (hy p q) ht.le)
      (by simp only [← Finset.sum_div]; exact div_self ht.ne')
    refine ⟨s, hs, ?_⟩
    have e : Ly y = fun u v => t * Ly (fun p q => y p q / t) u v := by
      funext u v; rw [← Ly_smul]; congr; funext p q; field_simp
    rw [e, phi_smul a c (Ly_nonneg fun p q => div_nonneg (hy p q) ht.le) ht0]
    exact le_mul_of_one_le_right (Real.rpow_nonneg ht0 a) h1

/-! ## The two-level induction -/

variable {α : Type*} [DecidableEq α]

/-- The overlaps of the two-level expansion are the sums `L_{uv}` of the eight cell overlaps. -/
lemma tt_sub_eq_Ly {S T : Tree α} {h₁ h₂ : ℕ} (hS : Bal (h₁ + 2) S) (hT : Bal (h₂ + 1) T)
    (pS : S.Phylo) (pT : T.Phylo) (u v : List Bool) (hu : u.length ≤ 2) (hv : v.length ≤ 1) :
    tt (sub S u) (sub T v) = Ly (fun p q => tt (sub S (bitsS p)) (sub T (bitsT q))) u v := by
  obtain ⟨l, r, rfl, hl, hr⟩ := hS.eq_node
  obtain ⟨A, B, rfl, -, -⟩ := hl.eq_node
  obtain ⟨C, D, rfl, -, -⟩ := hr.eq_node
  obtain ⟨E, F, rfl, -, -⟩ := hT.eq_node
  obtain ⟨pAB, pCD, _⟩ := phylo_node.1 pS
  rcases u with _ | ⟨b₁, _ | ⟨b₂, _ | ⟨b₃, u⟩⟩⟩ <;> simp at hu <;>
  rcases v with _ | ⟨d₁, _ | ⟨d₂, v⟩⟩ <;> simp at hv <;>
  (try cases b₁) <;> (try cases b₂) <;> (try cases d₁) <;>
  simp [sub, Ly, Fin.sum_univ_four, Fin.sum_univ_two, bitsS, bitsT, tt_node_left _ _ _ pS,
    tt_node_left _ _ _ pAB, tt_node_left _ _ _ pCD, tt_node_right _ _ _ pT] <;> ring

/-- **The two-level induction** (proof of Theorem 1.1(3), for any `(a, c)` with `CertTwo a c`). -/
theorem ansatz_two {a c : ℝ} (ha : 0 < a) (ha1 : a ≤ 1) (hc : 0 ≤ c) (hcert : CertTwo a c) :
    ∀ n h₁ h₂ (S T : Tree α), h₁ + h₂ = n → Bal h₁ S → Bal h₂ T → S.Phylo → T.Phylo →
      tt S T ^ a * (2 : ℝ) ^ (-(c * ((h₁ : ℝ) + h₂))) ≤ mast S T := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
  have hK1 : ∀ h₁ h₂ : ℕ, (2 : ℝ) ^ (-(c * ((h₁ : ℝ) + h₂))) ≤ 1 := fun h₁ h₂ =>
    Real.rpow_le_one_of_one_le_of_nonpos (by norm_num)
      (by have : (0 : ℝ) ≤ c * ((h₁ : ℝ) + h₂) := by positivity
          linarith)
  -- a tree with at most two leaves: every common label set agrees
  have small : ∀ (h₁ h₂ : ℕ) (S T : Tree α), (S.L ∩ T.L).card ≤ 2 →
      tt S T ^ a * (2 : ℝ) ^ (-(c * ((h₁ : ℝ) + h₂))) ≤ mast S T := by
    intro h₁ h₂ S T h2
    have hm : (S.L ∩ T.L).card ≤ mast S T := le_mast (agree_of_card_le_two le_rfl h2)
    rcases Nat.eq_zero_or_pos (S.L ∩ T.L).card with h0 | hpos
    · simp [tt, h0, Real.zero_rpow ha.ne']
    · have h1 : (1 : ℝ) ≤ tt S T := by unfold tt; exact_mod_cast hpos
      calc tt S T ^ a * (2 : ℝ) ^ (-(c * ((h₁ : ℝ) + h₂))) ≤ tt S T ^ a * 1 :=
            mul_le_mul_of_nonneg_left (hK1 h₁ h₂) (Real.rpow_nonneg (tt_nonneg _ _) a)
        _ ≤ tt S T ^ (1 : ℝ) := by
            rw [mul_one]; exact Real.rpow_le_rpow_of_exponent_le h1 ha1
        _ ≤ mast S T := by rw [Real.rpow_one, tt]; exact_mod_cast hm
  -- the step, for `h₂ ≤ h₁`
  have step : ∀ h₁ h₂ (S T : Tree α), h₁ + h₂ = n → h₂ ≤ h₁ → Bal h₁ S → Bal h₂ T →
      S.Phylo → T.Phylo → tt S T ^ a * (2 : ℝ) ^ (-(c * ((h₁ : ℝ) + h₂))) ≤ mast S T := by
    intro h₁ h₂ S T hn hle hS hT pS pT
    by_cases hb : h₁ ≤ 1 ∨ h₂ = 0
    · refine small h₁ h₂ S T ?_
      rcases hb with hb | hb
      · exact (Finset.card_le_card Finset.inter_subset_left).trans
          (by rw [hS.card_L pS]; exact (Nat.pow_le_pow_right (by norm_num) hb).trans (by norm_num))
      · subst hb; obtain ⟨x, rfl⟩ := hT.eq_leaf
        exact (Finset.card_le_card Finset.inter_subset_right).trans (by simp)
    push_neg at hb
    obtain ⟨k₁, rfl⟩ : ∃ k, h₁ = k + 2 := ⟨h₁ - 2, by omega⟩
    obtain ⟨k₂, rfl⟩ : ∃ k, h₂ = k + 1 := ⟨h₂ - 1, by omega⟩
    set y : Fin 4 → Fin 2 → ℝ := fun p q => tt (sub S (bitsS p)) (sub T (bitsT q))
    have hy : ∀ p q, 0 ≤ y p q := fun p q => tt_nonneg _ _
    have htot : ∑ p, ∑ q, y p q = tt S T := by
      have := tt_sub_eq_Ly hS hT pS pT [] [] (by simp) (by simp)
      simpa [Ly, sub] using this.symm
    obtain ⟨s, hs, hle'⟩ := hcert.scaled ha hy
    rw [htot] at hle'
    obtain ⟨hfit, hstop⟩ := strategies21_fit s hs
    have hphi : phi a c (Ly y) s [] [] = phi a c (fun u v => tt (sub S u) (sub T v)) s [] [] :=
      phi_congr a c s 2 1 [] [] hfit fun u' v' hu hv =>
        (tt_sub_eq_Ly hS hT pS pT u' v' (by simpa using hu) (by simpa using hv)).symm
    have hval := val_eq_phi a c hS hT s 2 1 [] [] hfit (by simp) (by simp)
    simp only [sub] at hval
    have hroot := val_le_root (ans a c) s hstop S T pS pT fun U hU V hV hne => by
      obtain ⟨bU, ltU⟩ := hS.of_mem_subtrees hU
      obtain ⟨bV, ltV⟩ := hT.of_mem_subtrees hV
      have leU : ht U ≤ k₁ + 2 := by
        by_cases e : U = S
        · rw [e, hS.ht_eq]
        · exact (ltU e).le
      have leV : ht V ≤ k₂ + 1 := by
        by_cases e : V = T
        · rw [e, hT.ht_eq]
        · exact (ltV e).le
      have hlt : ht U + ht V < n := by
        rcases hne with e | e
        · have := ltU e; omega
        · have := ltV e; omega
      exact ih _ hlt _ _ U V rfl bU bV (phylo_of_mem_subtrees pS hU)
        (phylo_of_mem_subtrees pT hV)
    rw [hval, ← hphi] at hroot
    calc tt S T ^ a * (2 : ℝ) ^ (-(c * (((k₁ + 2 : ℕ) : ℝ) + ((k₂ + 1 : ℕ) : ℝ))))
        ≤ phi a c (Ly y) s [] [] * (2 : ℝ) ^ (-(c * (((k₁ + 2 : ℕ) : ℝ) + ((k₂ + 1 : ℕ) : ℝ)))) :=
          mul_le_mul_of_nonneg_right hle' (Real.rpow_nonneg (by norm_num) _)
      _ = _ := mul_comm _ _
      _ ≤ mast S T := hroot
  intro h₁ h₂ S T hn hS hT pS pT
  rcases le_total h₂ h₁ with hle | hle
  · exact step h₁ h₂ S T hn hle hS hT pS pT
  · have := step h₂ h₁ T S (by omega) hle hT hS pT pS
    rw [mast_comm]
    have e : tt T S = tt S T := by simp [tt, Finset.inter_comm]
    rwa [e, add_comm (h₂ : ℝ)] at this

/-- `M(2^m) ≥ 2^(m(a - 2c))` from the two-level inequality. -/
theorem M_lower_of_certTwo {a c : ℝ} (ha : 0 < a) (ha1 : a ≤ 1) (hc : 0 ≤ c)
    (hcert : CertTwo a c) (m : ℕ) : (2 : ℝ) ^ ((m : ℝ) * (a - 2 * c)) ≤ M m := by
  obtain ⟨S, T, hS, hT, pS, pT, hL, hm⟩ := M_mem m
  have := ansatz_two ha ha1 hc hcert _ m m S T rfl hS hT pS pT
  rw [← hm]
  have ht : tt S T = (2 : ℝ) ^ (m : ℝ) := by
    rw [tt, ← hL, Finset.inter_self, hS.card_L pS, Real.rpow_natCast]; push_cast; ring
  rw [ht, ← Real.rpow_mul (by norm_num), ← Real.rpow_add (by norm_num)] at this
  convert this using 2; ring

/-- **Theorem 1.1(3)**, given the certified inequality of Lemma 5.3:
`M(n) ≥ n^0.243` for `n = 2^m`. -/
theorem M_lower (hcert : CertTwo (2 / 5) (157 / 2000)) (m : ℕ) :
    (2 : ℝ) ^ ((m : ℝ) * (243 / 1000)) ≤ M m := by
  have := M_lower_of_certTwo (by norm_num) (by norm_num) (by norm_num) hcert m
  convert this using 3; norm_num

end BalancedMast
