#!/usr/bin/env python3
"""Mutation tests for EnclosingCopy/Enclosing (MO 458571): every wrong variant must FAIL to check.

Each mutant copies one file to Enclosing/Mut.lean with a single textual change and compiles it
with `lake env lean` (single process, nice 15). Unmutated copies must pass (baseline).
"""
import subprocess, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
D = ROOT / "EnclosingCopy" / "Enclosing"
MUT = D / "Mut.lean"

MUTANTS = [
    ("identity (1c): 1/2 -> 1/3", "Polygon.lean",
     "    ∑ i, len v i * bEnd v i = (1 / 2) * ∑ i, len v i ^ 2 := by",
     "    ∑ i, len v i * bEnd v i = (1 / 3) * ∑ i, len v i ^ 2 := by"),
    ("identity (1b): 2 area -> area", "Polygon.lean",
     "    ∑ i, len v i * hsup v i = 2 * area v := by",
     "    ∑ i, len v i * hsup v i = area v := by"),
    ("Lemma 7: -2 eps area -> -eps area", "Void.lean",
     "      = -(2 * ε * area v) := by", "      = -(ε * area v) := by"),
    ("Lemma 7: event min -> max", "Void.lean",
     "    (hE : ∀ i, Hcopy v ε C i ≤ min (Θ * aEnd v i) (Θ * bEnd v i)) :",
     "    (hE : ∀ i, Hcopy v ε C i ≤ max (Θ * aEnd v i) (Θ * bEnd v i)) :"),
    ("KKT strict -> weak", "Segment.lean",
     "        μ₁ * s₁ + μ₂ * s₂ + μ₃ * s₃ = 0) ↔ s₁ < -s₃ ∧ -s₃ < s₂ := by",
     "        μ₁ * s₁ + μ₂ * s₂ + μ₃ * s₃ = 0) ↔ s₁ < -s₃ ∧ -s₃ ≤ s₂ := by"),
    ("sigma inner 1/2 -> 1/3", "Segment.lean",
     "    ∫ s₁ in a..x, ∫ s₂ in x..b, (s₂ - s₁) = (1 / 2) * (x - a) * (b - x) * (b - a) := by",
     "    ∫ s₁ in a..x, ∫ s₂ in x..b, (s₂ - s₁) = (1 / 3) * (x - a) * (b - x) * (b - a) := by"),
    ("sigma regular 4/3 -> 3/2", "Segment.lean",
     "    ∫ x in (-1 : ℝ)..1, ∫ s₁ in (-1 : ℝ)..x, ∫ s₂ in x..1, (s₂ - s₁) = 4 / 3 := by",
     "    ∫ x in (-1 : ℝ)..1, ∫ s₁ in (-1 : ℝ)..x, ∫ s₂ in x..1, (s₂ - s₁) = 3 / 2 := by"),
    ("segment prob: |Y_E| -> beta", "Segment.lean",
     "    F α * G α + ∫ y in α..β, G y * deriv F y = K₀ * (1 + S * (β - α)) := by",
     "    F α * G α + ∫ y in α..β, G y * deriv F y = K₀ * (1 + S * β) := by"),
    ("area factor 1/(4q^4) -> 1/(4q^3)", "Regular.lean",
     "    ∫ Θ, ∫ t in Ioi |Θ|, exp (-(2 * q * t)) * (t - |Θ|) ^ 2 = 1 / (4 * q ^ 4) := by",
     "    ∫ Θ, ∫ t in Ioi |Θ|, exp (-(2 * q * t)) * (t - |Θ|) ^ 2 = 1 / (4 * q ^ 3) := by"),
    ("cot sum: cos/sin -> sin/cos", "Regular.lean",
     "    ∑ j ∈ Finset.Ico 1 r, sin (π * j / r) = cos (π / (2 * r)) / sin (π / (2 * r)) := by",
     "    ∑ j ∈ Finset.Ico 1 r, sin (π * j / r) = sin (π / (2 * r)) / cos (π / (2 * r)) := by"),
    ("segment term 8/(3q^2) -> 8/(3q^3)", "Regular.lean",
     "      = 8 / (3 * q ^ 2) := by", "      = 8 / (3 * q ^ 3) := by"),
    ("square area 4 -> 2", "RegularGeom.lean",
     "theorem volume_P_four : volume (Preg 4) = 4 := by",
     "theorem volume_P_four : volume (Preg 4) = 2 := by"),
    ("width: drop the lower half", "RegularGeom.lean",
     "    (fun C : ℝ × ℝ => C.1) '' Rreg (2 * r) t Θ = Icc (-(t - |Θ|)) (t - |Θ|) := by",
     "    (fun C : ℝ × ℝ => C.1) '' Rreg (2 * r) t Θ = Icc 0 (t - |Θ|) := by"),
    ("V regular 4 q^4 -> 2 q^4", "RegularGeom.lean",
     "      = (volume (Preg q)).toReal / (4 * (q : ℝ) ^ 4) := by",
     "      = (volume (Preg q)).toReal / (2 * (q : ℝ) ^ 4) := by"),
    ("square segment term 1/6 -> 1/4", "RegularGeom.lean",
     "      = 1 / 6 := by\n  have h := segment_term_measure",
     "      = 1 / 4 := by\n  have h := segment_term_measure"),
    ("theta-height: drop Q", "TriangleDeriv.lean",
     "        (∫ H in Iic (Θ * a₃), exp (L₃ * H)) = 1 / (Q * L₁ * L₂ * L₃) := by",
     "        (∫ H in Iic (Θ * a₃), exp (L₃ * H)) = 1 / (L₁ * L₂ * L₃) := by"),
    ("I_k: /8 -> /4", "TriangleDeriv.lean",
     "      = Li * Lj * Lk * Lk ^ 2 * gfun (Li ^ 2 / Lk ^ 2) (Lj ^ 2 / Lk ^ 2) / 8 := by",
     "      = Li * Lj * Lk * Lk ^ 2 * gfun (Li ^ 2 / Lk ^ 2) (Lj ^ 2 / Lk ^ 2) / 4 := by"),
    ("assembly: Q = sum/2 -> sum", "TriangleDeriv.lean",
     "    let Q := (L₁ ^ 2 + L₂ ^ 2 + L₃ ^ 2) / 2", "    let Q := (L₁ ^ 2 + L₂ ^ 2 + L₃ ^ 2)"),
    ("g closed form: 2ab -> ab", "Triangle.lean",
     "    gfun α β = (Phi (α + β) - Phi (α - β)) / (2 * α * β) := by",
     "    gfun α β = (Phi (α + β) - Phi (α - β)) / (α * β) := by"),
    ("equilateral 13/48 -> 1/2 (the asker's guess)", "Triangle.lean",
     "theorem p_equilateral : ptri 1 1 1 = 13 / 48 := by",
     "theorem p_equilateral : ptri 1 1 1 = 1 / 2 := by"),
    ("30-60-90: 29/96 -> 5/16", "Triangle.lean",
     "theorem p_30_60_90 : ptri 1 3 4 = 29 / 96 := by",
     "theorem p_30_60_90 : ptri 1 3 4 = 5 / 16 := by"),
    ("flat isosceles 25/72 -> 1/3", "Triangle.lean",
     "    Filter.Tendsto (fun c => ptri 1 1 c) (nhds 4) (nhds (25 / 72)) := by",
     "    Filter.Tendsto (fun c => ptri 1 1 c) (nhds 4) (nhds (1 / 3)) := by"),
    ("thin right 1/3 -> 1/2", "Triangle.lean",
     "    Filter.Tendsto (fun c => ptri 1 c (1 + c)) (nhdsWithin 0 (Set.Ioi 0)) (nhds (1 / 3)) := by",
     "    Filter.Tendsto (fun c => ptri 1 c (1 + c)) (nhdsWithin 0 (Set.Ioi 0)) (nhds (1 / 2)) := by"),
    ("regular area: tan -> sin", "RegularArea.lean",
     "    volume (Preg q) = ENNReal.ofReal (q * tan (π / q)) := by",
     "    volume (Preg q) = ENNReal.ofReal (q * sin (π / q)) := by"),
    ("key inequality: half-period pi/q -> 2pi/q", "RegularArea.lean",
     "lemma cos_le_cos_on_period (hq : 2 ≤ q) {θ : ℝ} (hθ : |θ| ≤ π / q) (j : Fin q) :",
     "lemma cos_le_cos_on_period (hq : 2 ≤ q) {θ : ℝ} (hθ : |θ| ≤ 2 * π / q) (j : Fin q) :"),
    ("radial: 1/(2M^2) -> 1/M^2", "RegularArea.lean",
     "      = ENNReal.ofReal (1 / (2 * Mq q θ ^ 2)) := by",
     "      = ENNReal.ofReal (1 / (Mq q θ ^ 2)) := by"),
    ("vertex integral tan/(4q^3) -> tan/(4q^4)", "RegularArea.lean",
     "      = q * tan (π / q) / (4 * (q : ℝ) ^ 4) := by",
     "      = q * tan (π / q) / (4 * (q : ℝ) ^ 5) := by"),
    ("square det 2(A-B) -> (A-B)", "SquareVertex.lean",
     "lemma det_id (σ : Fin 4 → ℝ) : (Amat id σ).det = 2 * ((σ 0 + σ 2) - (σ 1 + σ 3)) := by",
     "lemma det_id (σ : Fin 4 → ℝ) : (Amat id σ).det = ((σ 0 + σ 2) - (σ 1 + σ 3)) := by"),
    ("square KKT: drop the A = B = 0 case", "SquareVertex.lean",
     "    KKT id σ ↔ (σ 0 + σ 2) * (σ 1 + σ 3) < 0 ∨ (σ 0 + σ 2 = 0 ∧ σ 1 + σ 3 = 0) := by",
     "    KKT id σ ↔ (σ 0 + σ 2) * (σ 1 + σ 3) < 0 := by"),
    ("square pair integral 4/3 -> 1", "SquareVertex.lean",
     "lemma integral_Pp : ∫ z, Pp z ∂(nu1.prod nu1) = 4 / 3 := by",
     "lemma integral_Pp : ∫ z, Pp z ∂(nu1.prod nu1) = 1 := by"),
    ("identity tuple 64/3 -> 32/3", "SquareVertex.lean",
     "theorem integral_id : ∫ σ, integrand id σ ∂mu4 = 64 / 3 := by",
     "theorem integral_id : ∫ σ, integrand id σ ∂mu4 = 32 / 3 := by"),
    ("bijections 24 -> 23", "SquareVertex.lean",
     "    (Finset.univ.filter fun k : Fin 4 → Fin 4 => Function.Bijective k).card = 24 := by",
     "    (Finset.univ.filter fun k : Fin 4 → Fin 4 => Function.Bijective k).card = 23 := by"),
    ("p4 = 1/4 -> 1/2 (the asker's guess)", "SquareVertex.lean",
     "      = 1 / 4 := by\n  rw [V_regular_full",
     "      = 1 / 2 := by\n  rw [V_regular_full"),
    ("segment event: drop the G(alpha) factor", "SegmentProb.lean",
     "    P.real {ω | ℓ ω ≤ β ∧ α ≤ r ω ∧ ℓ ω ≤ r ω} = F α * G α + ∫ y in α..β, G y * F' y := by",
     "    P.real {ω | ℓ ω ≤ β ∧ α ≤ r ω ∧ ℓ ω ≤ r ω} = F α + ∫ y in α..β, G y * F' y := by"),
    ("segment event: drop independence", "SegmentProb.lean",
     "    (hind : IndepFun ℓ r P) {α β : ℝ} (hαβ : α ≤ β) {F G F' : ℝ → ℝ}\n    (hF : ∀ y ∈ Icc α β, P.real {ω | ℓ ω ≤ y} = F y)\n    (hG : ∀ y ∈ Icc α β, P.real {ω | y ≤ r ω} = G y)\n    (hFc : ContinuousOn F (Icc α β)) (hder : ∀ y ∈ Ioo α β, HasDerivAt F (F' y) y)\n    (hF'c : Continuous F') (hF'0 : ∀ y ∈ Icc α β, 0 ≤ F' y) :\n    P.real {ω | ℓ ω ≤ β ∧ α ≤ r ω ∧ ℓ ω ≤ r ω} = F α * G α",
     "    {α β : ℝ} (hαβ : α ≤ β) {F G F' : ℝ → ℝ}\n    (hF : ∀ y ∈ Icc α β, P.real {ω | ℓ ω ≤ y} = F y)\n    (hG : ∀ y ∈ Icc α β, P.real {ω | y ≤ r ω} = G y)\n    (hFc : ContinuousOn F (Icc α β)) (hder : ∀ y ∈ Ioo α β, HasDerivAt F (F' y) y)\n    (hF'c : Continuous F') (hF'0 : ∀ y ∈ Icc α β, 0 ≤ F' y) :\n    P.real {ω | ℓ ω ≤ β ∧ α ≤ r ω ∧ ℓ ω ≤ r ω} = F α * G α"),
    ("density: law of l equals F' -> 2F'", "SegmentProb.lean",
     "      = (volume.restrict (Ioc α β)).withDensity fun y => ENNReal.ofReal (F' y) := by",
     "      = (volume.restrict (Ioc α β)).withDensity fun y => ENNReal.ofReal (2 * F' y) := by"),
    ("vertex limit: -Theta b -> +Theta b (no corner poke)", "Linearise.lean",
     "      (𝓝 (ε * h + C₁ - Θ * b)) := by", "      (𝓝 (ε * h + C₁ + Θ * b)) := by"),
    ("point limit: +D -> -D", "Linearise.lean",
     "      (𝓝 (ε * h + C₁ - Θ * s + D)) := by", "      (𝓝 (ε * h + C₁ - Θ * s - D)) := by"),
    ("n sin(Theta/n) -> 2 Theta", "Linearise.lean",
     "lemma tendsto_n_sin (Θ : ℝ) : Tendsto (fun n : ℕ => (n : ℝ) * sin (Θ / n)) atTop (𝓝 Θ) := by",
     "lemma tendsto_n_sin (Θ : ℝ) : Tendsto (fun n : ℕ => (n : ℝ) * sin (Θ / n)) atTop (𝓝 (2 * Θ)) := by"),
    ("cone/tetrahedron: drop the 1/h scaling", "Segment.lean",
     "      (∃ w : Fin k → ℝ, (∀ r, 0 < w r) ∧ ∑ r, w r = 1 ∧ ∑ r, w r * (x r / h r) = 0 ∧",
     "      (∃ w : Fin k → ℝ, (∀ r, 0 < w r) ∧ ∑ r, w r = 1 ∧ ∑ r, w r * (x r * h r) = 0 ∧"),
    ("model: Lemma 7 exp(2 eps) -> exp(eps)", "Model.lean",
     "    PoissonPP.prob (Λ K T) (fun μ => Feasible K μ z) = ENNReal.ofReal (Real.exp (2 * z.1)) := by",
     "    PoissonPP.prob (Λ K T) (fun μ => Feasible K μ z) = ENNReal.ofReal (Real.exp z.1) := by"),
    ("model: drop the truncation hypothesis", "Model.lean",
     "    (hT : ∀ i, ∀ s ∈ Icc (K.a i) (K.b i), z.2.2 * s - Hs K z i ≤ T) :\n    PoissonPP.prob",
     "    :\n    PoissonPP.prob"),
    ("LP certificate: optimal -> strictly better", "LP.lean",
     "    (htight : ∀ r, gx K zs (x r) = 0) (z : Copy) (hz : ∀ r, 0 ≤ gx K z (x r)) :\n    zs.1 ≤ z.1 := by",
     "    (htight : ∀ r, gx K zs (x r) = 0) (z : Copy) (hz : ∀ r, 0 ≤ gx K z (x r)) :\n    zs.1 < z.1 := by"),
    ("square model: spatial factor 1/4 -> 1/3", "SquareModel.lean",
     "theorem spatial_square : spatialVertexIntegral squareSides = ENNReal.ofReal (1 / 4) := by",
     "theorem spatial_square : spatialVertexIntegral squareSides = ENNReal.ofReal (1 / 3) := by"),
    ("square model: cone factor 1/3 -> 1/2", "SquareModel.lean",
     "theorem cone_square : coneVertexDensity squareSides = ENNReal.ofReal (1 / 3) := by",
     "theorem cone_square : coneVertexDensity squareSides = ENNReal.ofReal (1 / 2) := by"),
    ("square model: half-box Jacobian 1/16 -> 1/8", "SquareModel.lean",
     "      = ENNReal.ofReal (1 / 16) * ∫⁻ σ, G σ ∂mu4 := by",
     "      = ENNReal.ofReal (1 / 8) * ∫⁻ σ, G σ ∂mu4 := by"),
    ("square model: det scaling /4 -> /2", "SquareModel.lean",
     "    (vertexMatrix squareSides (pointsOf k s 0)).det = (Amat k ((2 : ℝ) • s)).det / 4 := by",
     "    (vertexMatrix squareSides (pointsOf k s 0)).det = (Amat k ((2 : ℝ) • s)).det / 2 := by"),
    ("square model: vertex limit 1/12 -> 1/4", "SquareModel.lean",
     "      Filter.atTop (nhds (ENNReal.ofReal (1 / 12))) := by",
     "      Filter.atTop (nhds (ENNReal.ofReal (1 / 4))) := by"),
    ("segment count: Fourier-Motzkin <= -> <", "SegmentCount.lean",
     "      (∀ j, a j = 0 → 0 ≤ b j) ∧ ∀ j j', 0 < a j → a j' < 0 → b j' / a j' ≤ b j / a j := by",
     "      (∀ j, a j = 0 → 0 ≤ b j) ∧ ∀ j j', 0 < a j → a j' < 0 → b j' / a j' < b j / a j := by"),
    ("segment count: parallel sides u -> -u dropped", "SegmentCount.lean",
     "  par : K.u kb = -K.u k", "  par : K.u kb = K.u k"),
    ("segment count: KKT -s2 -> s2", "SegmentCount.lean",
     "  (x 0).1 = k ∧ (x 1).1 = k ∧ (x 2).1 = kb ∧ (x 0).2.1 < -(x 2).2.1 ∧ -(x 2).2.1 < (x 1).2.1",
     "  (x 0).1 = k ∧ (x 1).1 = k ∧ (x 2).1 = kb ∧ (x 0).2.1 < (x 2).2.1 ∧ (x 2).2.1 < (x 1).2.1"),
    ("segment count: chord weight e^{2 eps} -> e^{eps}", "SegmentCount.lean",
     "noncomputable def chordWeight (T : ℝ) (v : Fin 3 → ℝ) : ℝ≥0∞ :=\n  ENNReal.ofReal (Real.exp (2 * v 0)) *",
     "noncomputable def chordWeight (T : ℝ) (v : Fin 3 → ℝ) : ℝ≥0∞ :=\n  ENNReal.ofReal (Real.exp (v 0)) *"),
    ("segment count: drop the width term", "SegmentCount.lean",
     "    ({v | (chordSet K k T v).Nonempty}.indicator 1 v +\n      ENNReal.ofReal (slopeSum K k) * volume (chordSet K k T v))",
     "    (ENNReal.ofReal (slopeSum K k) * volume (chordSet K k T v))"),
    ("segment count: slope over the negative sides", "SegmentCount.lean",
     "  ∑ i ∈ positiveSides K (tang K k), (K.b i - K.a i) * dot (K.u i) (tang K k)",
     "  ∑ i ∈ negativeSides K (tang K k), (K.b i - K.a i) * dot (K.u i) (tang K k)"),
    ("segment count: Jacobian drops h_kbar", "SegmentCount.lean",
     "    (fun s => ENNReal.ofReal ((s 1 - s 0) * (K.h k + K.h kb))) s",
     "    (fun s => ENNReal.ofReal ((s 1 - s 0) * K.h k)) s"),
    ("square segment: max-square integral /3 -> /2", "SquareSegment.lean",
     "    ∫ x in (-1 / 2 : ℝ)..(1 / 2), (max (x - a) 0) ^ 2 = (1 / 2 - a) ^ 3 / 3 := by",
     "    ∫ x in (-1 / 2 : ℝ)..(1 / 2), (max (x - a) 0) ^ 2 = (1 / 2 - a) ^ 3 / 2 := by"),
    ("square segment: density 1/12 -> 1/6", "SquareSegment.lean",
     "theorem segDensity_square (k kb : Fin 4) : segDensity squareSides k kb = ENNReal.ofReal (1 / 12) := by",
     "theorem segDensity_square (k kb : Fin 4) : segDensity squareSides k kb = ENNReal.ofReal (1 / 6) := by"),
    ("square segment: width integral 1/4 -> 1/2", "SquareSegment.lean",
     "    ∫⁻ u in Ioi (0 : ℝ), ENNReal.ofReal (u * Real.exp (-(2 * u))) = ENNReal.ofReal (1 / 4) := by",
     "    ∫⁻ u in Ioi (0 : ℝ), ENNReal.ofReal (u * Real.exp (-(2 * u))) = ENNReal.ofReal (1 / 2) := by"),
    ("square segment: chord integral 1/2 -> 1/4", "SquareSegment.lean",
     "    ∫⁻ v, chordWeightInf squareSides k v = ENNReal.ofReal (1 / 2) := by",
     "    ∫⁻ v, chordWeightInf squareSides k v = ENNReal.ofReal (1 / 4) := by"),
    ("square segment: pair limit 1/24 -> 1/12", "SquareSegment.lean",
     "      (nhds (ENNReal.ofReal (1 / 24))) := by",
     "      (nhds (ENNReal.ofReal (1 / 12))) := by"),
    ("square segment: total 1/4 -> 1/3", "SquareSegment.lean",
     "      Filter.atTop (nhds (ENNReal.ofReal (1 / 4))) := by\n  have hv := square_vertex_candidate_limit",
     "      Filter.atTop (nhds (ENNReal.ofReal (1 / 3))) := by\n  have hv := square_vertex_candidate_limit"),
    ("square segment: pair (k, k+2) -> (k, k+1)", "SquareSegment.lean",
     "lemma squarePair (k : Fin 4) : ParPair squareSides k (k + 2) := by",
     "lemma squarePair (k : Fin 4) : ParPair squareSides k (k + 1) := by"),
    ("LP dual: Caratheodory subset reversed", "LPDual.lean",
     "    ∃ t ⊆ s, ∃ μ : ι → ℝ, LinearIndependent ℝ (fun i : t => v i) ∧ (∀ i ∈ t, 0 < μ i) ∧",
     "    ∃ t, s ⊆ t ∧ ∃ μ : ι → ℝ, LinearIndependent ℝ (fun i : t => v i) ∧ (∀ i ∈ t, 0 < μ i) ∧"),
    ("LP dual: Farkas with strict separation of the generators", "LPDual.lean",
     "    ∃ y : Fin d → ℝ, (∀ i, 0 ≤ v i ⬝ᵥ y) ∧ e ⬝ᵥ y < 0 := by",
     "    ∃ y : Fin d → ℝ, (∀ i, 0 < v i ⬝ᵥ y) ∧ e ⬝ᵥ y < 0 := by"),
    ("LP dual: KKT drops the multipliers", "LPDual.lean",
     "      LinearIndependent ℝ (fun i : t => r i) ∧ e = ∑ i ∈ t, μ i • r i := by",
     "      LinearIndependent ℝ (fun i : t => r i) ∧ e = ∑ i ∈ t, r i := by"),
    ("classification: position null set -> depth half-line", "Classification.lean",
     "theorem intensity_position_zero (T c : ℝ) : Λ K T {p : Pt m | p.2.1 = c} = 0 := by",
     "theorem intensity_position_zero (T c : ℝ) : Λ K T {p : Pt m | p.2.2 ≤ c} = 0 := by"),
    ("classification: opposite normals not negated", "Classification.lean",
     "lemma square_u_add_two (j : Fin 4) : squareSides.u (j + 2) = -squareSides.u j := by",
     "lemma square_u_add_two (j : Fin 4) : squareSides.u (j + 2) = squareSides.u j := by"),
    ("classification: segment multipliers mu_a = mu_c", "Classification.lean",
     "      (p c).1 = j + 2 ∧ (p a).2.1 < (p b).2.1 ∧ 0 < μ a ∧ 0 < μ b ∧ 0 < μ c ∧\n      μ a + μ b = μ c ∧ (μ a + μ b) * (squareSides.h j + squareSides.h (j + 2)) = 1 ∧\n      μ a * (p a).2.1 + μ b * (p b).2.1 + μ c * (p c).2.1 = 0) ∨\n    (∃ a ∈ t",
     "      (p c).1 = j + 2 ∧ (p a).2.1 < (p b).2.1 ∧ 0 < μ a ∧ 0 < μ b ∧ 0 < μ c ∧\n      μ a = μ c ∧ (μ a + μ b) * (squareSides.h j + squareSides.h (j + 2)) = 1 ∧\n      μ a * (p a).2.1 + μ b * (p b).2.1 + μ c * (p c).2.1 = 0) ∨\n    (∃ a ∈ t"),
    ("classification: null event s_a = s_b", "Classification.lean",
     "def OppP (x : Fin 1 → Pt 4) (q : Pt 4) : Prop := q.1 = (x 0).1 + 2 ∧ (x 0).2.1 + q.2.1 = 0",
     "def OppP (x : Fin 1 → Pt 4) (q : Pt 4) : Prop := q.1 = (x 0).1 + 2 ∧ (x 0).2.1 = q.2.1"),
    ("classification: perpendicular point on the parallel side", "Classification.lean",
     "    (h2 : (q 2).1 = k + 2) (h3 : (q 3).1 = k + 1) (hs : (q 0).2.1 ≠ (q 1).2.1) :",
     "    (h2 : (q 2).1 = k + 2) (h3 : (q 3).1 = k + 2) (hs : (q 0).2.1 ≠ (q 1).2.1) :"),
    ("classification: event E without the cutoff", "Classification.lean",
     "  ∃ z : Copy, Fits K z ∧ Below K T z ∧ Feasible K (PoissonPP.config ω.2) z ∧",
     "  ∃ z : Copy, Fits K z ∧ Feasible K (PoissonPP.config ω.2) z ∧"),
    ("classification: P(E) limit 1/4 -> 1/3", "Classification.lean",
     "      Filter.atTop (nhds (ENNReal.ofReal (1 / 4))) := by\n  simp_rw [square_optFit_prob]",
     "      Filter.atTop (nhds (ENNReal.ofReal (1 / 3))) := by\n  simp_rw [square_optFit_prob]"),
    ("general: unit vectors with zero cross are only equal", "GeneralClassify.lean",
     "    (h : cross u v = 0) : v = u ∨ v = -u := by",
     "    (h : cross u v = 0) : v = u := by"),
    ("general: width hypothesis weakened to >= 0", "GeneralClassify.lean",
     "  width : ∀ i j, K.u j = -K.u i → 0 < K.h i + K.h j",
     "  width : ∀ i j, K.u j = -K.u i → 0 ≤ K.h i + K.h j"),
    ("general: Tri3 relation with a wrong cross sign", "GeneralClassify.lean",
     "    cross (K.u (x 1).1) (K.u q.1) * (x 0).2.1 + cross (K.u q.1) (K.u (x 0).1) * (x 1).2.1 +",
     "    cross (K.u (x 1).1) (K.u q.1) * (x 0).2.1 + cross (K.u (x 0).1) (K.u q.1) * (x 1).2.1 +"),
    ("general: balanced unit vectors equal", "GeneralClassify.lean",
     "    (h2 : M * u.2 + N * v.2 = 0) : M = N ∧ v = -u := by",
     "    (h2 : M * u.2 + N * v.2 = 0) : M = N ∧ v = u := by"),
    ("general: Opp2 with equal positions", "GeneralClassify.lean",
     "  K.u q.1 = -K.u (x 0).1 ∧ (x 0).2.1 + q.2.1 = 0",
     "  K.u q.1 = -K.u (x 0).1 ∧ (x 0).2.1 = q.2.1"),
    ("general: perpendicular determinant with a parallel side", "GeneralClassify.lean",
     "lemma gen_perp_det {k kb k' : Fin m} (hu : K.u kb = -K.u k) (hk' : cross (K.u k) (K.u k') ≠ 0)",
     "lemma gen_perp_det {k kb k' : Fin m} (hu : K.u kb = -K.u k) (hk' : cross (K.u k) (K.u k') = 0)"),
    ("general: parallel pairs with equal normals", "GeneralClassify.lean",
     "  Finset.univ.filter fun p => K.u p.2 = -K.u p.1",
     "  Finset.univ.filter fun p => K.u p.2 = K.u p.1"),
    ("general: Theorem 8 limit without the vertex term", "GeneralClassify.lean",
     "      (nhds (spatialVertexIntegral K * coneVertexDensity K +\n        ∑ p ∈ parPairs K,",
     "      (nhds (\n        ∑ p ∈ parPairs K,"),
    ("triangle: identity (1c) sign flipped", "TriangleModel.lean",
     "lemma sum_L_a : ∑ i, sideL K i * K.a i = -Qtri K := by",
     "lemma sum_L_a : ∑ i, sideL K i * K.a i = Qtri K := by"),
    ("triangle: D3 L0 = cross (factor 2 dropped)", "TriangleModel.lean",
     "lemma D3_mul_L0 : D3 K * sideL K 0 = 2 * cross (K.u 1) (K.u 2) := by",
     "lemma D3_mul_L0 : D3 K * sideL K 0 = cross (K.u 1) (K.u 2) := by"),
    ("triangle: spatial factor 2 -> 1", "TriangleModel.lean",
     "    ∫⁻ v, fitWeight K v = ENNReal.ofReal |D3 K|⁻¹ *\n      ENNReal.ofReal (2 / (Qtri",
     "    ∫⁻ v, fitWeight K v = ENNReal.ofReal |D3 K|⁻¹ *\n      ENNReal.ofReal (1 / (Qtri"),
    ("triangle: wrong canonical tuple", "TriangleCone.lean",
     "![2, 2, 0, 1]]", "![2, 2, 0, 0]]"),
    ("triangle: class size 12 -> 11", "TriangleCone.lean",
     "sideCount (canon k)).card = 12 := by", "sideCount (canon k)).card = 11 := by"),
    ("triangle: x without the minus sign", "TriangleCone.lean",
     "  -(sideL K i * si + sideL K j * sj) / sideL K k\n", "  (sideL K i * si + sideL K j * sj) / sideL K k\n"),
    ("triangle: cone criterion with a weak inequality", "TriangleCone.lean",
     "      min (s 0) (s 1) < xpos K k i j (s 2) (s 3) ∧ xpos K k i j (s 2) (s 3) < max (s 0) (s 1) := by",
     "      min (s 0) (s 1) ≤ xpos K k i j (s 2) (s 3) ∧ xpos K k i j (s 2) (s 3) < max (s 0) (s 1) := by"),
    ("triangle: inner pair integral (b-a) -> (b-a)^2", "TriangleCone.lean",
     "      = ENNReal.ofReal ((b - a) * max 0 ((x - a) * (b - x))) := by",
     "      = ENNReal.ofReal ((b - a) ^ 2 * max 0 ((x - a) * (b - x))) := by"),
    ("triangle: tuple sum 12 -> 6", "TriangleCone.lean",
     "    ∑ κ, coneTerm K κ = ∑ k : Fin 3, 12 * coneTerm K (canon k) := by",
     "    ∑ κ, coneTerm K κ = ∑ k : Fin 3, 6 * coneTerm K (canon k) := by"),
    ("triangle: cone density with |D3| inverted", "TriangleCone.lean",
     "    coneVertexDensity K = ENNReal.ofReal (|D3 K| *",
     "    coneVertexDensity K = ENNReal.ofReal (|D3 K|⁻¹ *"),
    ("triangle: equilateral ptri 13/48 -> 13/24", "TriangleCone.lean",
     "lemma ptri_equal {c : ℝ} (hc : 0 < c) : ptri c c c = 13 / 48 := by",
     "lemma ptri_equal {c : ℝ} (hc : 0 < c) : ptri c c c = 13 / 24 := by"),
    ("triangle: equilateral limit 13/48 -> 1/4", "TriangleCone.lean",
     "      (nhds (ENNReal.ofReal (13 / 48))) := by",
     "      (nhds (ENNReal.ofReal (1 / 4))) := by"),
    ("convex: weak convex position", "ConvexPolygon.lean",
     "  ∀ i j : Fin m, j ≠ i → j ≠ i + 1 → dot (v j) (nrm v i) < hsup v i",
     "  ∀ i j : Fin m, j ≠ i → j ≠ i + 1 → dot (v j) (nrm v i) ≤ hsup v i"),
    ("convex: two vertices suffice", "ConvexPolygon.lean",
     "variable (hm : 3 ≤ m)\ninclude hm", "variable (hm : 2 ≤ m)\ninclude hm"),
    ("convex: width as a difference", "ConvexPolygon.lean",
     "    0 < hsup v i + hsup v j := by", "    0 < hsup v i - hsup v j := by"),
    ("convex: area 2 in sidesOf", "ConvexPolygon.lean",
     "(hv : ConvexPos v) (harea : area v = 1) :\n    Sides m where",
     "(hv : ConvexPos v) (harea : area v = 2) :\n    Sides m where"),
    ("convex: degenerate triangle allowed", "ConvexPolygon.lean",
     "lemma convexPos_triangle {w : Fin 3 → ℝ × ℝ} (harea : 0 < area w) : ConvexPos w := by",
     "lemma convexPos_triangle {w : Fin 3 → ℝ × ℝ} (harea : 0 ≤ area w) : ConvexPos w := by"),
    ("convex: triangle limit with unsquared lengths", "ConvexPolygon.lean",
     "(nhds (ENNReal.ofReal (ptri (len w 0 ^ 2) (len w 1 ^ 2) (len w 2 ^ 2)))) := by",
     "(nhds (ENNReal.ofReal (ptri (len w 0) (len w 1) (len w 2)))) := by"),
    ("superpose: w0 of a sum is a sum", "../Poisson/Superpose.lean",
     "w0 (Λ₁ + Λ₂) = w0 Λ₁ * w0 Λ₂ := by", "w0 (Λ₁ + Λ₂) = w0 Λ₁ + w0 Λ₂ := by"),
    ("superpose: wrong binomial coefficient", "../Poisson/Superpose.lean",
     "      ∑ p ∈ antidiagonal n, (n.choose p.1 : ℝ≥0∞) * pairInt Λ₁ Λ₂ G p.1 p.2 := by",
     "      ∑ p ∈ antidiagonal n, ((n + 1).choose p.1 : ℝ≥0∞) * pairInt Λ₁ Λ₂ G p.1 p.2 := by"),
    ("superpose: union has intensity of the first process", "../Poisson/Superpose.lean",
     "∂law Λ₂ ∂law Λ₁ = expect (Λ₁ + Λ₂) G := by", "∂law Λ₂ ∂law Λ₁ = expect Λ₁ G := by"),
    ("infinite: first n slabs have n+1 intensities", "../Poisson/Infinite.lean",
     "∂slabLaw Λs = ∫⁻ ω, f ω ∂law (∑ k : Fin n, Λs k) := by",
     "∂slabLaw Λs = ∫⁻ ω, f ω ∂law (∑ k : Fin (n + 1), Λs k) := by"),
    ("untruncated: overlapping slabs", "Untruncated.lean",
     "×ˢ Ioc (k : ℝ) (k + 1)))\n", "×ˢ Ioc (k : ℝ) (k + 2)))\n"),
    ("untruncated: witness margin Q/per", "Untruncated.lean",
     "noncomputable def δK : ℝ := Qs K / (2 * per K)", "noncomputable def δK : ℝ := Qs K / per K"),
    ("untruncated: tilt bound without the factor 2", "Untruncated.lean",
     "    |z.2.2| ≤ 2 * (∑ i, Ls K i * ((wp i).2.2 + (wm i).2.2)) / Qs K := by",
     "    |z.2.2| ≤ (∑ i, Ls K i * ((wp i).2.2 + (wm i).2.2)) / Qs K := by"),
    ("untruncated: E with a maximal copy", "Untruncated.lean",
     "    ∀ z' : Copy, (∀ p ∈ allPts ω, ¬ violates K z' p) → z.1 ≤ z'.1",
     "    ∀ z' : Copy, (∀ p ∈ allPts ω, ¬ violates K z' p) → z'.1 ≤ z.1"),
    ("untruncated: first n slabs = truncation at n+1", "Untruncated.lean",
     "    model K {ω | trunc n ω ∈ A} = PoissonPP.law (Λ K n) A := by",
     "    model K {ω | trunc n ω ∈ A} = PoissonPP.law (Λ K (n + 1)) A := by"),
    ("untruncated: vertex and segment terms multiplied", "Untruncated.lean",
     "    model K {ω | UFit K ω} = spatialVertexIntegral K * coneVertexDensity K +\n",
     "    model K {ω | UFit K ω} = spatialVertexIntegral K * coneVertexDensity K *\n"),
    ("untruncated: equilateral 13/48 -> 13/24", "Untruncated.lean",
     "model eqTri {ω | UFit eqTri ω} = ENNReal.ofReal (13 / 48) := by",
     "model eqTri {ω | UFit eqTri ω} = ENNReal.ofReal (13 / 24) := by"),
    ("theorem 1: equilateral 13/48 -> 13/24", "Theorem1.lean",
     "      (𝓝 (ENNReal.ofReal (13 / 48))) := by", "      (𝓝 (ENNReal.ofReal (13 / 24))) := by"),
    ("theorem 1: vertex and segment terms multiplied", "Theorem1.lean",
     "      (𝓝 (spatialVertexIntegral K * coneVertexDensity K +\n        ∑ p ∈ parPairs K, segDensity K p.1 p.2 * ∫⁻ w, chordWeightInf K p.1 w)) := by\n  intro K\n  have hG",
     "      (𝓝 (spatialVertexIntegral K * coneVertexDensity K *\n        ∑ p ∈ parPairs K, segDensity K p.1 p.2 * ∫⁻ w, chordWeightInf K p.1 w)) := by\n  intro K\n  have hG"),
    ("theorem 1: triangle limit with unsquared lengths", "Theorem1.lean",
     "      (𝓝 (ENNReal.ofReal (ptri (len w 0 ^ 2) (len w 1 ^ 2) (len w 2 ^ 2)))) := by",
     "      (𝓝 (ENNReal.ofReal (ptri (len w 0) (len w 1) (len w 2)))) := by"),
    ("theorem 1: largest instead of smallest copy", "Theorem1Physical.lean",
     "    (∀ l' θ' c', 0 < l' → (∀ j, x j ∈ simCopy K l' θ' c') → l ≤ l') ∧",
     "    (∀ l' θ' c', 0 < l' → (∀ j, x j ∈ simCopy K l' θ' c') → l' ≤ l) ∧"),
    ("theorem 1: copy contains the polygon instead of lying in it", "Theorem1Physical.lean",
     "    simCopy K l θ c ⊆ polygonRegion K\n", "    polygonRegion K ⊆ simCopy K l θ c\n"),
    ("theorem 1: tangent scale squared", "Theorem1Physical.lean",
     "    ∃ z : Copy, 0 < 1 + q * z.1 ∧ tangentScale q z = l ∧ q * z.2.2 = tan θ ∧",
     "    ∃ z : Copy, 0 < 1 + q * z.1 ∧ tangentScale q z = l ^ 2 ∧ q * z.2.2 = tan θ ∧"),
    ("theorem 1: tilt window above the coercivity bound", "Theorem1Physical.lean",
     "    (hηπ : η < π / 2) (htanr : tan η ≤ r) (htanQ : tan η ≤ Qs K / 4)",
     "    (hηπ : η < π / 2) (htanr : tan η ≤ r) (htanQ : Qs K / 4 ≤ tan η)"),
    ("step 0: symmetries without translation", "Theorem1Step0.lean",
     "  ∃ t : ℝ × ℝ, planeRotate θ₀ '' polygonRegion K = (· + t) '' polygonRegion K",
     "  ∃ t : ℝ × ℝ, t = 0 ∧ planeRotate θ₀ '' polygonRegion K = (· + t) '' polygonRegion K"),
    ("strict representative strictly below the optimum", "Theorem1Strict.lean",
     "    ∃ z, Feasible K (PoissonPP.config y) z ∧ z.1 = zs.1 ∧\n",
     "    ∃ z, Feasible K (PoissonPP.config y) z ∧ z.1 < zs.1 ∧\n"),
    ("poisson stabilisation to the complement", "Theorem1Events.lean",
     "      (EvN K R M n (PoissonPP.config ω.2) ↔ EvF K R M (PoissonPP.config ω.2)) := by",
     "      (EvN K R M n (PoissonPP.config ω.2) ↔ ¬ EvF K R M (PoissonPP.config ω.2)) := by"),
    ("witness threshold halved", "Theorem1Limit.lean",
     "noncomputable def T0 (M : ℝ) : ℝ := 2 * (4 * M * per K / Qs K) * Sb K + 2 * m * M",
     "noncomputable def T0 (M : ℝ) : ℝ := (4 * M * per K / Qs K) * Sb K + m * M"),
    ("model witness failure bound without the factor 2", "Theorem1Limit.lean",
     "      ∑ i : Fin m, 2 * ENNReal.ofReal (Real.exp (-(min (δK K) (Ls K i) * M))) := by",
     "      ∑ i : Fin m, ENNReal.ofReal (Real.exp (-(min (δK K) (Ls K i) * M))) := by"),
    ("tetrahedron: corner simplex volume 1/3", "Tetrahedron.lean",
     "lemma volume_corner : volume corner = ENNReal.ofReal (1 / 6) := by",
     "lemma volume_corner : volume corner = ENNReal.ofReal (1 / 3) := by"),
    ("tetrahedron: |det|/3", "Tetrahedron.lean",
     "      (fun P => |(homMat P).det| / 6) P) := by",
     "      (fun P => |(homMat P).det| / 3) P) := by"),
    ("tetrahedron: nonnegative instead of positive weights", "Tetrahedron.lean",
     "  ∃ l : Fin 4 → ℝ, (∀ r, 0 < l r) ∧ ∑ r, l r = 1 ∧ ∑ r, l r • P r = 0",
     "  ∃ l : Fin 4 → ℝ, (∀ r, 0 ≤ l r) ∧ ∑ r, l r = 1 ∧ ∑ r, l r • P r = 0"),
    ("regular polygon: circumradius = inradius", "RegularPolygon.lean",
     "noncomputable def rOut (q : ℕ) : ℝ := rIn q / cos (π / q)",
     "noncomputable def rOut (q : ℕ) : ℝ := rIn q"),
    ("regular polygon: vertices on the normals", "RegularPolygon.lean",
     "  fun j => (rOut q * cos (thA q j - π / q), rOut q * sin (thA q j - π / q))",
     "  fun j => (rOut q * cos (thA q j), rOut q * sin (thA q j))"),
    ("regular model: spatial r^3/(2c)", "RegularModel.lean",
     "    spatialVertexIntegral K = ENNReal.ofReal (q * tan (π / q) * r ^ 3 / (4 * c)) := by",
     "    spatialVertexIntegral K = ENNReal.ofReal (q * tan (π / q) * r ^ 3 / (2 * c)) := by"),
    ("regular model: cone c^4 instead of c^5", "RegularModel.lean",
     "    coneVertexDensity K = ENNReal.ofReal (4 * r * c ^ 5 * (q : ℝ) ^ 4) * prismE q := by",
     "    coneVertexDensity K = ENNReal.ofReal (4 * r * c ^ 4 * (q : ℝ) ^ 4) * prismE q := by"),
    ("regular model: height law not normalised", "RegularModel.lean",
     "noncomputable def unifH : Measure ℝ := (2 : ℝ≥0∞)⁻¹ • volume.restrict (Icc (-1 : ℝ) 1)",
     "noncomputable def unifH : Measure ℝ := volume.restrict (Icc (-1 : ℝ) 1)"),
    ("regular segment: density 4/3", "RegularSegment.lean",
     "    (k kb : Fin q) : segDensity K k kb = ENNReal.ofReal (8 * r * c ^ 4 / 3) := by",
     "    (k kb : Fin q) : segDensity K k kb = ENNReal.ofReal (4 * r * c ^ 4 / 3) := by"),
    ("regular segment: slope sum tan instead of cot", "RegularSegment.lean",
     "    slopeSum K k = 2 * c * (cos (π / (2 * m)) / sin (π / (2 * m))) := by",
     "    slopeSum K k = 2 * c * (sin (π / (2 * m)) / cos (π / (2 * m))) := by"),
    ("regular segment: parallel pairs for even q", "RegularSegment.lean",
     "lemma parPairs_odd [NeZero q] (hodd : ¬ Even q) : parPairs K = ∅ := by",
     "lemma parPairs_odd [NeZero q] (hodd : Even q) : parPairs K = ∅ := by"),
    ("regular chord: width term r/4", "RegularChord.lean",
     "      (r / 2 + slopeSum K k * (q * tan (π / q)) * r ^ 2 / 4)) := by",
     "      (r / 4 + slopeSum K k * (q * tan (π / q)) * r ^ 2 / 4)) := by"),
    ("corollary 3: segment term 8/(3q^3)", "Theorem1Regular.lean",
     "        if Even q then ENNReal.ofReal (8 / (3 * (q : ℝ) ^ 2)) else 0)) := by",
     "        if Even q then ENNReal.ofReal (8 / (3 * (q : ℝ) ^ 3)) else 0)) := by"),
    ("corollary 3: vertex term without tan", "Theorem1Regular.lean",
     "      (𝓝 (ENNReal.ofReal (q * tan (π / q)) * prismE q +",
     "      (𝓝 (ENNReal.ofReal (q : ℝ) * prismE q +"),
    ("corollary 3: segment term for odd q", "Theorem1Regular.lean",
     "        if Even q then ENNReal.ofReal (8 / (3 * (q : ℝ) ^ 2)) else 0)) := by",
     "        if Odd q then ENNReal.ofReal (8 / (3 * (q : ℝ) ^ 2)) else 0)) := by"),
]

def check(text: str) -> bool:
    MUT.write_text(text)
    r = subprocess.run(["nice", "-n", "15", "lake", "env", "lean", str(MUT)], cwd=ROOT,
                       capture_output=True, text=True, timeout=600)
    return r.returncode == 0 and "error" not in r.stdout

def main() -> int:
    bad = 0
    # optional filters: only mutants whose file name contains one of the arguments
    sel = [m for m in MUTANTS if not sys.argv[1:] or any(a in m[1] for a in sys.argv[1:])]
    try:
        for f in sorted({m[1] for m in sel}):
            ok = check((D / f).read_text())
            print(f"baseline {'ok' if ok else 'FAILS'}: {f}", flush=True)
            bad += not ok
        for name, f, old, new in sel:
            src = (D / f).read_text()
            if src.count(old) != 1:
                print(f"MUTATION DID NOT APPLY: {name}", flush=True); bad += 1; continue
            if check(src.replace(old, new)):
                print(f"MUTANT SURVIVED: {name}", flush=True); bad += 1
            else:
                print(f"rejected: {name}", flush=True)
    finally:
        MUT.unlink(missing_ok=True)
    print(f"{len(sel)} mutants, {bad} problems")
    return 1 if bad else 0

if __name__ == "__main__":
    sys.exit(main())
