import Mathlib.Analysis.LocallyConvex.Separation
import Mathlib.Analysis.Normed.Module.FiniteDimension
import Mathlib.LinearAlgebra.Matrix.DotProduct
import Mathlib.Topology.Algebra.Module.FiniteDimension

/-!
# Linear programming duality for finitely many constraints

The classification of optima of the limit LP needs the KKT condition at an attained minimum:
the objective is a positive combination of the rows of the tight constraints. Mathlib has
Farkas' lemma only for closed cones, so this file proves what is missing in `Fin d → ℝ`.

* `conic_caratheodory`: a positive combination can be rewritten on a linearly independent
  subfamily, still with positive coefficients.
* `isClosed_cone`: a finitely generated cone is closed (a finite union of images of the closed
  orthant under injective linear maps).
* `farkas`: either `e` is in the cone of the `vᵢ`, or some `y` has `vᵢ ⬝ y ≥ 0` and `e ⬝ y < 0`.
* `lp_kkt`: at a minimiser of `e ⬝ z` subject to `bᵢ ≤ rᵢ ⬝ z`, `e` is a positive combination
  of linearly independent tight rows.
-/

namespace LPDual

open Finset Matrix

/-! ### Conic Carathéodory -/

theorem conic_caratheodory {ι E : Type*} [AddCommGroup E] [Module ℝ E] (v : ι → E)
    (s : Finset ι) (l : ι → ℝ) (hl : ∀ i ∈ s, 0 < l i) :
    ∃ t ⊆ s, ∃ μ : ι → ℝ, LinearIndependent ℝ (fun i : t => v i) ∧ (∀ i ∈ t, 0 < μ i) ∧
      ∑ i ∈ t, μ i • v i = ∑ i ∈ s, l i • v i := by
  classical
  induction s using Finset.strongInduction generalizing l with
  | H s ih =>
  by_cases hli : LinearIndependent ℝ (fun i : s => v i)
  · exact ⟨s, subset_rfl, l, hli, hl, rfl⟩
  -- a dependency `∑ c v = 0` on `s` with a positive coefficient
  obtain ⟨c, hc0, hcpos⟩ : ∃ c : ι → ℝ, ∑ i ∈ s, c i • v i = 0 ∧ ∃ i ∈ s, 0 < c i := by
    rw [Fintype.linearIndependent_iff] at hli
    push Not at hli
    obtain ⟨g, hg, i0, hi0⟩ := hli
    let c : ι → ℝ := fun i => if h : i ∈ s then g ⟨i, h⟩ else 0
    have hsum : ∑ i ∈ s, c i • v i = 0 := by
      rw [← hg, ← Finset.sum_coe_sort s]
      exact Finset.sum_congr rfl fun i _ => by simp [c]
    rcases lt_or_gt_of_ne hi0 with hneg | hpos
    · refine ⟨fun i => -c i, ?_, i0, i0.2, ?_⟩
      · simp only [neg_smul, Finset.sum_neg_distrib, hsum, neg_zero]
      · simp [c, hneg]
    · exact ⟨c, hsum, i0, i0.2, by simp [c, hpos]⟩
  let P := s.filter fun i => 0 < c i
  have hP : P.Nonempty := by
    obtain ⟨i, hi, hci⟩ := hcpos; exact ⟨i, Finset.mem_filter.mpr ⟨hi, hci⟩⟩
  obtain ⟨i1, hi1, hmin⟩ := Finset.exists_min_image P (fun i => l i / c i) hP
  have hi1' := Finset.mem_filter.mp hi1
  set τ := l i1 / c i1 with hτ
  have hτpos : 0 < τ := div_pos (hl i1 hi1'.1) hi1'.2
  let l' : ι → ℝ := fun i => l i - τ * c i
  have hl'nn : ∀ i ∈ s, 0 ≤ l' i := by
    intro i hi
    by_cases hci : 0 < c i
    · have h := hmin i (Finset.mem_filter.mpr ⟨hi, hci⟩)
      have : τ * c i ≤ l i := by rw [le_div_iff₀ hci] at h; linarith
      simp only [l']; linarith
    · have : τ * c i ≤ 0 := mul_nonpos_of_nonneg_of_nonpos hτpos.le (not_lt.mp hci)
      simp only [l']; linarith [hl i hi]
  have hl'1 : l' i1 = 0 := by
    simp only [l', hτ]; rw [div_mul_cancel₀ _ hi1'.2.ne']; ring
  have hsum' : ∑ i ∈ s, l' i • v i = ∑ i ∈ s, l i • v i := by
    simp only [l', sub_smul, Finset.sum_sub_distrib, mul_smul, ← Finset.smul_sum, hc0,
      smul_zero, sub_zero]
  let s' := s.filter fun i => 0 < l' i
  have hss : s' ⊂ s := by
    refine Finset.ssubset_iff_subset_ne.mpr ⟨Finset.filter_subset _ _, fun h => ?_⟩
    have : i1 ∈ s' := h ▸ hi1'.1
    simp [s', hl'1] at this
  have hsub : ∑ i ∈ s', l' i • v i = ∑ i ∈ s, l' i • v i := by
    apply Finset.sum_subset (Finset.filter_subset _ _)
    intro i hi hni
    have : l' i = 0 := le_antisymm (by simpa [s', hi] using hni) (hl'nn i hi)
    simp [this]
  obtain ⟨t, hts, μ, hμ, hpos, heq⟩ :=
    ih s' hss l' fun i hi => (Finset.mem_filter.mp hi).2
  exact ⟨t, hts.trans (Finset.filter_subset _ _), μ, hμ, hpos, by rw [heq, hsub, hsum']⟩

/-! ### Finitely generated cones are closed -/

variable {d : ℕ}

/-- The cone generated by a finite family. -/
def cone {ι : Type*} [Fintype ι] (v : ι → Fin d → ℝ) : Set (Fin d → ℝ) :=
  {x | ∃ l : ι → ℝ, (∀ i, 0 ≤ l i) ∧ x = ∑ i, l i • v i}

/-- The linear map `μ ↦ ∑ μᵢ vᵢ` on a subfamily. -/
def combo {ι : Type*} (v : ι → Fin d → ℝ) (t : Finset ι) : (t → ℝ) →ₗ[ℝ] (Fin d → ℝ) where
  toFun μ := ∑ i, μ i • v i
  map_add' μ μ' := by simp [add_smul, Finset.sum_add_distrib]
  map_smul' a μ := by simp [mul_smul, Finset.smul_sum]

lemma combo_apply {ι : Type*} (v : ι → Fin d → ℝ) (t : Finset ι) (μ : t → ℝ) :
    combo v t μ = ∑ i, μ i • v i := rfl

lemma cone_eq_iUnion {ι : Type*} [Fintype ι] (v : ι → Fin d → ℝ) :
    cone v = ⋃ t : Finset ι, ⋃ (_ : LinearIndependent ℝ (fun i : t => v i)),
      combo v t '' {μ | ∀ i, 0 ≤ μ i} := by
  classical
  ext x
  simp only [Set.mem_iUnion, Set.mem_image, Set.mem_ofPred_eq]
  constructor
  · rintro ⟨l, hl, rfl⟩
    let s := Finset.univ.filter fun i => 0 < l i
    have hs : ∑ i ∈ s, l i • v i = ∑ i, l i • v i := by
      apply Finset.sum_subset (Finset.subset_univ _)
      intro i _ hi
      have : l i = 0 := le_antisymm (by simpa [s] using hi) (hl i)
      simp [this]
    obtain ⟨t, -, μ, hμ, hpos, heq⟩ :=
      conic_caratheodory v s l fun i hi => (Finset.mem_filter.mp hi).2
    refine ⟨t, hμ, fun i => μ i, fun i => (hpos i i.2).le, ?_⟩
    rw [combo_apply, Finset.sum_coe_sort t (fun i => μ i • v i), heq, hs]
  · rintro ⟨t, -, μ, hμ, rfl⟩
    refine ⟨fun i => if h : i ∈ t then μ ⟨i, h⟩ else 0, fun i => ?_, ?_⟩
    · by_cases h : i ∈ t <;> simp [h, hμ]
    · rw [combo_apply, ← Finset.sum_subset (Finset.subset_univ t) (fun i _ hi => by simp [hi]),
        ← Finset.sum_coe_sort t]
      exact Finset.sum_congr rfl fun i _ => by simp

theorem isClosed_cone {ι : Type*} [Fintype ι] (v : ι → Fin d → ℝ) : IsClosed (cone v) := by
  rw [cone_eq_iUnion]
  refine isClosed_iUnion_of_finite fun t => isClosed_iUnion_of_finite fun hli => ?_
  have hker : LinearMap.ker (combo v t) = ⊥ := by
    rw [LinearMap.ker_eq_bot']
    intro μ hμ
    funext i
    exact Fintype.linearIndependent_iff.mp hli μ hμ i
  have hemb := LinearMap.isClosedEmbedding_of_injective hker
  apply hemb.isClosedMap
  simp only [Set.ofPred_forall]
  exact isClosed_iInter fun i => isClosed_le continuous_const (continuous_apply i)

lemma convex_cone {ι : Type*} [Fintype ι] (v : ι → Fin d → ℝ) : Convex ℝ (cone v) := by
  rintro x ⟨l, hl, rfl⟩ y ⟨l', hl', rfl⟩ a b ha hb _
  refine ⟨fun i => a * l i + b * l' i, fun i => by have := hl i; have := hl' i; positivity, ?_⟩
  simp only [Finset.smul_sum, add_smul, mul_smul, Finset.sum_add_distrib]

lemma smul_mem_cone {ι : Type*} [Fintype ι] (v : ι → Fin d → ℝ) (i : ι) {a : ℝ} (ha : 0 ≤ a) :
    a • v i ∈ cone v := by
  classical
  refine ⟨Pi.single i a, fun j => ?_, ?_⟩
  · by_cases h : j = i
    · subst h; simp [ha]
    · simp [h]
  · rw [Finset.sum_eq_single i (fun j _ hj => by simp [hj]) (by simp)]
    simp

/-! ### Farkas -/

theorem farkas {ι : Type*} [Fintype ι] (v : ι → Fin d → ℝ) (e : Fin d → ℝ) (he : e ∉ cone v) :
    ∃ y : Fin d → ℝ, (∀ i, 0 ≤ v i ⬝ᵥ y) ∧ e ⬝ᵥ y < 0 := by
  obtain ⟨f, u, hfu, hb⟩ :=
    geometric_hahn_banach_point_closed (convex_cone v) (isClosed_cone v) he
  have hu : u < 0 := by
    have := hb 0 ⟨0, fun _ => le_rfl, by simp⟩
    simpa using this
  let y : Fin d → ℝ := fun j => f (Pi.single j 1)
  have hf : ∀ x : Fin d → ℝ, f x = x ⬝ᵥ y := by
    intro x
    conv_lhs => rw [show x = ∑ j, x j • Pi.single j (1 : ℝ) by
      ext k; simp [Finset.sum_apply, Pi.single_apply]]
    simp [map_sum, map_smul, dotProduct, y]
  refine ⟨y, fun i => ?_, by rw [← hf]; linarith⟩
  rw [← hf]
  by_contra hneg
  push Not at hneg
  have hmem := smul_mem_cone v i (show 0 ≤ u / f (v i) from div_nonneg_of_nonpos hu.le hneg.le)
  have := hb _ hmem
  rw [map_smul, smul_eq_mul, div_mul_cancel₀ _ hneg.ne] at this
  exact lt_irrefl _ this

/-! ### KKT at an attained minimum -/

/-- **KKT for a linear program.** If `z` minimises `e ⬝ z` subject to `bᵢ ≤ rᵢ ⬝ z`, then `e` is
a positive combination of linearly independent rows of constraints tight at `z`. -/
theorem lp_kkt {ι : Type*} [Fintype ι] (r : ι → Fin d → ℝ) (b : ι → ℝ) (e z : Fin d → ℝ)
    (hz : ∀ i, b i ≤ r i ⬝ᵥ z) (hopt : ∀ z', (∀ i, b i ≤ r i ⬝ᵥ z') → e ⬝ᵥ z ≤ e ⬝ᵥ z') :
    ∃ t : Finset ι, ∃ μ : ι → ℝ, (∀ i ∈ t, r i ⬝ᵥ z = b i) ∧ (∀ i ∈ t, 0 < μ i) ∧
      LinearIndependent ℝ (fun i : t => r i) ∧ e = ∑ i ∈ t, μ i • r i := by
  classical
  let T := Finset.univ.filter fun i => r i ⬝ᵥ z = b i
  -- `e` lies in the cone of the tight rows
  have hcone : e ∈ cone (fun i : T => r i) := by
    by_contra hne
    obtain ⟨y, hy, hey⟩ := farkas _ e hne
    -- step along `y` while the slack constraints stay satisfied
    let δ : ι → ℝ := fun i => (r i ⬝ᵥ z - b i) / (|r i ⬝ᵥ y| + 1)
    let N := Finset.univ.filter fun i => r i ⬝ᵥ z ≠ b i
    let τ : ℝ := if h : N.Nonempty then N.inf' h δ else 1
    have hδ : ∀ i ∈ N, 0 < δ i := by
      intro i hi
      have h1 : r i ⬝ᵥ z ≠ b i := (Finset.mem_filter.mp hi).2
      exact div_pos (sub_pos.mpr (lt_of_le_of_ne (hz i) (Ne.symm h1))) (by positivity)
    have hτ : 0 < τ := by
      simp only [τ]
      split_ifs with h
      · obtain ⟨j, hj, hjm⟩ := Finset.exists_min_image N δ h
        rw [show N.inf' h δ = δ j from le_antisymm (Finset.inf'_le _ hj)
          (Finset.le_inf' _ _ fun i hi => hjm i hi)]
        exact hδ j hj
      · exact one_pos
    have hτN : ∀ i ∈ N, τ ≤ δ i := by
      intro i hi
      have hN : N.Nonempty := ⟨i, hi⟩
      simp only [τ, dif_pos hN]
      exact Finset.inf'_le _ hi
    have hfeas : ∀ i, b i ≤ r i ⬝ᵥ (z + τ • y) := by
      intro i
      rw [dotProduct_add, dotProduct_smul, smul_eq_mul]
      by_cases ht : r i ⬝ᵥ z = b i
      · have := hy ⟨i, Finset.mem_filter.mpr ⟨Finset.mem_univ _, ht⟩⟩
        have := mul_nonneg hτ.le this
        linarith
      · have hi : i ∈ N := Finset.mem_filter.mpr ⟨Finset.mem_univ _, ht⟩
        have h1 := hτN i hi
        have hpos : 0 < |r i ⬝ᵥ y| + 1 := by positivity
        have h2 : τ * (|r i ⬝ᵥ y| + 1) ≤ r i ⬝ᵥ z - b i := by
          rw [show δ i = (r i ⬝ᵥ z - b i) / (|r i ⬝ᵥ y| + 1) from rfl, le_div_iff₀ hpos] at h1
          exact h1
        have h3 : -(τ * |r i ⬝ᵥ y|) ≤ τ * (r i ⬝ᵥ y) := by
          have := neg_abs_le (r i ⬝ᵥ y)
          nlinarith [hτ]
        nlinarith
    have := hopt _ hfeas
    rw [dotProduct_add, dotProduct_smul, smul_eq_mul] at this
    have : 0 ≤ τ * (e ⬝ᵥ y) := by linarith
    have : τ * (e ⬝ᵥ y) < 0 := mul_neg_of_pos_of_neg hτ hey
    linarith
  obtain ⟨l, hl, hle⟩ := hcone
  -- move to `ι` and apply Carathéodory
  let L : ι → ℝ := fun i => if h : i ∈ T then l ⟨i, h⟩ else 0
  let s := T.filter fun i => 0 < L i
  have hs : ∑ i ∈ s, L i • r i = e := by
    rw [hle]
    have h1 : ∑ i ∈ s, L i • r i = ∑ i ∈ T, L i • r i := by
      apply Finset.sum_subset (Finset.filter_subset _ _)
      intro i hi hni
      have h0 : L i = 0 := by
        have hnn : 0 ≤ L i := by simp only [L, dif_pos hi]; exact hl _
        exact le_antisymm (by simpa [s, hi] using hni) hnn
      simp [h0]
    rw [h1, ← Finset.sum_coe_sort T]
    exact Finset.sum_congr rfl fun i _ => by simp [L]
  obtain ⟨t, hts, μ, hμ, hpos, heq⟩ :=
    conic_caratheodory r s L fun i hi => (Finset.mem_filter.mp hi).2
  refine ⟨t, μ, fun i hi => ?_, hpos, hμ, by rw [heq, hs]⟩
  exact (Finset.mem_filter.mp (Finset.mem_filter.mp (hts hi)).1).2

end LPDual
