"""Export the certificate (verify/out) as Lean data for AlmostSquares.

Explicit.lean: the 151 base tilings (fill/) and the six small ones (small/), as (n, tiles).
Inflations.lean: every inflation record of cover112/cover110 as (S, v(S), t0, u, v); Classes.lean derives the
tilings from them through the inflation lemma and Lemma 4 (all_scales).
usage: python3 gen_lean.py   (run from lean/; rewrites AlmostSquares/Explicit.lean and Inflations.lean)
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ANC = Path(__file__).resolve().parent.parent / "verify" / "out"


def tiling(f: Path) -> list[tuple[int, int, int, int]]:
    rows = [ln.split() for ln in f.read_text().splitlines()
            if ln.strip() and ln.strip() != "SOL" and not ln.startswith("COUNT")]
    return [tuple(map(int, r[1:5])) for r in rows]


def squares(S: int) -> list[tuple[int, int, int]]:
    lines = (ANC / f"sq{S}.txt").read_text().splitlines()
    return [tuple(map(int, ln.split())) for ln in lines[1:] if ln.strip()]


def aff(a: int, b: int) -> str:
    return f"⟨{a}, {b}⟩"



def decode_rect(code: str) -> tuple[int, int, list[tuple[int, int, int]]]:
    """Squares (side, x, y) of the squared rectangle with Bouwkamp code `code` (as in verify/src/fill.py)."""
    groups = [list(map(int, g.split(","))) for g in re.findall(r"\(([^)]*)\)", code)]
    W = sum(groups[0])
    H = sum(s * s for g in groups for s in g) // W
    depth = [0] * W
    placed = []
    for g in groups:
        d = min(depth)
        x = depth.index(d)
        for s in g:
            assert all(depth[c] == d for c in range(x, x + s)), "bad code"
            placed.append((s, x, d))
            for c in range(x, x + s):
                depth[c] += s
            x += s
    assert all(v == H for v in depth), "not full"
    return W, H, [(s, x, H - top - s) for s, x, top in placed]

def main() -> None:
    dest = Path(__file__).resolve().parent / "AlmostSquares"
    ex = []
    for d in ("small", "fill"):
        for f in sorted((ANC / d).glob("n*.txt"), key=lambda p: int(p.stem[1:])):
            ts = tiling(f)
            ex.append(f"  ({f.stem[1:]}, [" + ", ".join(f"mk {w} {h} {x} {y}" for w, h, x, y in ts) + "])")
    (dest / "Explicit.lean").write_text(
        "/- Generated by friedman-almost-squares/verify/gen_lean.py: explicit tilings `(n, tiles)`. -/\n"
        "import AlmostSquares.Basic\n\nnamespace AlmostSq\n\n"
        "/-- The 6 small tilings and the 151 base tilings, tiles as `mk w h x y`. -/\n"
        "def explicit : List (ℕ × List Tile) := [\n" + ",\n".join(ex) + "]\n\n"
        "theorem explicit_ok : explicit.all (fun e => check e.1 e.2) = true := by decide +kernel\n\n"
        f"theorem explicit_length : explicit.length = {len(ex)} := by decide +kernel\n\nend AlmostSq\n")
    cls = []
    for S in (112, 110):
        for ln in (ANC / f"cover{S}.jsonl").read_text().splitlines():
            r = json.loads(ln)
            if not r["t0"]:
                continue
            tabs = []
            for key in ("u", "v"):
                tabs.append("[" + ", ".join(f"({a}, {x})" for a, x in sorted((int(k), x) for k, x in r[key].items()) if x) + "]")
            cls.append(f"  ⟨{S}, {r['V']}, {r['t0']}, {tabs[0]}, {tabs[1]}⟩")
    (dest / "Inflations.lean").write_text(
        "/- Generated by friedman-almost-squares/verify/gen_lean.py: the residue classes of Section 4. -/\n"
        "import AlmostSquares.Classes\n\nnamespace AlmostSq\n\n"
        "/-! Inflations of the squared squares of sides 112 and 110: `⟨S, v(S), t₀, u, v⟩`, shifts given by\n"
        "    their nonzero values. -/\n\n"
        + "".join(f"def inflations{k} : List Infl := [\n" + ",\n".join(cls[16 * k:16 * k + 16]) + "]\n\n"
                  f"theorem inflations{k}_ok : inflations{k}.all inflOK = true := by decide +kernel\n\n"
                  for k in range((len(cls) + 15) // 16))
        + "def inflations : List Infl :=\n  " + " ++ ".join(f"inflations{k}" for k in range((len(cls) + 15) // 16)) + "\n\n"
        "/-- Every class satisfies the hypotheses of Lemma 4 at its threshold (checked in pieces of 16, to bound\n"
        "    the kernel's memory). -/\n"
        "theorem inflations_ok : inflations.all inflOK = true := by\n"
        "  simp only [inflations, List.all_append, Bool.and_eq_true]\n"
        "  exact " + "⟨" * ((len(cls) + 15) // 16 - 1) + ", ".join(
            [f"inflations0_ok"] + [f"inflations{k}_ok⟩" for k in range(1, (len(cls) + 15) // 16)]) + "\n\n"
        f"theorem inflations_length : inflations.length = {len(cls)} := by decide +kernel\n\nend AlmostSq\n")
    # Reach.lean: the 57 x 55 rectangle at t = 1 and Moron's rectangle at t = 2, 3 (Section 4).
    reach = ANC / "reach"
    W, H, sq57 = decode_rect("(30,27)(3,11,13)(25,8)(17,2)(15)")
    def tabl(d):
        return "[" + ", ".join(f"({a}, {x})" for a, x in sorted((int(k), x) for k, x in d.items())) + "]"
    rs = [json.loads(ln) for ln in (reach / "r57.jsonl").read_text().splitlines()]
    ms = [json.loads(ln) for ln in (reach / "moron.jsonl").read_text().splitlines()]
    assert not any(m["flip"] for m in ms)
    (dest / "Reach.lean").write_text(
        "/- Generated by lean/gen_lean.py from verify/out/reach (verify/verify/base_reach.py):\n"
        "   one squared rectangle at one fixed scale, inflated to explicit tilings (Section 4). -/\n"
        "import AlmostSquares.Counts\n\nnamespace AlmostSq\n\n"
        "/-- The order-10 squared rectangle, 57 by 55, code `(30,27)(3,11,13)(25,8)(17,2)(15)`. -/\n"
        "def code57 : List (List ℕ) := [[30, 27], [3, 11, 13], [25, 8], [17, 2], [15]]\n\n"
        "def rect57 : List Tile := [" + ", ".join(f"sq {s_} {x} {y}" for s_, x, y in sq57) + "]\n\n"
        "theorem rect57_code : codeIs code57 57 55 rect57 = true := by decide +kernel\n\n"
        "/-- One tiling: the rectangle (transposed if `flip`) at `t = 1`, shifted by `u`, `v`, tiles `R_n`. -/\n"
        "structure Reach where\n  n : ℕ\n  flip : Bool\n  u : List (ℤ × ℤ)\n  v : List (ℤ × ℤ)\n\n"
        "def reach57 : List Reach := [\n" +
        ",\n".join(f"  ⟨{r['n']}, {'true' if r['flip'] else 'false'}, {tabl(r['u'])}, {tabl(r['v'])}⟩" for r in rs) + "]\n\n"
        "def reach57OK (e : Reach) : Bool :=\n"
        "  if e.flip then rectOK 55 57 (rect57.map Tile.swap) 1 (tab e.u) (tab e.v) e.n\n"
        "  else rectOK 57 55 rect57 1 (tab e.u) (tab e.v) e.n\n\n"
        "/-- Every entry is a valid tiling of `R_n` by the inflated rectangle. -/\n"
        "theorem reach57_ok : reach57.all reach57OK = true := by decide +kernel\n\n"
        "theorem reach57OK_sound {e : Reach} (h : reach57OK e = true) :\n"
        "    ∃ ts, Admissible e.n ts := by\n"
        "  unfold reach57OK at h\n"
        "  split at h\n"
        "  · exact ⟨_, rectOK_sound h⟩\n"
        "  · exact ⟨_, rectOK_sound h⟩\n\n"
        "/-- The single 57 × 55 rectangle gives tilings for 67 of the 151 values left by the classes. -/\n"
        f"theorem reach57_count : (reach57.map Reach.n).dedup.length = {len(rs)} ∧\n"
        "    (reach57.map Reach.n).all (fun n => uncovered.contains n) = true := by decide +kernel\n\n"
        + "".join(f"/-- Moroń's rectangle at `t = {m['t']}` tiles `R_{{{m['n']}}}`. -/\n"
                  f"theorem moron_{m['n']} : rectOK 33 32 moron {m['t']} (tab {tabl(m['u'])}) (tab {tabl(m['v'])}) {m['n']} = true := by\n"
                  "  decide +kernel\n\n" for m in ms)
        + "end AlmostSq\n")
    print(len(ex), "explicit tilings;", len(cls), "inflation classes;", len(rs), "57x55 tilings;", len(ms), "Moron tilings")


if __name__ == "__main__":
    main()
