import EnclosingCopy.Poisson.Basic
import Mathlib.MeasureTheory.Measure.Sum
import Mathlib.Probability.Independence.Basic

/-!
# A probability space for the finite-intensity Poisson process

The sample space records the number of points and their labelled finite tuple. Its
probability measure is the mixed-binomial law already used in `PoissonPP.expect`.
`law_prob` connects measurable configuration events to that existing API.
`void_disjoint` proves independence of void events in disjoint regions, without
assuming independence as an extra hypothesis.
-/

namespace PoissonPP
open MeasureTheory Set ENNReal
variable {α : Type*} [MeasurableSpace α]

abbrev Sample (α : Type*) := Σ n : ℕ, Fin n → α

lemma measurable_sampleMk (n : ℕ) :
    Measurable (@Sigma.mk ℕ (fun n => Fin n → α) n) :=
  Measurable.of_le_map (iInf_le _ n)

lemma measurableSet_sample {B : Set (Sample α)}
    (hB : ∀ n, MeasurableSet ((Sigma.mk n) ⁻¹' B)) : MeasurableSet B := by
  exact MeasurableSpace.measurableSet_iInf.mpr hB

/-- The labelled mixed-binomial Poisson law. Configuration events ignore labels. -/
noncomputable def law (Λ : Measure α) : Measure (Sample α) :=
  Measure.sum fun n : ℕ => (w0 Λ / n.factorial) •
    Measure.map (Sigma.mk n) (Measure.pi fun _ : Fin n => Λ)

lemma lintegral_law (Λ : Measure α) (f : Sample α → ℝ≥0∞) (hf : Measurable f) :
    (∫⁻ ω, f ω ∂law Λ) =
      ∑' n : ℕ, w0 Λ / n.factorial *
        ∫⁻ x : Fin n → α, f ⟨n, x⟩ ∂(Measure.pi fun _ => Λ) := by
  rw [law, lintegral_sum_measure]
  congr 1
  funext n
  rw [lintegral_smul_measure, lintegral_map hf (measurable_sampleMk n)]
  rfl

instance (Λ : Measure α) [IsFiniteMeasure Λ] : IsProbabilityMeasure (law Λ) := by
  constructor
  have h := lintegral_law Λ (fun _ => 1) measurable_const
  rw [lintegral_const, one_mul] at h
  exact h.trans (expect_one Λ)

/-- The probability measure agrees with the original configuration probability API. -/
theorem law_prob (Λ : Measure α) (E : Multiset α → Prop)
    (hE : ∀ n : ℕ, MeasurableSet {x : Fin n → α | E (config x)}) :
    law Λ {ω | E (config ω.2)} = prob Λ E := by
  have hset : MeasurableSet {ω : Sample α | E (config ω.2)} :=
    measurableSet_sample hE
  rw [← lintegral_indicator_one hset, lintegral_law Λ _ (measurable_one.indicator hset)]
  rfl

lemma measurable_void_tuple {B : Set α} (hB : MeasurableSet B) (n : ℕ) :
    MeasurableSet {x : Fin n → α | ∀ p ∈ config x, p ∉ B} := by
  have he : {x : Fin n → α | ∀ p ∈ config x, p ∉ B} = univ.pi (fun _ => Bᶜ) := by
    ext x; simp [mem_config]
  rw [he]
  exact MeasurableSet.univ_pi fun _ => hB.compl

variable (Λ : Measure α) [IsFiniteMeasure Λ]

lemma expect_const (a : ℝ≥0∞) : expect Λ (fun _ => a) = a := by
  have he : expect Λ (fun _ => a) = a * expect Λ (fun _ => 1) := by
    unfold expect
    rw [← ENNReal.tsum_mul_left]
    congr 1
    funext n
    rw [lintegral_const_pi, lintegral_const_pi]
    ring
  rw [he, expect_one, mul_one]

theorem law_void {B : Set α} (hB : MeasurableSet B) :
    law Λ {ω | ∀ p ∈ config ω.2, p ∉ B} =
      ENNReal.ofReal (Real.exp (-(Λ B).toReal)) := by
  rw [law_prob Λ (fun μ => ∀ p ∈ μ, p ∉ B) (measurable_void_tuple hB), void_prob Λ hB]

/-- Void events for two disjoint measurable regions factor in the actual Poisson law. -/
theorem void_disjoint {B C : Set α} (hB : MeasurableSet B) (hC : MeasurableSet C)
    (hBC : Disjoint B C) :
    law Λ ({ω | ∀ p ∈ config ω.2, p ∉ B} ∩ {ω | ∀ p ∈ config ω.2, p ∉ C}) =
      law Λ {ω | ∀ p ∈ config ω.2, p ∉ B} *
        law Λ {ω | ∀ p ∈ config ω.2, p ∉ C} := by
  have he : ({ω : Sample α | ∀ p ∈ config ω.2, p ∉ B} ∩
      {ω | ∀ p ∈ config ω.2, p ∉ C}) = {ω | ∀ p ∈ config ω.2, p ∉ B ∪ C} := by
    ext ω; simp only [mem_inter_iff, mem_ofPred_eq, mem_union, not_or]
    exact ⟨fun h p hp => ⟨h.1 p hp, h.2 p hp⟩,
      fun h => ⟨fun p hp => (h p hp).1, fun p hp => (h p hp).2⟩⟩
  rw [he, law_void Λ (hB.union hC), law_void Λ hB, law_void Λ hC,
    measure_union hBC hC, ENNReal.toReal_add (measure_ne_top _ _) (measure_ne_top _ _),
    neg_add, Real.exp_add, ENNReal.ofReal_mul (Real.exp_pos _).le]

def voidEvent (B : Set α) : Set (Sample α) := {ω | ∀ p ∈ config ω.2, p ∉ B}

/-- The sigma-field generated by observing void events inside a specified region. -/
def voidFamily (B : Set α) : Set (Set (Sample α)) :=
  {E | ∃ D : Set α, D ⊆ B ∧ MeasurableSet D ∧ E = voidEvent D}

omit [MeasurableSpace α] in
lemma voidEvent_union (B C : Set α) : voidEvent (B ∪ C) = voidEvent B ∩ voidEvent C := by
  ext ω
  simp only [voidEvent, mem_ofPred_eq, mem_inter_iff, mem_union, not_or]
  exact ⟨fun h => ⟨fun p hp => (h p hp).1, fun p hp => (h p hp).2⟩,
    fun h p hp => ⟨h.1 p hp, h.2 p hp⟩⟩

lemma voidFamily_measurable (B : Set α) :
    ∀ E ∈ voidFamily B, MeasurableSet E := by
  rintro E ⟨D, -, hD, rfl⟩
  exact measurableSet_sample (measurable_void_tuple hD)

lemma voidFamily_pi (B : Set α) : IsPiSystem (voidFamily B) := by
  rintro E ⟨D, hDB, hD, rfl⟩ F ⟨G, hGB, hG, rfl⟩ _
  exact ⟨D ∪ G, union_subset hDB hGB, hD.union hG, (voidEvent_union D G).symm⟩

/-- Independence of the sigma-fields of Poisson observations in two disjoint regions. -/
theorem void_sigma_independent {B C : Set α} (hBC : Disjoint B C) :
    ProbabilityTheory.Indep (MeasurableSpace.generateFrom (voidFamily B))
      (MeasurableSpace.generateFrom (voidFamily C)) (law Λ) := by
  have hind : ProbabilityTheory.IndepSets (voidFamily B) (voidFamily C) (law Λ) := by
    intro E F hE hF
    obtain ⟨D, hDB, hD, rfl⟩ := hE
    obtain ⟨G, hGC, hG, rfl⟩ := hF
    exact Filter.Eventually.of_forall fun _ => void_disjoint Λ hD hG (hBC.mono hDB hGC)
  exact ProbabilityTheory.IndepSets.indep' (voidFamily_measurable B) (voidFamily_measurable C)
    (voidFamily_pi B) (voidFamily_pi C) hind

theorem indep_of_void_measurable {B C : Set α} (hBC : Disjoint B C)
    {β γ : Type*} [MeasurableSpace β] [MeasurableSpace γ]
    (f : Sample α → β) (g : Sample α → γ)
    (hf : @Measurable _ _ (MeasurableSpace.generateFrom (voidFamily B)) _ f)
    (hg : @Measurable _ _ (MeasurableSpace.generateFrom (voidFamily C)) _ g) :
    ProbabilityTheory.IndepFun f g (law Λ) := by
  rw [ProbabilityTheory.IndepFun_iff_Indep]
  exact ProbabilityTheory.indep_of_indep_of_le (void_sigma_independent Λ hBC)
    hf.comap_le hg.comap_le

end PoissonPP
