"""Independent recheck for MSE 5150767 (shares no code with ../): no residues, no Gauss sums.

c_n(N) is computed from the power series and is periodic for N >= 1 with period L = lcm{2m : floor(n/m) odd}.
Functions on Z/L have the basis psi(N/h) [h | N], psi primitive of conductor f, f h | L. Solving for the coordinates
beta of c_n gives D_n(s) = sum beta h^{-s} L(s, psi), so the coefficient of L'(-1, psi) in I_n = -2 D_n'(-1) is
K_psi = -2 sum_h h beta_{psi,h}. For n = 5, 7, 9 this recomputes the conductor sets and the coefficients quoted in
the note, and I_n itself (with the log terms) against quadrature.

    python3 recheck.py            -> ALL AGREE / DISAGREE
    python3 recheck.py --mutant   -> uses period L/2; must DISAGREE
"""

import sys
from math import gcd, lcm

import mpmath as mp
import numpy as np

MUTANT = "--mutant" in sys.argv
mp.mp.dps = 30


def series(n, N):
    c = [1] + [0] * N
    for k in range(1, n + 1):
        c = [c[i] - (c[i - k] if i >= k else 0) for i in range(N + 1)]
        for i in range(k, N + 1):
            c[i] -= c[i - k]
    return c


def factor(n):
    out, p = {}, 2
    while p * p <= n:
        while n % p == 0:
            out[p] = out.get(p, 0) + 1
            n //= p
        p += 1
    if n > 1:
        out[n] = out.get(n, 0) + 1
    return out


def unit_chars(f):
    """All characters mod f: (Z/f)* is the product over p^k || f of cyclic groups generated by a primitive root
    (odd p), or by -1 and 5 (p = 2, k >= 3), lifted to residues mod f by the Chinese remainder theorem."""
    if f == 1:
        return [{0: 1}]
    gens = []  # (residue mod f, exact order)
    for p, k in factor(f).items():
        pk, rest = p ** k, f // p ** k
        lift = lambda x: next(y for y in range(x % pk, f + pk, pk) if y % rest == 1 % rest)
        phi = pk - pk // p
        if p == 2:
            if k >= 2:
                gens.append((lift(pk - 1), 2))
            if k >= 3:
                gens.append((lift(5), 2 ** (k - 2)))
        else:
            g = next(g for g in range(2, pk) if gcd(g, p) == 1 and all(pow(g, phi // q, pk) != 1 for q in factor(phi)))
            gens.append((lift(g), phi))
    units = [a for a in range(1, f) if gcd(a, f) == 1]
    rep = {}
    def walk(i, val, exps):
        if i == len(gens):
            rep[val] = tuple(exps)
            return
        a, o = gens[i]
        x = val
        for e in range(o):
            walk(i + 1, x, exps + [e])
            x = x * a % f
    walk(0, 1 % f, [])
    assert len(rep) == len(units) and all(pow(a, o, f) == 1 % f for a, o in gens)
    out = []
    def chars(i, roots):
        if i == len(gens):
            out.append({u: complex(np.prod([roots[k] ** rep[u][k] for k in range(len(gens))])) for u in units})
            return
        o = gens[i][1]
        for t in range(o):
            chars(i + 1, roots + [np.exp(2j * np.pi * t / o)])
    chars(0, [])
    return out


def primitive_even_and_odd(f):
    res = []
    for ch in unit_chars(f):
        prim = (
            all(
                any(abs(ch[u] - 1) > 1e-9 for u in ch if u % d == 1 % d)
                for d in range(1, f)
                if f % d == 0
            )
            if f > 1
            else True
        )
        if prim:
            res.append(ch)
    return res


def K_and_basis(n):
    fams = [m for m in range(1, n + 1) if (n // m) % 2]
    L = lcm(*[2 * m for m in fams])
    if MUTANT:
        L //= 2
    c = series(n, 3 * L)
    vec = np.array([c[N] for N in range(1, L + 1)], dtype=complex)
    assert MUTANT or all(c[N] == c[N + L] for N in range(1, 2 * L + 1)), "not periodic"
    cols, labels = [], []
    for f in (d for d in range(1, L + 1) if L % d == 0):
        for ch in primitive_even_and_odd(f):
            for h in (d for d in range(1, L // f + 1) if (L // f) % d == 0):
                col = np.array(
                    [
                        ch.get((N // h) % f if f > 1 else 0, 0) if N % h == 0 else 0
                        for N in range(1, L + 1)
                    ],
                    dtype=complex,
                )
                if f > 1:
                    col = np.array(
                        [
                            (ch.get((N // h) % f, 0) if N % h == 0 else 0)
                            for N in range(1, L + 1)
                        ],
                        dtype=complex,
                    )
                cols.append(col)
                labels.append(
                    (f, tuple(ch.get(u, 0) for u in range(f)) if f > 1 else (1,), h)
                )
    A = np.array(cols).T
    beta = np.linalg.solve(A, vec)
    K = {}
    for (f, tab, h), b in zip(labels, beta):
        K[(f, tab)] = K.get((f, tab), 0) - 2 * h * b
    return {k: v for k, v in K.items() if abs(v) > 1e-8}, labels, beta


def close(a, b, tol=1e-6):
    return abs(complex(a) - complex(b)) < tol


def find(K, f, vals):
    for (ff, tab), v in K.items():
        if ff == f and all(close(tab[r], x) for r, x in vals.items()):
            return v
    return 0


w = np.exp(2j * np.pi / 3)
ok = True
K5, _, _ = K_and_basis(5)
K7, _, _ = K_and_basis(7)
K9, _, _ = K_and_basis(9)
conds = {n: sorted({f for f, _ in K}) for n, K in ((5, K5), (7, K7), (9, K9))}
print("conductors", conds)
ok &= conds == {5: [1, 8], 7: [5, 12], 9: [1, 7, 8, 12, 16]}
ok &= close(find(K5, 8, {1: 1, 3: -1}), 4) and close(find(K5, 1, {0: 1}), -48)
ok &= close(find(K7, 5, {1: 1, 2: -1}), 20) and close(find(K7, 12, {1: 1, 5: -1}), -4)
ok &= close(find(K9, 7, {1: 1, 2: w**2, 3: w}), -20 - 4 * np.sqrt(3) * 1j)
ok &= close(find(K9, 16, {1: 1, 3: 1j, 5: -1j}), 2 - 2j)
print("coefficients found:", {n: len(K) for n, K in ((5, K5), (7, K7), (9, K9))})
print("ALL AGREE" if ok else "DISAGREE")
sys.exit(0 if ok else 1)
